import {readFileSync} from 'node:fs';import {describe,expect,it} from 'vitest'
const unit=readFileSync('deploy/relay/waypoint-relay.service','utf8'),env=readFileSync('deploy/relay/relay.env.example','utf8'),template=readFileSync('deploy/aws/waypoint-relay.yaml','utf8'),backup=readFileSync('deploy/relay/waypoint-relay-backup.sh','utf8'),caddy=readFileSync('deploy/relay/Caddyfile.waypoint-relay','utf8')
describe('native relay deployment artifacts',()=>{
 it('runs as a dedicated hardened identity with only explicit state paths',()=>{expect(unit).toMatch(/User=waypoint-relay/);expect(unit).toMatch(/NoNewPrivileges=true/);expect(unit).toMatch(/ProtectSystem=strict/);expect(unit).toMatch(/ReadWritePaths=\/var\/lib\/waypoint-relay/);expect(unit).toMatch(/ConditionPathExists=.*authority\.json/);expect(unit).toMatch(/IPAddressDeny=any/);expect(unit).toMatch(/IPAddressAllow=localhost/);expect(unit).not.toMatch(/docker/i)})
 it('contains no secrets and freezes loopback proxy TLS/database paths',()=>{expect(env).toMatch(/TLS_MODE=proxy-loopback/);expect(env).toMatch(/AUTHORITY_REGISTRY=.*authority/);expect(env).not.toMatch(/PASSWORD|TOKEN|SECRET=/)})
 it('rejects out-of-range IPv4 octets before AWS deployment',()=>{const pattern=template.match(/AllowedPattern: '([^']+)'/)?.[1];expect(pattern).toBeTruthy();expect('192.168.10.2/32').toMatch(new RegExp(pattern!));expect('999.999.999.999/32').not.toMatch(new RegExp(pattern!))})
 it('keeps AWS ingress bounded, metadata v2-only, storage encrypted, architecture fixed, and egress fail-closed',()=>{expect(template).toMatch(/AllowedValues: \[t4g\.small\]/);expect(template).toMatch(/HttpTokens: required/);expect(template).toMatch(/Encrypted: true/);expect(template).toMatch(/CidrIp: 127\.0\.0\.1\/32/);expect(template).not.toMatch(/SecurityGroupEgress: \[\]/);expect(template).not.toMatch(/0\.0\.0\.0\/0/);expect(template).not.toMatch(/DeletionPolicy: Snapshot/)})
 it('targets a compiled relay entrypoint that exists after build',()=>{expect(unit).toMatch(/dist-electron\/node\/relay\/entry\.js/)})
 it('uses authenticated backup encryption, a conservative sub-14-day cleanup, and TLS 1.3',()=>{expect(backup).toMatch(/backup-crypto\.mjs encrypt/);expect(backup).toMatch(/-mmin \+17280/);expect(backup).not.toMatch(/\+20160/);expect(caddy).toMatch(/protocols tls1\.3/)})
})
