import {readFileSync} from 'node:fs';import {describe,expect,it} from 'vitest'
const unit=readFileSync('deploy/relay/waypoint-relay.service','utf8'),env=readFileSync('deploy/relay/relay.env.example','utf8'),template=readFileSync('deploy/aws/waypoint-relay.yaml','utf8')
describe('native relay deployment artifacts',()=>{
 it('runs as a dedicated hardened identity with only explicit state paths',()=>{expect(unit).toMatch(/User=waypoint-relay/);expect(unit).toMatch(/NoNewPrivileges=true/);expect(unit).toMatch(/ProtectSystem=strict/);expect(unit).toMatch(/ReadWritePaths=\/var\/lib\/waypoint-relay/);expect(unit).toMatch(/ConditionPathExists=.*authority\.json/);expect(unit).toMatch(/RestartPreventExitStatus=78/);expect(unit).not.toMatch(/docker/i)})
 it('contains no secrets and requires explicit TLS/database paths',()=>{expect(env).toMatch(/TLS_CERT=.*fullchain/);expect(env).toMatch(/TLS_KEY=.*private-key/);expect(env).not.toMatch(/PASSWORD|TOKEN|SECRET=/)})
 it('rejects out-of-range IPv4 octets before AWS deployment',()=>{const pattern=template.match(/AllowedPattern: '([^']+)'/)?.[1];expect(pattern).toBeTruthy();expect('192.168.10.2/32').toMatch(new RegExp(pattern!));expect('999.999.999.999/32').not.toMatch(new RegExp(pattern!))})
 it('keeps AWS ingress bounded, metadata v2-only, storage encrypted, architecture fixed, and egress fail-closed',()=>{expect(template).toMatch(/AllowedValues: \[t4g\.small\]/);expect(template).toMatch(/HttpTokens: required/);expect(template).toMatch(/Encrypted: true/);expect(template).toMatch(/CidrIp: 127\.0\.0\.1\/32/);expect(template).not.toMatch(/SecurityGroupEgress: \[\]/);expect(template).not.toMatch(/0\.0\.0\.0\/0/);expect(template).not.toMatch(/DeletionPolicy: Snapshot/)})
 it('targets a compiled relay entrypoint that exists after build',()=>{expect(unit).toMatch(/dist-electron\/node\/relay\/entry\.js/)})
})
