import {copyFileSync,mkdirSync,mkdtempSync,writeFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {describe,expect,it} from 'vitest'
import {WorkspaceStore} from '../store.js'
import {WaypointCrypto} from './crypto.js'
import {DesktopSyncPump} from './desktop-sync-pump.js'
import type {ProtectedWorkspaceSecrets} from './protected-sync-vault.js'
import type {OpaqueRelayMessage} from '../../../node/relay/types.js'

describe('isolated two-device desktop sync matrix',()=>{
  it('materializes chats, messages, documents, graph, and resumed attachment bytes',async()=>{const root=mkdtempSync(path.join(tmpdir(),'waypoint-two-device-')),leftDb=path.join(root,'left','waypoint.sqlite'),rightDb=path.join(root,'right','waypoint.sqlite'),leftSeed=new WorkspaceStore(leftDb),workspace=leftSeed.createWorkspace('Shared',path.join(root,'left'));leftSeed.close();mkdirSync(path.dirname(rightDb),{recursive:true});copyFileSync(leftDb,rightDb);const left=new WorkspaceStore(leftDb),right=new WorkspaceStore(rightDb),crypto=await WaypointCrypto.create(),a=crypto.generateDevice('opaque_device_a_01'),b=crypto.generateDevice('opaque_device_b_01'),key=crypto.generateWorkspaceKey();left.configureSyncDevice(workspace.id,a.deviceId);right.configureSyncDevice(workspace.id,b.deviceId)
    const chat=left.captureChat(workspace.id,'Synced route','hello peer'),createdDocument=left.createDocument(workspace.id,'Shared note','body'),document=createdDocument.id,memory=left.createMemory(workspace.id,'Remember','fact',document),relationship=left.createRelationship(workspace.id,document,memory,'supports'),source=path.join(root,'sample.md');writeFileSync(source,Buffer.alloc(4*1024*1024+17,120));left.addAttachment(workspace.id,chat,'sample.md','text/markdown',source)
    const devices=[{...a,role:'owner',status:'active',enrolledAt:new Date().toISOString()},{...b,role:'peer',status:'active',enrolledAt:new Date().toISOString()}],queues=new Map([[a.deviceId,[] as OpaqueRelayMessage[]],[b.deviceId,[] as OpaqueRelayMessage[]]]),client=(deviceId:string)=>({listDevices:async()=>({devices}),enqueue:async(message:OpaqueRelayMessage)=>{queues.get(message.recipientDeviceId)!.push(message);return{messageId:message.messageId,acceptedAt:new Date().toISOString()}},pull:async()=>queues.get(deviceId)!.splice(0),acknowledge:async()=>true}),secrets=(device:typeof a):ProtectedWorkspaceSecrets=>({version:1,workspaceId:workspace.id,device,workspaceKey:key,keyEpoch:1,endpoint:'https://waypoint-relay.johnnycode.ai'})
    await new DesktopSyncPump(secrets(a),crypto,client(a.deviceId) as never,left).runOnce();const initial=queues.get(b.deviceId)!.splice(0),dropped=initial.pop();expect(dropped).toBeDefined();queues.get(b.deviceId)!.push(...initial);await new DesktopSyncPump(secrets(b),crypto,client(b.deviceId) as never,right).runOnce();expect(queues.get(a.deviceId)).toHaveLength(1);await new DesktopSyncPump(secrets(a),crypto,client(a.deviceId) as never,left).runOnce();expect(queues.get(b.deviceId)).toHaveLength(2);await new DesktopSyncPump(secrets(b),crypto,client(b.deviceId) as never,right).runOnce()
    expect(right.listChats(workspace.id)[0]).toMatchObject({id:chat,title:'Synced route'});expect(right.listChats(workspace.id)[0].messages[0].body).toBe('hello peer');expect(right.listDocuments(workspace.id)[0]).toMatchObject({id:document,body:'body'});expect(right.listMemories(workspace.id)[0]).toMatchObject({id:memory,body:'fact'});expect(right.graph(workspace.id).edges.some((edge)=>edge.id===relationship)).toBe(true);const attachment=right.listChatAttachments(workspace.id,chat)[0];expect(attachment).toMatchObject({name:'sample.md',bytes:4*1024*1024+17});left.close();right.close()})
  it('converges concurrent edits and makes an offline delete dominate a stale update',async()=>{const root=mkdtempSync(path.join(tmpdir(),'waypoint-conflict-matrix-')),leftDb=path.join(root,'left','waypoint.sqlite'),rightDb=path.join(root,'right','waypoint.sqlite'),seed=new WorkspaceStore(leftDb),workspace=seed.createWorkspace('Shared',path.join(root,'left')),document=seed.createDocument(workspace.id,'Route','base').id;for(const change of seed.pendingSyncChanges(workspace.id))seed.markSyncChangeRelayed(workspace.id,change.id);seed.close();mkdirSync(path.dirname(rightDb),{recursive:true});copyFileSync(leftDb,rightDb);const left=new WorkspaceStore(leftDb),right=new WorkspaceStore(rightDb),crypto=await WaypointCrypto.create(),a=crypto.generateDevice('opaque_device_a_02'),b=crypto.generateDevice('opaque_device_b_02'),key=crypto.generateWorkspaceKey();left.configureSyncDevice(workspace.id,a.deviceId);right.configureSyncDevice(workspace.id,b.deviceId);left.updateDocument(workspace.id,document,'Route','left edit');right.updateDocument(workspace.id,document,'Route','right edit')
    const devices=[{...a,role:'owner',status:'active',enrolledAt:new Date().toISOString()},{...b,role:'peer',status:'active',enrolledAt:new Date().toISOString()}],queues=new Map([[a.deviceId,[] as OpaqueRelayMessage[]],[b.deviceId,[] as OpaqueRelayMessage[]]]),client=(deviceId:string)=>({listDevices:async()=>({devices}),enqueue:async(message:OpaqueRelayMessage)=>{queues.get(message.recipientDeviceId)!.push(message);return{messageId:message.messageId,acceptedAt:new Date().toISOString()}},pull:async()=>queues.get(deviceId)!.splice(0),acknowledge:async()=>true}),secrets=(device:typeof a):ProtectedWorkspaceSecrets=>({version:1,workspaceId:workspace.id,device,workspaceKey:key,keyEpoch:1,endpoint:'https://waypoint-relay.johnnycode.ai'}),pump=(device:typeof a,store:WorkspaceStore)=>new DesktopSyncPump(secrets(device),crypto,client(device.deviceId) as never,store)
    await pump(a,left).runOnce();await pump(b,right).runOnce();await pump(a,left).runOnce();expect(left.listDocuments(workspace.id)[0].body).toBe(right.listDocuments(workspace.id)[0].body);expect(left.syncStatus(workspace.id)).toMatchObject({conflicts:1});right.updateDocument(workspace.id,document,'Route','offline stale');left.deleteObject(workspace.id,'document',document);await pump(a,left).runOnce();await pump(b,right).runOnce();await pump(a,left).runOnce();expect(left.listDocuments(workspace.id)).toEqual([]);expect(right.listDocuments(workspace.id)).toEqual([]);left.close();right.close()})
  it('lets a newly enrolled identity request an authoritative current snapshot',async()=>{const root=mkdtempSync(path.join(tmpdir(),'waypoint-snapshot-matrix-')),ownerDb=path.join(root,'owner','waypoint.sqlite'),peerDb=path.join(root,'peer','waypoint.sqlite'),seed=new WorkspaceStore(ownerDb),workspace=seed.createWorkspace('Shared',path.join(root,'owner'));for(const change of seed.pendingSyncChanges(workspace.id))seed.markSyncChangeRelayed(workspace.id,change.id);seed.close();mkdirSync(path.dirname(peerDb),{recursive:true});copyFileSync(ownerDb,peerDb);const ownerStore=new WorkspaceStore(ownerDb),peerStore=new WorkspaceStore(peerDb),historical=ownerStore.createDocument(workspace.id,'Before enrollment','history').id,stale=peerStore.createDocument(workspace.id,'Deleted while away','stale').id;for(const change of ownerStore.pendingSyncChanges(workspace.id))ownerStore.markSyncChangeRelayed(workspace.id,change.id);for(const change of peerStore.pendingSyncChanges(workspace.id))peerStore.markSyncChangeRelayed(workspace.id,change.id);const crypto=await WaypointCrypto.create(),owner=crypto.generateDevice('opaque_owner_snap_01'),peer=crypto.generateDevice('opaque_peer_snap_001'),observer=crypto.generateDevice('opaque_observer_001'),key=crypto.generateWorkspaceKey();ownerStore.configureSyncDevice(workspace.id,owner.deviceId);peerStore.configureSyncDevice(workspace.id,peer.deviceId);const devices=[{...owner,role:'owner',status:'active',enrolledAt:new Date().toISOString()},{...peer,role:'peer',status:'active',enrolledAt:new Date().toISOString()},{...observer,role:'peer',status:'active',enrolledAt:new Date().toISOString()}],queues=new Map([[owner.deviceId,[] as OpaqueRelayMessage[]],[peer.deviceId,[] as OpaqueRelayMessage[]],[observer.deviceId,[] as OpaqueRelayMessage[]]]),client=(deviceId:string)=>({listDevices:async()=>({devices}),enqueue:async(message:OpaqueRelayMessage)=>{queues.get(message.recipientDeviceId)!.push(message);return{messageId:message.messageId,acceptedAt:new Date().toISOString()}},pull:async()=>queues.get(deviceId)!.splice(0),acknowledge:async()=>true}),secrets=(device:typeof owner):ProtectedWorkspaceSecrets=>({version:1,workspaceId:workspace.id,device,workspaceKey:key,keyEpoch:1,endpoint:'https://waypoint-relay.johnnycode.ai'}),ownerPump=new DesktopSyncPump(secrets(owner),crypto,client(owner.deviceId) as never,ownerStore),peerPump=new DesktopSyncPump(secrets(peer),crypto,client(peer.deviceId) as never,peerStore);await peerPump.requestSnapshot();await ownerPump.runOnce();expect(queues.get(observer.deviceId)).toEqual([]);await peerPump.runOnce();expect(peerStore.listDocuments(workspace.id)).toEqual([expect.objectContaining({id:historical,title:'Before enrollment',body:'history'})]);expect(peerStore.listDocuments(workspace.id).some((item)=>item.id===stale)).toBe(false);ownerStore.close();peerStore.close()})
})
