import {describe,expect,it} from 'vitest'
import {WaypointCrypto} from './crypto.js'
import {DesktopRelayClient} from './desktop-relay-client.js'

describe('desktop relay transport',()=>{
  it('requires the pinned HTTPS origin and signs bounded requests without leaking private keys',async()=>{const crypto=await WaypointCrypto.create(),device=crypto.generateDevice('opaque_device_001'),calls:Array<{url:string;init:RequestInit}>=[],request=(async(url:string|URL|Request,init?:RequestInit)=>{calls.push({url:String(url),init:init!});return new Response(JSON.stringify({messages:[]}),{status:200,headers:{'content-type':'application/json'}})}) as typeof fetch;await expect(DesktopRelayClient.create({endpoint:'https://relay.example',workspaceId:'opaque_workspace_01',device,keyEpoch:1},request)).rejects.toThrow('pinned');const client=await DesktopRelayClient.create({endpoint:'https://waypoint-relay.johnnycode.ai',workspaceId:'opaque_workspace_01',device,keyEpoch:1},request);expect(await client.pull()).toEqual([]);const headers=calls[0].init.headers as Record<string,string>;expect(headers['x-waypoint-signature']).toBeTruthy();expect(JSON.stringify(calls)).not.toContain(device.signingPrivateKey)})
  it('fails closed on redirects and authority mismatch',async()=>{const crypto=await WaypointCrypto.create(),device=crypto.generateDevice('opaque_device_001'),request=(async()=>new Response('',{status:302,headers:{location:'https://evil.invalid'}})) as typeof fetch,client=await DesktopRelayClient.create({endpoint:'https://waypoint-relay.johnnycode.ai',workspaceId:'opaque_workspace_01',device,keyEpoch:1},request);await expect(client.pull()).rejects.toThrow('302');await expect(client.enqueue({protocolVersion:1,messageId:'opaque_message_001',workspaceId:'opaque_workspace_02',senderDeviceId:device.deviceId,recipientDeviceId:'opaque_device_002',keyEpoch:1,sequence:1,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+60_000).toISOString(),envelope:new Uint8Array([1])})).rejects.toThrow('authority')})
  it('rejects hostile pull payloads before returning relay data',async()=>{const crypto=await WaypointCrypto.create(),device=crypto.generateDevice('opaque_device_001'),request=(async()=>new Response(JSON.stringify({messages:[{workspaceId:'other_workspace_01'}]}),{status:200})) as typeof fetch,client=await DesktopRelayClient.create({endpoint:'https://waypoint-relay.johnnycode.ai',workspaceId:'opaque_workspace_01',device,keyEpoch:1},request);await expect(client.pull()).rejects.toThrow('authority')})
})
