import {describe,expect,it} from 'vitest'
import {WaypointCrypto} from './crypto.js'
import {DesktopSyncPump,type SyncPumpStore} from './desktop-sync-pump.js'
import type {ProtectedWorkspaceSecrets} from './protected-sync-vault.js'
import type {InboundChange,LocalMutation} from './sync-store.js'
import type {OpaqueRelayMessage} from '../../../node/relay/types.js'
import {toOpaqueRelayMessage} from './relay-adapter.js'

function memoryStore(change?:LocalMutation){let pending=change?[change]:[];const inbound:InboundChange[]=[];const store:SyncPumpStore={pendingSyncChanges:()=>pending,syncMutationRecipient:()=>undefined,recordSnapshotRequest:()=>undefined,acceptSnapshotResponse:()=>true,completeSnapshotResponse:()=>undefined,hasAppliedSyncChange:()=>false,markSyncChangeRelayed:(_workspace,id)=>{pending=pending.filter((item)=>item.id!==id)},applyInboundSyncChange:(item)=>{inbound.push(item);return'applied'},readSyncAttachment:()=>new Uint8Array(),acceptInboundAttachmentChunk:()=>true,missingInboundAttachmentChunks:()=>[],recordOutboundAttachmentMissing:()=>undefined,requestedOutboundAttachmentChunks:()=>undefined,clearOutboundAttachmentRequest:()=>undefined,acceptSnapshotRequest:()=>true,queueReplacementSnapshot:()=>0,quarantineInboundEnvelope:()=>undefined};return{store,pending:()=>pending,inbound:()=>inbound}}

describe('desktop relay sync pump',()=>{
  it('keeps outage work durable then sends, decrypts, applies, and acknowledges',async()=>{const crypto=await WaypointCrypto.create(),workspaceId='opaque_workspace_01',workspaceKey=crypto.generateWorkspaceKey(),a=crypto.generateDevice('opaque_device_a_01'),b=crypto.generateDevice('opaque_device_b_01'),change:LocalMutation={id:'opaque_change_0001',workspaceId,objectId:'opaque_chat_000001',objectKind:'chat',operation:'upsert',deviceId:a.deviceId,sequence:1,clock:{[a.deviceId]:1},payload:{title:'Offline route'},createdAt:new Date().toISOString()},left=memoryStore(change),right=memoryStore(),queue:OpaqueRelayMessage[]=[],acked:string[]=[],devices=[{...a,role:'owner',status:'active',enrolledAt:new Date().toISOString()},{...b,role:'peer',status:'active',enrolledAt:new Date().toISOString()}],secretsA:ProtectedWorkspaceSecrets={version:1,workspaceId,device:a,workspaceKey,keyEpoch:1,endpoint:'https://waypoint-relay.johnnycode.ai'},secretsB={...secretsA,device:b}
    const outage={listDevices:async()=>({devices}),enqueue:async()=>{throw new Error('offline')},pull:async()=>[],acknowledge:async()=>true};await expect(new DesktopSyncPump(secretsA,crypto,outage as never,left.store).runOnce()).rejects.toThrow('offline');expect(left.pending()).toHaveLength(1)
    const relayA={listDevices:async()=>({devices}),enqueue:async(message:OpaqueRelayMessage)=>{queue.push(message);return{messageId:message.messageId,acceptedAt:new Date().toISOString()}},pull:async()=>[],acknowledge:async()=>true};expect(await new DesktopSyncPump(secretsA,crypto,relayA as never,left.store).runOnce()).toMatchObject({sent:1,received:0,activePeers:1});expect(left.pending()).toHaveLength(0)
    const relayB={listDevices:async()=>({devices}),enqueue:async()=>{throw new Error('unexpected')},pull:async()=>queue,acknowledge:async(id:string)=>{acked.push(id);return true}};expect(await new DesktopSyncPump(secretsB,crypto,relayB as never,right.store).runOnce()).toMatchObject({sent:0,received:1,activePeers:1});expect(right.inbound()[0]).toMatchObject({id:change.id,payload:change.payload});expect(acked).toEqual([queue[0].messageId])
  })
  it('drains and decrypts an accepted previous-epoch envelope after rotation',async()=>{const crypto=await WaypointCrypto.create(),workspaceId='opaque_workspace_02',oldKey=crypto.generateWorkspaceKey(),newKey=crypto.generateWorkspaceKey(),sender=crypto.generateDevice('opaque_device_a_02'),recipient=crypto.generateDevice('opaque_device_b_02'),change:LocalMutation={id:'opaque_change_0002',workspaceId,objectId:'opaque_chat_000002',objectKind:'chat',operation:'upsert',deviceId:sender.deviceId,sequence:1,clock:{[sender.deviceId]:1},payload:{title:'Before rotation'},createdAt:new Date().toISOString()},wire={type:'mutation' as const,change},message=toOpaqueRelayMessage(crypto.encryptEnvelope({workspaceId,sender,recipient,workspaceKey:oldKey,payload:wire,keyEpoch:1,sequence:1})),target=memoryStore(),devices=[{...sender,role:'owner',status:'active',enrolledAt:new Date().toISOString()},{...recipient,role:'peer',status:'active',enrolledAt:new Date().toISOString()}],secrets:ProtectedWorkspaceSecrets={version:1,workspaceId,device:recipient,workspaceKey:newKey,keyEpoch:2,previous:{keyEpoch:1,workspaceKey:oldKey},endpoint:'https://waypoint-relay.johnnycode.ai'},acked:string[]=[];const client={listDevices:async()=>({devices}),enqueue:async()=>{throw new Error('unexpected')},pull:async()=>[message],acknowledge:async(id:string)=>{acked.push(id);return true}};expect(await new DesktopSyncPump(secrets,crypto,client as never,target.store).runOnce()).toMatchObject({received:1});expect(target.inbound()[0]).toMatchObject({id:change.id,payload:change.payload});expect(acked).toEqual([message.messageId])})
  it('rejects an authoritative prune manifest from a non-owner peer',async()=>{const crypto=await WaypointCrypto.create(),workspaceId='opaque_workspace_03',key=crypto.generateWorkspaceKey(),owner=crypto.generateDevice('opaque_owner_auth_01'),attacker=crypto.generateDevice('opaque_peer_attack1'),recipient=crypto.generateDevice('opaque_peer_target1'),change:LocalMutation={id:'opaque_snapshot_bad1',workspaceId,objectId:'opaque_request_bad01',objectKind:'snapshot',operation:'upsert',deviceId:attacker.deviceId,sequence:1,clock:{[attacker.deviceId]:1},payload:{id:'opaque_request_bad01',targetDeviceId:recipient.deviceId,liveIds:[],tombstoneIds:[]},createdAt:new Date().toISOString()},message=toOpaqueRelayMessage(crypto.encryptEnvelope({workspaceId,sender:attacker,recipient,workspaceKey:key,payload:{type:'mutation',change},keyEpoch:1,sequence:1})),target=memoryStore(),devices=[{...owner,role:'owner',status:'active',enrolledAt:new Date().toISOString()},{...attacker,role:'peer',status:'active',enrolledAt:new Date().toISOString()},{...recipient,role:'peer',status:'active',enrolledAt:new Date().toISOString()}],secrets:ProtectedWorkspaceSecrets={version:1,workspaceId,device:recipient,workspaceKey:key,keyEpoch:1,endpoint:'https://waypoint-relay.johnnycode.ai'},client={listDevices:async()=>({devices}),enqueue:async()=>{throw new Error('unexpected')},pull:async()=>[message],acknowledge:async()=>true};await expect(new DesktopSyncPump(secrets,crypto,client as never,target.store).runOnce()).rejects.toThrow('not authorized');expect(target.inbound()).toEqual([])})
})
