import { mkdtempSync } from 'node:fs'
import path from 'node:path'
import { tmpdir } from 'node:os'
import { describe, expect, it } from 'vitest'
import { SyncStateStore, type InboundChange } from './sync-store.js'

function setup(){const root=mkdtempSync(path.join(tmpdir(),'waypoint-sync-store-')),store=new SyncStateStore(path.join(root,'sync.sqlite'));store.registerDevice({id:'mac',workspaceId:'w',label:'Mac',signingPublicKey:'s',encryptionPublicKey:'e',membershipEpoch:1});store.registerDevice({id:'pc',workspaceId:'w',label:'PC',signingPublicKey:'s2',encryptionPublicKey:'e2',membershipEpoch:1});return store}
function change(input:Partial<InboundChange>&Pick<InboundChange,'id'|'deviceId'|'sequence'|'clock'|'payload'>):InboundChange{return {envelopeId:`env-${input.id}`,workspaceId:'w',objectId:'doc',objectKind:'document',operation:'upsert',createdAt:new Date().toISOString(),...input}}

describe('durable local sync state',()=>{
  it('persists consumed enrollment and peer-request nonces across restart',()=>{const store=setup(),database=store.databasePath;store.consumeEnrollment('invite');store.consumePeerRequest('run');store.close();const reopened=new SyncStateStore(database);expect(reopened.hasEnrollment('invite')).toBe(true);expect(reopened.hasPeerRequest('run')).toBe(true);expect(()=>reopened.consumeEnrollment('invite')).toThrow();reopened.close()})
  it('queues monotonic causal mutations and atomically replaces plaintext with ciphertext',()=>{const store=setup();const first=store.queueMutation({workspaceId:'w',objectId:'doc',objectKind:'document',operation:'upsert',deviceId:'mac',payload:{body:'private'}});const second=store.queueMutation({workspaceId:'w',objectId:'doc2',objectKind:'document',operation:'upsert',deviceId:'mac',payload:{body:'two'}});expect([first.sequence,second.sequence]).toEqual([1,2]);store.promoteEncrypted(first.id,'env',new Uint8Array([1,2]));expect(store.pendingMutations('w').map((m)=>m.id)).toEqual([second.id]);expect(store.outbox('w')).toHaveLength(1);store.close()})
  it('preserves concurrent authored variants and is replay safe',()=>{const store=setup();const a=change({id:'a',deviceId:'mac',sequence:1,clock:{mac:1},payload:{body:'A'}}),b=change({id:'b',deviceId:'pc',sequence:1,clock:{pc:1},payload:{body:'B'}});expect(store.applyInbound(a)).toBe('applied');expect(store.applyInbound(b)).toBe('conflict');expect(store.conflicts('w','doc').map((v)=>v.payload)).toEqual([{body:'A'},{body:'B'}]);expect(store.applyInbound(b)).toBe('replay');store.close()})
  it('resolves authored conflicts only with a change causally descending from every variant',()=>{const store=setup();store.applyInbound(change({id:'a',deviceId:'mac',sequence:1,clock:{mac:1},payload:{body:'A'}}));store.applyInbound(change({id:'b',deviceId:'pc',sequence:1,clock:{pc:1},payload:{body:'B'}}));expect(store.applyInbound(change({id:'resolved',deviceId:'mac',sequence:2,clock:{mac:2,pc:1},payload:{body:'resolved'}}))).toBe('applied');expect(store.conflicts('w','doc')).toEqual([]);expect(store.head('w','doc')?.payload).toEqual({body:'resolved'});store.close()})
  it('makes deletion dominate stale and concurrent authored updates',()=>{const store=setup();const deleted=change({id:'delete',deviceId:'mac',sequence:2,clock:{mac:2},operation:'delete',payload:{}}),stale=change({id:'stale',deviceId:'pc',sequence:4,clock:{pc:4},payload:{body:'resurrection'}});expect(store.applyInbound(deleted)).toBe('applied');expect(store.applyInbound(stale)).toBe('ignored');expect(store.head('w','doc')?.operation).toBe('delete');store.close()})
  it('requires the fixed retention and acknowledgements from every active peer before purge',()=>{const store=setup();const deleted=change({id:'delete',deviceId:'mac',sequence:2,clock:{mac:2},operation:'delete',payload:{}});store.applyInbound(deleted);store.acknowledgeTombstone('w','doc','mac');expect(store.purgeEligibleTombstones('w',new Date(Date.now()+89*86_400_000).toISOString())).toEqual([]);store.revokeDevice('w','pc',2);expect(store.purgeEligibleTombstones('w',new Date(Date.now()+91*86_400_000).toISOString())).toEqual(['doc']);store.close()})
  it('expires presence and revocation cancels authority',()=>{const store=setup();store.setPresence('w','pc',new Date(Date.now()+1000).toISOString());expect(store.listDevices('w').find((d)=>d.id==='pc')?.online).toBe(1);store.revokeDevice('w','pc',2);expect(()=>store.queueMutation({workspaceId:'w',objectId:'x',objectKind:'memory',operation:'upsert',deviceId:'pc',payload:{}})).toThrow(/Active/);expect(store.listDevices('w').find((d)=>d.id==='pc')?.online).toBe(0);store.close()})
})
