import {createHmac,randomUUID} from 'node:crypto'
import sodium from 'libsodium-wrappers-sumo'
import {canonicalWebhookRequest,type WebhookEnvelope} from './webhook-request.js'
import {webhookConnector,type WebhookConnectorId} from '../webhook-automations.js'

export interface InboundWebhookPayload{version:1|2;connectorId?:WebhookConnectorId;sourceEventId?:string;eventType:string;occurredAt:string;payload:Record<string,string|number|boolean|null>}
const MIME='application/vnd.waypoint.encrypted-event+json'
const SECRET_KEY=/authorization|cookie|password|secret|token|signature|credential/i
function validPayload(value:unknown):value is Record<string,string|number|boolean|null>{if(!value||typeof value!=='object'||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)return false;const entries=Object.entries(value as Record<string,unknown>);return entries.length<=64&&!entries.some(([key,item])=>!key||key.length>120||SECRET_KEY.test(key)||!(item===null||['string','number','boolean'].includes(typeof item))||typeof item==='string'&&item.length>2_000||typeof item==='number'&&!Number.isFinite(item))&&Buffer.byteLength(JSON.stringify(value))<=64*1024}
export async function prepareSignedWebhook(input:{channelId:string;secretVersion:number;secret:string;recipientPublicKey:string;eventType:string;payload:Record<string,string|number|boolean|null>;eventId?:string;timestamp?:string;nonce?:string}){await sodium.ready;const timestamp=input.timestamp??new Date().toISOString(),nonce=input.nonce??randomUUID(),eventId=input.eventId??randomUUID(),inner:InboundWebhookPayload={version:1,eventType:input.eventType,occurredAt:timestamp,payload:input.payload},ciphertext=sodium.crypto_box_seal(sodium.from_string(JSON.stringify(inner)),sodium.from_base64(input.recipientPublicKey,sodium.base64_variants.ORIGINAL)),envelope:WebhookEnvelope={version:1,eventId,ciphertextBase64:sodium.to_base64(ciphertext,sodium.base64_variants.ORIGINAL)},body=Buffer.from(JSON.stringify(envelope)),path=`/v1/hooks/${input.channelId}`,signature=createHmac('sha256',input.secret).update(canonicalWebhookRequest(input.channelId,input.secretVersion,path,timestamp,nonce,body)).digest('base64');return{path,body,headers:{'content-type':MIME,'x-waypoint-timestamp':timestamp,'x-waypoint-nonce':nonce,'x-waypoint-secret-version':String(input.secretVersion),'x-waypoint-signature':signature},eventId}}
export async function openInboundWebhook(ciphertextBase64:string,publicKey:string,privateKey:string):Promise<InboundWebhookPayload>{await sodium.ready;let opened:Uint8Array|null;try{opened=sodium.crypto_box_seal_open(sodium.from_base64(ciphertextBase64,sodium.base64_variants.ORIGINAL),sodium.from_base64(publicKey,sodium.base64_variants.ORIGINAL),sodium.from_base64(privateKey,sodium.base64_variants.ORIGINAL))}catch{throw new Error('Inbound webhook decryption failed')}if(!opened)throw new Error('Inbound webhook decryption failed');let value:unknown;try{value=JSON.parse(sodium.to_string(opened))}catch{throw new Error('Inbound webhook payload is invalid')}if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Inbound webhook payload is invalid');const item=value as Record<string,unknown>,payload=item.payload;if(![1,2].includes(Number(item.version))||typeof item.eventType!=='string'||!/^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/.test(item.eventType)||item.eventType.length>80||typeof item.occurredAt!=='string'||!Number.isFinite(Date.parse(item.occurredAt))||!validPayload(payload))throw new Error('Inbound webhook payload is invalid');if(item.version===2){webhookConnector(item.connectorId);if(typeof item.sourceEventId!=='string'||item.sourceEventId.length<8||item.sourceEventId.length>180)throw new Error('Inbound webhook payload is invalid')}return value as InboundWebhookPayload}
