// Generated by prepare-agent-browser-assets.ts; protected by the signed application bundle.
export const EXPECTED_AGENT_BROWSER_CLOSURE={"platform":"darwin","arch":"arm64","closureSha256":"56c1ad6f43281d1d2bf273f8b2b2388e0c8d2ac2bec91ee7bfc76a8f42b7dce9"} as const
