import {DatabaseSync} from 'node:sqlite'
import {mkdirSync,statfsSync} from 'node:fs'
import path from 'node:path'
import type {OpaqueRelayMessage,RelayAuthority,RelayReceipt} from './types.js'
import {R0_PROTOCOL_CONTRACT} from '../../electron/core/sync/protocol-contract.js'

const ID=/^[A-Za-z0-9_-]{16,128}$/
export class DurableOpaqueRelayService{
  private readonly db:DatabaseSync
  constructor(readonly databasePath:string,private readonly authority:RelayAuthority,private readonly limits:{maxEnvelopeBytes:number;maxMessages:number;maxWorkspaceBytes:number}=R0_PROTOCOL_CONTRACT.limits,private readonly minimumFreeBytes=268_435_456){mkdirSync(path.dirname(databasePath),{recursive:true});this.db=new DatabaseSync(databasePath);const version=Number((this.db.prepare('PRAGMA user_version').get() as {user_version:number}).user_version);if(version!==0&&version!==1){this.db.close();throw new Error(`Unsupported relay database schema ${version}`)}this.db.exec(`PRAGMA journal_mode=WAL;PRAGMA synchronous=FULL;CREATE TABLE IF NOT EXISTS relay_messages(message_id TEXT PRIMARY KEY,protocol_version INTEGER NOT NULL,workspace_id TEXT NOT NULL,recipient_device_id TEXT NOT NULL,sender_device_id TEXT NOT NULL,key_epoch INTEGER NOT NULL,sequence INTEGER NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,envelope BLOB NOT NULL,accepted_at TEXT NOT NULL,UNIQUE(workspace_id,sender_device_id,sequence));CREATE INDEX IF NOT EXISTS relay_delivery ON relay_messages(workspace_id,recipient_device_id,created_at);CREATE TABLE IF NOT EXISTS relay_sender_sequences(workspace_id TEXT NOT NULL,sender_device_id TEXT NOT NULL,sequence INTEGER NOT NULL,PRIMARY KEY(workspace_id,sender_device_id));PRAGMA user_version=1;`)}
  close(){this.db.close()}
  enqueue(message:OpaqueRelayMessage,now=new Date()):RelayReceipt{
    if(message.protocolVersion!==R0_PROTOCOL_CONTRACT.protocolVersion)throw new Error('Unsupported relay protocol version')
    if(![message.messageId,message.workspaceId,message.recipientDeviceId,message.senderDeviceId].every((value)=>ID.test(value)))throw new Error('Invalid opaque relay identifier')
    if(!(message.envelope instanceof Uint8Array)||!message.envelope.length||message.envelope.byteLength>this.limits.maxEnvelopeBytes)throw new Error('Invalid opaque envelope')
    const created=Date.parse(message.createdAt),expires=Date.parse(message.expiresAt);if(!Number.isFinite(created)||!Number.isFinite(expires)||new Date(created).toISOString()!==message.createdAt||new Date(expires).toISOString()!==message.expiresAt||expires<=now.getTime()||created>now.getTime()+30_000||expires<=created||expires-created>R0_PROTOCOL_CONTRACT.retention.relayEnvelopeMaximumDays*86_400_000)throw new Error('Invalid envelope lifetime')
    this.purgeExpired(now)
    if(!this.authority.isActive(message.workspaceId,message.senderDeviceId,message.keyEpoch)||!this.authority.isActive(message.workspaceId,message.recipientDeviceId,message.keyEpoch)||!this.authority.verifySignature(message))throw new Error('Relay authority rejected envelope')
    const acceptedAt=now.toISOString();this.db.exec('BEGIN IMMEDIATE');try{const prior=this.db.prepare('SELECT * FROM relay_messages WHERE message_id=?').get(message.messageId) as Record<string,unknown>|undefined;if(prior){const same=Number(prior.protocol_version)===message.protocolVersion&&String(prior.workspace_id)===message.workspaceId&&String(prior.recipient_device_id)===message.recipientDeviceId&&String(prior.sender_device_id)===message.senderDeviceId&&Number(prior.key_epoch)===message.keyEpoch&&Number(prior.sequence)===message.sequence&&String(prior.created_at)===message.createdAt&&String(prior.expires_at)===message.expiresAt&&Buffer.from(prior.envelope as Uint8Array).equals(Buffer.from(message.envelope));if(!same)throw new Error('Message identifier collision');this.db.exec('COMMIT');return{messageId:message.messageId,acceptedAt:String(prior.accepted_at)}}if(this.availableBytes()<this.minimumFreeBytes+message.envelope.byteLength)throw new Error('Relay storage reserve reached');const priorSequence=Number((this.db.prepare('SELECT coalesce(sequence,0) sequence FROM relay_sender_sequences WHERE workspace_id=? AND sender_device_id=?').get(message.workspaceId,message.senderDeviceId) as {sequence:number}|undefined)?.sequence??0);if(!Number.isSafeInteger(message.sequence)||message.sequence<=priorSequence)throw new Error('Sender sequence replay or rollback');const count=Number((this.db.prepare('SELECT count(*) count FROM relay_messages').get() as {count:number}).count),bytes=Number((this.db.prepare('SELECT coalesce(sum(length(envelope)),0) bytes FROM relay_messages WHERE workspace_id=?').get(message.workspaceId) as {bytes:number}).bytes);if(count>=this.limits.maxMessages||bytes+message.envelope.byteLength>this.limits.maxWorkspaceBytes)throw new Error('Relay quota exceeded');this.db.prepare('INSERT INTO relay_messages VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(message.messageId,message.protocolVersion,message.workspaceId,message.recipientDeviceId,message.senderDeviceId,message.keyEpoch,message.sequence,message.createdAt,message.expiresAt,Buffer.from(message.envelope),acceptedAt);this.db.prepare('INSERT INTO relay_sender_sequences VALUES (?,?,?) ON CONFLICT(workspace_id,sender_device_id) DO UPDATE SET sequence=excluded.sequence').run(message.workspaceId,message.senderDeviceId,message.sequence);this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error};return{messageId:message.messageId,acceptedAt}
  }
  pull(workspaceId:string,recipientDeviceId:string,authenticatedDeviceId:string,now=new Date(),limit=100):OpaqueRelayMessage[]{this.purgeExpired(now);if(recipientDeviceId!==authenticatedDeviceId||!ID.test(workspaceId)||!ID.test(recipientDeviceId))return[];return(this.db.prepare('SELECT * FROM relay_messages WHERE workspace_id=? AND recipient_device_id=? ORDER BY created_at LIMIT ?').all(workspaceId,recipientDeviceId,Math.max(0,Math.min(limit,1000))) as Array<Record<string,unknown>>).filter((row)=>this.authority.isActive(workspaceId,authenticatedDeviceId,Number(row.key_epoch))&&this.authority.isActive(workspaceId,String(row.sender_device_id),Number(row.key_epoch))).map((row)=>({protocolVersion:Number(row.protocol_version),messageId:String(row.message_id),workspaceId:String(row.workspace_id),recipientDeviceId:String(row.recipient_device_id),senderDeviceId:String(row.sender_device_id),keyEpoch:Number(row.key_epoch),sequence:Number(row.sequence),createdAt:String(row.created_at),expiresAt:String(row.expires_at),envelope:new Uint8Array(row.envelope as Uint8Array)}))}
  acknowledge(workspaceId:string,recipientDeviceId:string,authenticatedDeviceId:string,messageId:string):boolean{if(recipientDeviceId!==authenticatedDeviceId||![workspaceId,recipientDeviceId,messageId].every((value)=>ID.test(value)))return false;const row=this.db.prepare('SELECT key_epoch FROM relay_messages WHERE workspace_id=? AND recipient_device_id=? AND message_id=?').get(workspaceId,recipientDeviceId,messageId) as {key_epoch:number}|undefined;if(!row||!this.authority.isActive(workspaceId,authenticatedDeviceId,row.key_epoch))return false;return Boolean(this.db.prepare('DELETE FROM relay_messages WHERE message_id=?').run(messageId).changes)}
  purgeExpired(now=new Date()):number{return Number(this.db.prepare('DELETE FROM relay_messages WHERE expires_at<=?').run(now.toISOString()).changes)}
  private availableBytes(){const stats=statfsSync(path.dirname(this.databasePath));return Number(stats.bavail)*Number(stats.bsize)}
  health(){const integrity=String((this.db.prepare('PRAGMA quick_check').get() as {'quick_check':string})['quick_check']),row=this.db.prepare('SELECT count(*) messages,coalesce(sum(length(envelope)),0) bytes FROM relay_messages').get() as {messages:number;bytes:number},availableBytes=this.availableBytes();return{status:integrity==='ok'&&availableBytes>=this.minimumFreeBytes?'ok' as const:'degraded' as const,protocolVersion:R0_PROTOCOL_CONTRACT.protocolVersion,queuedMessages:Number(row.messages),queuedBytes:Number(row.bytes),availableBytes}}
}
