import {createCipheriv,createDecipheriv,createHash,createHmac,randomBytes,timingSafeEqual} from 'node:crypto'
import {DatabaseSync} from 'node:sqlite'
import sodium from 'libsodium-wrappers-sumo'
import {canonicalWebhookRequest,type WebhookEnvelope} from '../../electron/core/sync/webhook-request.js'
import {defaultWebhookAuth,normalizeNativeWebhook,webhookConnector,type WebhookAuthMode,type WebhookConnectorId} from '../../electron/core/webhook-automations.js'

const ID=/^[A-Za-z0-9_-]{16,128}$/
const MIME='application/vnd.waypoint.encrypted-event+json'
export const WEBHOOK_LIMITS={maxBodyBytes:262_144,maxChannelsPerWorkspace:50,maxQueuedPerWorkspace:500,maxQueuedBytesPerWorkspace:32*1024*1024,retentionMs:7*86_400_000,replayWindowMs:60_000,maxRequestsPerMinute:60} as const
export interface WebhookChannelView{channelId:string;workspaceId:string;recipientDeviceId:string;recipientPublicKey:string;label:string;connectorId:WebhookConnectorId;authMode:WebhookAuthMode;secretVersion:number;status:'active'|'revoked';createdAt:string;rotatedAt:string;revokedAt?:string}
const digest=(body:Uint8Array)=>createHash('sha256').update(body).digest('hex')
const encoded=(value:string,length:number)=>{try{const bytes=Buffer.from(value,'base64');return bytes.length===length&&bytes.toString('base64')===value}catch{return false}}

export class WebhookRelayService{
  private readonly db:DatabaseSync
  constructor(databasePath:string,private readonly key:Buffer){if(key.length!==32)throw new Error('Webhook protection key must be 32 bytes');this.db=new DatabaseSync(databasePath);this.db.exec(`CREATE TABLE IF NOT EXISTS webhook_channels(channel_id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,recipient_device_id TEXT NOT NULL,recipient_public_key TEXT NOT NULL,label TEXT NOT NULL,secret_version INTEGER NOT NULL,secret_ciphertext BLOB NOT NULL,status TEXT NOT NULL CHECK(status IN ('active','revoked')),created_at TEXT NOT NULL,rotated_at TEXT NOT NULL,revoked_at TEXT);CREATE INDEX IF NOT EXISTS webhook_channels_workspace ON webhook_channels(workspace_id,created_at);CREATE TABLE IF NOT EXISTS webhook_nonces(channel_id TEXT NOT NULL,nonce TEXT NOT NULL,expires_at INTEGER NOT NULL,PRIMARY KEY(channel_id,nonce));CREATE TABLE IF NOT EXISTS webhook_replays(channel_id TEXT NOT NULL REFERENCES webhook_channels(channel_id) ON DELETE CASCADE,source_event_id TEXT NOT NULL,body_digest TEXT NOT NULL,expires_at INTEGER NOT NULL,PRIMARY KEY(channel_id,source_event_id));CREATE INDEX IF NOT EXISTS webhook_replay_expiry ON webhook_replays(expires_at);CREATE TABLE IF NOT EXISTS webhook_events(event_id TEXT PRIMARY KEY,channel_id TEXT NOT NULL REFERENCES webhook_channels(channel_id) ON DELETE CASCADE,workspace_id TEXT NOT NULL,recipient_device_id TEXT NOT NULL,secret_version INTEGER NOT NULL,received_at TEXT NOT NULL,expires_at TEXT NOT NULL,ciphertext BLOB NOT NULL,body_digest TEXT NOT NULL,UNIQUE(channel_id,body_digest));CREATE INDEX IF NOT EXISTS webhook_delivery ON webhook_events(workspace_id,recipient_device_id,received_at);CREATE TABLE IF NOT EXISTS webhook_workspace_settings(workspace_id TEXT PRIMARY KEY,kill_switch INTEGER NOT NULL CHECK(kill_switch IN (0,1)),updated_at TEXT NOT NULL);`);const columns=this.db.prepare('PRAGMA table_info(webhook_channels)').all() as Array<{name:string}>;if(!columns.some((item)=>item.name==='connector_id'))this.db.exec("ALTER TABLE webhook_channels ADD COLUMN connector_id TEXT NOT NULL DEFAULT 'generic'");if(!columns.some((item)=>item.name==='auth_mode'))this.db.exec("ALTER TABLE webhook_channels ADD COLUMN auth_mode TEXT NOT NULL DEFAULT 'waypoint_hmac'")}
  close(){this.db.close()}
  create(workspaceId:string,recipientDeviceId:string,recipientPublicKey:string,label:string,connectorValue:unknown='generic',at=new Date(),requestedChannelId?:string){const connectorId=webhookConnector(connectorValue),authMode=defaultWebhookAuth(connectorId),channelId=requestedChannelId??randomBytes(24).toString('base64url');if(!ID.test(workspaceId)||!ID.test(recipientDeviceId)||!ID.test(channelId)||!encoded(recipientPublicKey,32)||!label.trim()||label.length>80)throw new Error('Invalid webhook channel');if(Number((this.db.prepare('SELECT count(*) count FROM webhook_channels WHERE workspace_id=?').get(workspaceId) as {count:number}).count)>=WEBHOOK_LIMITS.maxChannelsPerWorkspace)throw new Error('quota');const secret=randomBytes(32).toString('base64url'),timestamp=at.toISOString();this.db.prepare("INSERT INTO webhook_channels(channel_id,workspace_id,recipient_device_id,recipient_public_key,label,secret_version,secret_ciphertext,status,created_at,rotated_at,revoked_at,connector_id,auth_mode) VALUES (?,?,?,?,?,1,?,'active',?,?,NULL,?,?)").run(channelId,workspaceId,recipientDeviceId,recipientPublicKey,label.trim(),this.protect(secret,channelId,1),timestamp,timestamp,connectorId,authMode);return{...this.view(channelId)!,secret}}
  list(workspaceId:string):WebhookChannelView[]{return(this.db.prepare('SELECT * FROM webhook_channels WHERE workspace_id=? ORDER BY created_at DESC').all(workspaceId) as Array<Record<string,unknown>>).map(view)}
  rotate(workspaceId:string,channelId:string,at=new Date()){const row=this.row(workspaceId,channelId);if(!row||row.status!=='active')throw new Error('Active webhook channel not found');const secret=randomBytes(32).toString('base64url'),version=Number(row.secret_version)+1,timestamp=at.toISOString();this.db.prepare('UPDATE webhook_channels SET secret_version=?,secret_ciphertext=?,rotated_at=? WHERE workspace_id=? AND channel_id=?').run(version,this.protect(secret,channelId,version),timestamp,workspaceId,channelId);this.db.prepare('DELETE FROM webhook_nonces WHERE channel_id=?').run(channelId);return{...this.view(channelId)!,secret}}
  revoke(workspaceId:string,channelId:string,at=new Date()){const result=this.db.prepare("UPDATE webhook_channels SET status='revoked',revoked_at=? WHERE workspace_id=? AND channel_id=? AND status='active'").run(at.toISOString(),workspaceId,channelId);if(result.changes!==1)throw new Error('Active webhook channel not found');return this.view(channelId)!}
  setKill(workspaceId:string,active:boolean,at=new Date()){this.db.prepare('INSERT INTO webhook_workspace_settings VALUES (?,?,?) ON CONFLICT(workspace_id) DO UPDATE SET kill_switch=excluded.kill_switch,updated_at=excluded.updated_at').run(workspaceId,active?1:0,at.toISOString());return{active}}
  killed(workspaceId:string){return Boolean((this.db.prepare('SELECT kill_switch active FROM webhook_workspace_settings WHERE workspace_id=?').get(workspaceId) as {active:number}|undefined)?.active)}
  accept(channelId:string,headers:{timestamp:string;nonce:string;signature:string;secretVersion:number;mime:string},body:Buffer,at=new Date()){
    const row=this.db.prepare('SELECT * FROM webhook_channels WHERE channel_id=?').get(channelId) as Record<string,unknown>|undefined;if(!row||row.status!=='active'||this.killed(String(row.workspace_id)))throw new Error('unauthorized')
    if(headers.mime!==MIME||body.length<2||body.length>WEBHOOK_LIMITS.maxBodyBytes||!ID.test(headers.nonce)||headers.secretVersion!==Number(row.secret_version))throw new Error('invalid_request')
    const requestTime=Date.parse(headers.timestamp);if(!Number.isFinite(requestTime)||Math.abs(at.getTime()-requestTime)>WEBHOOK_LIMITS.replayWindowMs)throw new Error('unauthorized')
    const expected=createHmac('sha256',this.unprotect(row.secret_ciphertext as Uint8Array,channelId,headers.secretVersion)).update(canonicalWebhookRequest(channelId,headers.secretVersion,`/v1/hooks/${channelId}`,headers.timestamp,headers.nonce,body)).digest(),provided=Buffer.from(headers.signature,'base64');if(provided.length!==expected.length||!timingSafeEqual(provided,expected))throw new Error('unauthorized')
    let envelope:WebhookEnvelope;try{envelope=JSON.parse(body.toString('utf8')) as WebhookEnvelope}catch{throw new Error('invalid_request')}if(envelope.version!==1||!ID.test(envelope.eventId)||typeof envelope.ciphertextBase64!=='string'||envelope.ciphertextBase64.length>WEBHOOK_LIMITS.maxBodyBytes||!encoded(envelope.ciphertextBase64,Buffer.from(envelope.ciphertextBase64,'base64').length))throw new Error('invalid_request');const ciphertext=Buffer.from(envelope.ciphertextBase64,'base64');if(ciphertext.length<49||ciphertext.length>WEBHOOK_LIMITS.maxBodyBytes)throw new Error('invalid_request')
    this.enqueue(row,envelope.eventId,ciphertext,digest(body),at,headers.nonce);return{eventId:envelope.eventId,acceptedAt:at.toISOString()}
  }
  async acceptNative(channelId:string,headers:Record<string,string|undefined>,body:Buffer,at=new Date()){
    const row=this.db.prepare('SELECT * FROM webhook_channels WHERE channel_id=?').get(channelId) as Record<string,unknown>|undefined;if(!row||row.status!=='active'||this.killed(String(row.workspace_id)))throw new Error('unauthorized');const connectorId=webhookConnector(row.connector_id),authMode=String(row.auth_mode) as WebhookAuthMode;if(connectorId==='generic'&&authMode==='waypoint_hmac')throw new Error('invalid_request');const secret=this.unprotect(row.secret_ciphertext as Uint8Array,channelId,Number(row.secret_version));this.authenticateNative(authMode,secret,headers,body,at);const normalized=normalizeNativeWebhook({connectorId,headers,body,receivedAt:at});await sodium.ready;const inner={...normalized,version:2 as const},ciphertext=Buffer.from(sodium.crypto_box_seal(sodium.from_string(JSON.stringify(inner)),sodium.from_base64(String(row.recipient_public_key),sodium.base64_variants.ORIGINAL))),eventId=createHash('sha256').update(`${channelId}:${normalized.sourceEventId}`).digest('base64url');this.enqueue(row,eventId,ciphertext,digest(body),at);return{eventId,acceptedAt:at.toISOString()}
  }
  pull(workspaceId:string,deviceId:string,limit:number,at=new Date()){this.purge(at);return(this.db.prepare('SELECT event_id eventId,channel_id channelId,secret_version secretVersion,received_at receivedAt,expires_at expiresAt,ciphertext FROM webhook_events WHERE workspace_id=? AND recipient_device_id=? ORDER BY received_at LIMIT ?').all(workspaceId,deviceId,Math.max(0,Math.min(100,limit))) as Array<Record<string,unknown>>).map((row)=>({...row,ciphertextBase64:Buffer.from(row.ciphertext as Uint8Array).toString('base64'),ciphertext:undefined}))}
  acknowledge(workspaceId:string,deviceId:string,eventId:string){return Boolean(this.db.prepare('DELETE FROM webhook_events WHERE workspace_id=? AND recipient_device_id=? AND event_id=?').run(workspaceId,deviceId,eventId).changes)}
  deleteChannel(workspaceId:string,channelId:string){this.db.exec('BEGIN IMMEDIATE');try{if(!this.row(workspaceId,channelId)){this.db.exec('ROLLBACK');return false}this.db.prepare('DELETE FROM webhook_events WHERE channel_id=?').run(channelId);this.db.prepare('DELETE FROM webhook_replays WHERE channel_id=?').run(channelId);this.db.prepare('DELETE FROM webhook_nonces WHERE channel_id=?').run(channelId);const deleted=this.db.prepare('DELETE FROM webhook_channels WHERE workspace_id=? AND channel_id=?').run(workspaceId,channelId).changes;this.db.exec('COMMIT');return Boolean(deleted)}catch(error){this.db.exec('ROLLBACK');throw error}}
  stats(){this.purge(new Date());const row=this.db.prepare('SELECT count(*) events,coalesce(sum(length(ciphertext)),0) bytes FROM webhook_events').get() as {events:number;bytes:number};return{queuedWebhookEvents:Number(row.events),queuedWebhookBytes:Number(row.bytes)}}
  private purge(at:Date){const events=this.db.prepare('DELETE FROM webhook_events WHERE expires_at<=?').run(at.toISOString()).changes;this.db.prepare('DELETE FROM webhook_replays WHERE expires_at<=?').run(at.getTime());return events}
  private row(workspaceId:string,channelId:string){return this.db.prepare('SELECT * FROM webhook_channels WHERE workspace_id=? AND channel_id=?').get(workspaceId,channelId) as Record<string,unknown>|undefined}
  private view(channelId:string){const row=this.db.prepare('SELECT * FROM webhook_channels WHERE channel_id=?').get(channelId) as Record<string,unknown>|undefined;return row?view(row):undefined}
  private protect(secret:string,channelId:string,version:number){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',this.key,iv);cipher.setAAD(Buffer.from(JSON.stringify([1,channelId,version])));const body=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body])}
  private unprotect(value:Uint8Array,channelId:string,version:number){const bytes=Buffer.from(value);if(bytes.length<29)throw new Error('invalid protected secret');const decipher=createDecipheriv('aes-256-gcm',this.key,bytes.subarray(0,12));decipher.setAAD(Buffer.from(JSON.stringify([1,channelId,version])));decipher.setAuthTag(bytes.subarray(12,28));return Buffer.concat([decipher.update(bytes.subarray(28)),decipher.final()])}
  private enqueue(row:Record<string,unknown>,eventId:string,ciphertext:Buffer,bodyDigest:string,at:Date,nonce?:string){this.purge(at);this.db.exec('BEGIN IMMEDIATE');try{const channelId=String(row.channel_id);if(this.db.prepare('SELECT 1 FROM webhook_replays WHERE channel_id=? AND source_event_id=?').get(channelId,eventId))throw new Error('replay');if(nonce){this.db.prepare('DELETE FROM webhook_nonces WHERE expires_at<=?').run(at.getTime());if(this.db.prepare('SELECT 1 FROM webhook_nonces WHERE channel_id=? AND nonce=?').get(channelId,nonce))throw new Error('replay');this.db.prepare('INSERT INTO webhook_nonces VALUES (?,?,?)').run(channelId,nonce,at.getTime()+2*WEBHOOK_LIMITS.replayWindowMs)}const workspaceId=String(row.workspace_id),queued=this.db.prepare('SELECT count(*) count,coalesce(sum(length(ciphertext)),0) bytes FROM webhook_events WHERE workspace_id=?').get(workspaceId) as {count:number;bytes:number};if(queued.count>=WEBHOOK_LIMITS.maxQueuedPerWorkspace||queued.bytes+ciphertext.length>WEBHOOK_LIMITS.maxQueuedBytesPerWorkspace)throw new Error('quota');this.db.prepare('INSERT INTO webhook_replays VALUES (?,?,?,?)').run(channelId,eventId,bodyDigest,at.getTime()+WEBHOOK_LIMITS.retentionMs);this.db.prepare('INSERT INTO webhook_events VALUES (?,?,?,?,?,?,?,?,?)').run(eventId,channelId,workspaceId,String(row.recipient_device_id),Number(row.secret_version),at.toISOString(),new Date(at.getTime()+WEBHOOK_LIMITS.retentionMs).toISOString(),ciphertext,bodyDigest);this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');if(error instanceof Error&&/UNIQUE constraint/.test(error.message))throw new Error('replay',{cause:error});throw error}}
  private authenticateNative(mode:WebhookAuthMode,secret:Buffer,headers:Record<string,string|undefined>,body:Buffer,at:Date){let expected:Buffer,provided:Buffer;if(mode==='basic'){const raw=headers.authorization??'';if(!raw.startsWith('Basic '))throw new Error('unauthorized');const decoded=Buffer.from(raw.slice(6),'base64').toString('utf8'),split=decoded.indexOf(':');provided=Buffer.from(split>=0?decoded.slice(split+1):'')}else if(mode==='github_hmac'){expected=Buffer.from(`sha256=${createHmac('sha256',secret).update(body).digest('hex')}`);provided=Buffer.from(headers['x-hub-signature-256']??'');return secure(expected,provided)}else if(mode==='stripe_hmac'){const signature=headers['stripe-signature']??'',time=/t=(\d+)/.exec(signature)?.[1],values=[...signature.matchAll(/v1=([a-f0-9]+)/g)].map((match)=>match[1]);if(!time||Math.abs(at.getTime()-Number(time)*1000)>300_000)throw new Error('unauthorized');expected=Buffer.from(createHmac('sha256',secret).update(`${time}.${body.toString('utf8')}`).digest('hex'));if(!values.some((value)=>secure(expected,Buffer.from(value),false)))throw new Error('unauthorized');return}else if(mode==='svix_hmac'){const id=headers['svix-id']??'',time=headers['svix-timestamp']??'',timestamp=Number(time);if(!id||!Number.isFinite(timestamp)||Math.abs(at.getTime()-timestamp*1000)>300_000)throw new Error('unauthorized');const keyText=secret.toString('utf8').replace(/^whsec_/,'');let key:Buffer;try{key=Buffer.from(keyText,'base64')}catch{throw new Error('unauthorized')}expected=createHmac('sha256',key).update(`${id}.${time}.${body.toString('utf8')}`).digest();const values=(headers['svix-signature']??'').split(' ').map((item)=>item.replace(/^v1,/,''));if(!values.some((value)=>secure(expected,Buffer.from(value,'base64'),false)))throw new Error('unauthorized');return}else{const auth=headers.authorization??'',candidate=auth.startsWith('Bearer ')?auth.slice(7):headers['x-waypoint-webhook-secret']??'';provided=Buffer.from(candidate)}expected=secret;secure(expected,provided)}
}
const secure=(expected:Buffer,provided:Buffer,throwOnFailure=true)=>{const valid=provided.length===expected.length&&timingSafeEqual(provided,expected);if(!valid&&throwOnFailure)throw new Error('unauthorized');return valid}
const view=(row:Record<string,unknown>):WebhookChannelView=>({channelId:String(row.channel_id),workspaceId:String(row.workspace_id),recipientDeviceId:String(row.recipient_device_id),recipientPublicKey:String(row.recipient_public_key),label:String(row.label),connectorId:webhookConnector(row.connector_id),authMode:String(row.auth_mode) as WebhookAuthMode,secretVersion:Number(row.secret_version),status:String(row.status) as 'active'|'revoked',createdAt:String(row.created_at),rotatedAt:String(row.rotated_at),revokedAt:row.revoked_at?String(row.revoked_at):undefined})
