import {createCipheriv,createDecipheriv,createHash,createHmac,randomBytes,timingSafeEqual} from 'node:crypto'
import {DatabaseSync} from 'node:sqlite'
import {canonicalWebhookRequest,type WebhookEnvelope} from '../../electron/core/sync/webhook-request.js'

const ID=/^[A-Za-z0-9_-]{16,128}$/
const MIME='application/vnd.waypoint.encrypted-event+json'
export const WEBHOOK_LIMITS={maxBodyBytes:262_144,maxChannelsPerWorkspace:50,maxQueuedPerWorkspace:500,maxQueuedBytesPerWorkspace:32*1024*1024,retentionMs:7*86_400_000,replayWindowMs:60_000,maxRequestsPerMinute:60} as const
export interface WebhookChannelView{channelId:string;workspaceId:string;recipientDeviceId:string;recipientPublicKey:string;label:string;secretVersion:number;status:'active'|'revoked';createdAt:string;rotatedAt:string;revokedAt?:string}
const digest=(body:Uint8Array)=>createHash('sha256').update(body).digest('hex')
const encoded=(value:string,length:number)=>{try{const bytes=Buffer.from(value,'base64');return bytes.length===length&&bytes.toString('base64')===value}catch{return false}}

export class WebhookRelayService{
  private readonly db:DatabaseSync
  constructor(databasePath:string,private readonly key:Buffer){if(key.length!==32)throw new Error('Webhook protection key must be 32 bytes');this.db=new DatabaseSync(databasePath);this.db.exec(`CREATE TABLE IF NOT EXISTS webhook_channels(channel_id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,recipient_device_id TEXT NOT NULL,recipient_public_key TEXT NOT NULL,label TEXT NOT NULL,secret_version INTEGER NOT NULL,secret_ciphertext BLOB NOT NULL,status TEXT NOT NULL CHECK(status IN ('active','revoked')),created_at TEXT NOT NULL,rotated_at TEXT NOT NULL,revoked_at TEXT);CREATE INDEX IF NOT EXISTS webhook_channels_workspace ON webhook_channels(workspace_id,created_at);CREATE TABLE IF NOT EXISTS webhook_nonces(channel_id TEXT NOT NULL,nonce TEXT NOT NULL,expires_at INTEGER NOT NULL,PRIMARY KEY(channel_id,nonce));CREATE TABLE IF NOT EXISTS webhook_events(event_id TEXT PRIMARY KEY,channel_id TEXT NOT NULL REFERENCES webhook_channels(channel_id) ON DELETE CASCADE,workspace_id TEXT NOT NULL,recipient_device_id TEXT NOT NULL,secret_version INTEGER NOT NULL,received_at TEXT NOT NULL,expires_at TEXT NOT NULL,ciphertext BLOB NOT NULL,body_digest TEXT NOT NULL,UNIQUE(channel_id,body_digest));CREATE INDEX IF NOT EXISTS webhook_delivery ON webhook_events(workspace_id,recipient_device_id,received_at);CREATE TABLE IF NOT EXISTS webhook_workspace_settings(workspace_id TEXT PRIMARY KEY,kill_switch INTEGER NOT NULL CHECK(kill_switch IN (0,1)),updated_at TEXT NOT NULL);`)}
  close(){this.db.close()}
  create(workspaceId:string,recipientDeviceId:string,recipientPublicKey:string,label:string,at=new Date()){if(!ID.test(workspaceId)||!ID.test(recipientDeviceId)||!encoded(recipientPublicKey,32)||!label.trim()||label.length>80)throw new Error('Invalid webhook channel');if(Number((this.db.prepare('SELECT count(*) count FROM webhook_channels WHERE workspace_id=?').get(workspaceId) as {count:number}).count)>=WEBHOOK_LIMITS.maxChannelsPerWorkspace)throw new Error('quota');const channelId=randomBytes(24).toString('base64url'),secret=randomBytes(32).toString('base64url'),timestamp=at.toISOString();this.db.prepare("INSERT INTO webhook_channels VALUES (?,?,?,?,?,1,?,'active',?,?,NULL)").run(channelId,workspaceId,recipientDeviceId,recipientPublicKey,label.trim(),this.protect(secret,channelId,1),timestamp,timestamp);return{...this.view(channelId)!,secret}}
  list(workspaceId:string):WebhookChannelView[]{return(this.db.prepare('SELECT * FROM webhook_channels WHERE workspace_id=? ORDER BY created_at DESC').all(workspaceId) as Array<Record<string,unknown>>).map(view)}
  rotate(workspaceId:string,channelId:string,at=new Date()){const row=this.row(workspaceId,channelId);if(!row||row.status!=='active')throw new Error('Active webhook channel not found');const secret=randomBytes(32).toString('base64url'),version=Number(row.secret_version)+1,timestamp=at.toISOString();this.db.prepare('UPDATE webhook_channels SET secret_version=?,secret_ciphertext=?,rotated_at=? WHERE workspace_id=? AND channel_id=?').run(version,this.protect(secret,channelId,version),timestamp,workspaceId,channelId);this.db.prepare('DELETE FROM webhook_nonces WHERE channel_id=?').run(channelId);return{...this.view(channelId)!,secret}}
  revoke(workspaceId:string,channelId:string,at=new Date()){const result=this.db.prepare("UPDATE webhook_channels SET status='revoked',revoked_at=? WHERE workspace_id=? AND channel_id=? AND status='active'").run(at.toISOString(),workspaceId,channelId);if(result.changes!==1)throw new Error('Active webhook channel not found');return this.view(channelId)!}
  setKill(workspaceId:string,active:boolean,at=new Date()){this.db.prepare('INSERT INTO webhook_workspace_settings VALUES (?,?,?) ON CONFLICT(workspace_id) DO UPDATE SET kill_switch=excluded.kill_switch,updated_at=excluded.updated_at').run(workspaceId,active?1:0,at.toISOString());return{active}}
  killed(workspaceId:string){return Boolean((this.db.prepare('SELECT kill_switch active FROM webhook_workspace_settings WHERE workspace_id=?').get(workspaceId) as {active:number}|undefined)?.active)}
  accept(channelId:string,headers:{timestamp:string;nonce:string;signature:string;secretVersion:number;mime:string},body:Buffer,at=new Date()){
    const row=this.db.prepare('SELECT * FROM webhook_channels WHERE channel_id=?').get(channelId) as Record<string,unknown>|undefined;if(!row||row.status!=='active'||this.killed(String(row.workspace_id)))throw new Error('unauthorized')
    if(headers.mime!==MIME||body.length<2||body.length>WEBHOOK_LIMITS.maxBodyBytes||!ID.test(headers.nonce)||headers.secretVersion!==Number(row.secret_version))throw new Error('invalid_request')
    const requestTime=Date.parse(headers.timestamp);if(!Number.isFinite(requestTime)||Math.abs(at.getTime()-requestTime)>WEBHOOK_LIMITS.replayWindowMs)throw new Error('unauthorized')
    const expected=createHmac('sha256',this.unprotect(row.secret_ciphertext as Uint8Array,channelId,headers.secretVersion)).update(canonicalWebhookRequest(channelId,headers.secretVersion,`/v1/hooks/${channelId}`,headers.timestamp,headers.nonce,body)).digest(),provided=Buffer.from(headers.signature,'base64');if(provided.length!==expected.length||!timingSafeEqual(provided,expected))throw new Error('unauthorized')
    let envelope:WebhookEnvelope;try{envelope=JSON.parse(body.toString('utf8')) as WebhookEnvelope}catch{throw new Error('invalid_request')}if(envelope.version!==1||!ID.test(envelope.eventId)||typeof envelope.ciphertextBase64!=='string'||envelope.ciphertextBase64.length>WEBHOOK_LIMITS.maxBodyBytes||!encoded(envelope.ciphertextBase64,Buffer.from(envelope.ciphertextBase64,'base64').length))throw new Error('invalid_request');const ciphertext=Buffer.from(envelope.ciphertextBase64,'base64');if(ciphertext.length<49||ciphertext.length>WEBHOOK_LIMITS.maxBodyBytes)throw new Error('invalid_request')
    this.purge(at);this.db.exec('BEGIN IMMEDIATE');try{this.db.prepare('DELETE FROM webhook_nonces WHERE expires_at<=?').run(at.getTime());if(this.db.prepare('SELECT 1 FROM webhook_nonces WHERE channel_id=? AND nonce=?').get(channelId,headers.nonce))throw new Error('replay');const workspaceId=String(row.workspace_id),recipientDeviceId=String(row.recipient_device_id),secretVersion=Number(row.secret_version),queued=this.db.prepare('SELECT count(*) count,coalesce(sum(length(ciphertext)),0) bytes FROM webhook_events WHERE workspace_id=?').get(workspaceId) as {count:number;bytes:number};if(queued.count>=WEBHOOK_LIMITS.maxQueuedPerWorkspace||queued.bytes+ciphertext.length>WEBHOOK_LIMITS.maxQueuedBytesPerWorkspace)throw new Error('quota');this.db.prepare('INSERT INTO webhook_nonces VALUES (?,?,?)').run(channelId,headers.nonce,at.getTime()+2*WEBHOOK_LIMITS.replayWindowMs);this.db.prepare('INSERT INTO webhook_events VALUES (?,?,?,?,?,?,?,?,?)').run(envelope.eventId,channelId,workspaceId,recipientDeviceId,secretVersion,at.toISOString(),new Date(at.getTime()+WEBHOOK_LIMITS.retentionMs).toISOString(),ciphertext,digest(body));this.db.exec('COMMIT')}catch(error){this.db.exec('ROLLBACK');throw error}return{eventId:envelope.eventId,acceptedAt:at.toISOString()}
  }
  pull(workspaceId:string,deviceId:string,limit:number,at=new Date()){this.purge(at);return(this.db.prepare('SELECT event_id eventId,channel_id channelId,secret_version secretVersion,received_at receivedAt,expires_at expiresAt,ciphertext FROM webhook_events WHERE workspace_id=? AND recipient_device_id=? ORDER BY received_at LIMIT ?').all(workspaceId,deviceId,Math.max(0,Math.min(100,limit))) as Array<Record<string,unknown>>).map((row)=>({...row,ciphertextBase64:Buffer.from(row.ciphertext as Uint8Array).toString('base64'),ciphertext:undefined}))}
  acknowledge(workspaceId:string,deviceId:string,eventId:string){return Boolean(this.db.prepare('DELETE FROM webhook_events WHERE workspace_id=? AND recipient_device_id=? AND event_id=?').run(workspaceId,deviceId,eventId).changes)}
  deleteChannel(workspaceId:string,channelId:string){return Boolean(this.db.prepare('DELETE FROM webhook_channels WHERE workspace_id=? AND channel_id=?').run(workspaceId,channelId).changes)}
  stats(){this.purge(new Date());const row=this.db.prepare('SELECT count(*) events,coalesce(sum(length(ciphertext)),0) bytes FROM webhook_events').get() as {events:number;bytes:number};return{queuedWebhookEvents:Number(row.events),queuedWebhookBytes:Number(row.bytes)}}
  private purge(at:Date){return this.db.prepare('DELETE FROM webhook_events WHERE expires_at<=?').run(at.toISOString()).changes}
  private row(workspaceId:string,channelId:string){return this.db.prepare('SELECT * FROM webhook_channels WHERE workspace_id=? AND channel_id=?').get(workspaceId,channelId) as Record<string,unknown>|undefined}
  private view(channelId:string){const row=this.db.prepare('SELECT * FROM webhook_channels WHERE channel_id=?').get(channelId) as Record<string,unknown>|undefined;return row?view(row):undefined}
  private protect(secret:string,channelId:string,version:number){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',this.key,iv);cipher.setAAD(Buffer.from(JSON.stringify([1,channelId,version])));const body=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body])}
  private unprotect(value:Uint8Array,channelId:string,version:number){const bytes=Buffer.from(value);if(bytes.length<29)throw new Error('invalid protected secret');const decipher=createDecipheriv('aes-256-gcm',this.key,bytes.subarray(0,12));decipher.setAAD(Buffer.from(JSON.stringify([1,channelId,version])));decipher.setAuthTag(bytes.subarray(12,28));return Buffer.concat([decipher.update(bytes.subarray(28)),decipher.final()])}
}
const view=(row:Record<string,unknown>):WebhookChannelView=>({channelId:String(row.channel_id),workspaceId:String(row.workspace_id),recipientDeviceId:String(row.recipient_device_id),recipientPublicKey:String(row.recipient_public_key),label:String(row.label),secretVersion:Number(row.secret_version),status:String(row.status) as 'active'|'revoked',createdAt:String(row.created_at),rotatedAt:String(row.rotated_at),revokedAt:row.revoked_at?String(row.revoked_at):undefined})
