import {createHash,createHmac,randomBytes,randomUUID} from 'node:crypto'
import {mkdtempSync,writeFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import sodium from 'libsodium-wrappers-sumo'
import {afterEach,describe,expect,it} from 'vitest'
import {WaypointCrypto} from '../../electron/core/sync/crypto.js'
import {DesktopRelayClient} from '../../electron/core/sync/desktop-relay-client.js'
import {prepareSignedWebhook,openInboundWebhook} from '../../electron/core/sync/webhook-crypto.js'
import {createRelayServer} from './server.js'

describe('production signed inbound webhook',()=>{
  const servers:Array<Awaited<ReturnType<typeof createRelayServer>>['server']>=[];afterEach(async()=>{for(const server of servers.splice(0))await new Promise<void>((resolve)=>server.close(()=>resolve()))})
  async function setup(){await sodium.ready;const root=mkdtempSync(path.join(tmpdir(),'waypoint-hook-')),database=path.join(root,'relay.sqlite'),registry=path.join(root,'authority.json'),webhookKey=path.join(root,'webhook.key'),crypto=await WaypointCrypto.create(),owner=crypto.generateDevice('opaque_hook_owner01'),peer=crypto.generateDevice('opaque_hook_peer_01'),workspaceId='opaque_hook_workspace01';writeFileSync(registry,JSON.stringify({version:1,workspaces:[{workspaceId,keyEpoch:1,devices:[{deviceId:owner.deviceId,signingPublicKey:owner.signingPublicKey,encryptionPublicKey:owner.encryptionPublicKey,active:true,role:'owner'},{deviceId:peer.deviceId,signingPublicKey:peer.signingPublicKey,encryptionPublicKey:peer.encryptionPublicKey,active:true,role:'peer'}]}]}));writeFileSync(webhookKey,randomBytes(32));const instance=await createRelayServer({host:'127.0.0.1',port:8789,databasePath:database,authorityRegistryPath:registry,webhookKeyPath:webhookKey,tlsMode:'proxy-loopback',logLevel:'info'});servers.push(instance.server);await new Promise<void>((resolve)=>instance.server.listen(0,'127.0.0.1',resolve));const address=instance.server.address();if(!address||typeof address==='string')throw new Error('missing address');const base=`http://127.0.0.1:${address.port}`,request:typeof fetch=(input,init)=>fetch(String(input instanceof Request?input.url:input).replace('https://waypoint-relay.johnnycode.ai',base),init),client=await DesktopRelayClient.create({endpoint:'https://waypoint-relay.johnnycode.ai',workspaceId,device:owner,keyEpoch:1},request),peerClient=await DesktopRelayClient.create({endpoint:'https://waypoint-relay.johnnycode.ai',workspaceId,device:peer,keyEpoch:1},request);return{base,client,peerClient,owner,workspaceId}}
  it('creates, signs, queues, decrypts, acknowledges, rotates, revokes, and kills with zero effects',async()=>{const{base,client,owner}=await setup(),channel=await client.createWebhookChannel('CI intake'),request=await prepareSignedWebhook({channelId:channel.channelId,secretVersion:channel.secretVersion,secret:channel.secret,recipientPublicKey:channel.recipientPublicKey,eventType:'build.completed',payload:{result:'ok'}}),accepted=await fetch(`${base}${request.path}`,{method:'POST',headers:request.headers,body:request.body});expect(accepted.status).toBe(202);expect((await fetch(`${base}${request.path}`,{method:'POST',headers:request.headers,body:request.body})).status).toBe(401);const pulled=await client.pullWebhookEvents();expect(pulled.events).toHaveLength(1);expect(await openInboundWebhook(pulled.events[0].ciphertextBase64,owner.encryptionPublicKey,owner.encryptionPrivateKey)).toMatchObject({eventType:'build.completed',payload:{result:'ok'}});expect((await client.acknowledgeWebhookEvent(request.eventId)).acknowledged).toBe(true);const rotated=await client.rotateWebhookChannel(channel.channelId);const stale=await prepareSignedWebhook({channelId:channel.channelId,secretVersion:channel.secretVersion,secret:channel.secret,recipientPublicKey:channel.recipientPublicKey,eventType:'build.completed',payload:{result:'stale'}});expect((await fetch(`${base}${stale.path}`,{method:'POST',headers:stale.headers,body:stale.body})).status).toBe(400);await client.setWebhookKill(true);const killed=await prepareSignedWebhook({channelId:channel.channelId,secretVersion:rotated.secretVersion,secret:rotated.secret,recipientPublicKey:channel.recipientPublicKey,eventType:'build.completed',payload:{result:'killed'}});expect((await fetch(`${base}${killed.path}`,{method:'POST',headers:killed.headers,body:killed.body})).status).toBe(401);await client.setWebhookKill(false);await client.revokeWebhookChannel(channel.channelId);expect((await fetch(`${base}${killed.path}`,{method:'POST',headers:killed.headers,body:killed.body})).status).toBe(401)})
  it('fails closed on expiry, tamper, MIME, malformed, and oversize',async()=>{const{base,client}=await setup(),channel=await client.createWebhookChannel('Bounded'),expired=await prepareSignedWebhook({channelId:channel.channelId,secretVersion:1,secret:channel.secret,recipientPublicKey:channel.recipientPublicKey,eventType:'build.completed',payload:{result:'old'},timestamp:new Date(Date.now()-61_000).toISOString()});expect((await fetch(`${base}${expired.path}`,{method:'POST',headers:expired.headers,body:expired.body})).status).toBe(401);const valid=await prepareSignedWebhook({channelId:channel.channelId,secretVersion:1,secret:channel.secret,recipientPublicKey:channel.recipientPublicKey,eventType:'build.completed',payload:{result:'ok'}}),tampered=Buffer.from(valid.body);tampered[tampered.length-2]^=1;expect((await fetch(`${base}${valid.path}`,{method:'POST',headers:valid.headers,body:tampered})).status).toBe(401);expect((await fetch(`${base}${valid.path}`,{method:'POST',headers:{...valid.headers,'content-type':'application/json'},body:valid.body})).status).toBe(400);const body=Buffer.from('{}'),timestamp=new Date().toISOString(),nonce=randomUUID(),signature=createHmac('sha256',channel.secret).update(JSON.stringify([1,channel.channelId,1,'POST',valid.path,timestamp,nonce,createHashHex(body)])).digest('base64');expect((await fetch(`${base}${valid.path}`,{method:'POST',headers:{...valid.headers,'x-waypoint-timestamp':timestamp,'x-waypoint-nonce':nonce,'x-waypoint-signature':signature},body})).status).toBe(400);const oversized=Buffer.alloc(262_145);expect((await fetch(`${base}${valid.path}`,{method:'POST',headers:valid.headers,body:oversized})).status).toBe(413)})
  it('denies channel metadata and management to an enrolled peer',async()=>{const{peerClient}=await setup();await expect(peerClient.webhookChannels()).rejects.toThrow(/403:owner_required/);await expect(peerClient.createWebhookChannel('Denied')).rejects.toThrow(/403:owner_required/)})
  it('creates only the exact preapproved channel ID and rejects a collision',async()=>{const{client}=await setup(),channelId='preapproved_channel_000001',created=await client.createWebhookChannel('Approved','github',channelId);expect(created.channelId).toBe(channelId);await expect(client.createWebhookChannel('Collision','github',channelId)).rejects.toThrow()})
  it('authenticates and encrypts a native Azure DevOps event before desktop import and rejects replay after ACK',async()=>{const{base,client,owner}=await setup(),channel=await client.createWebhookChannel('Azure PR','azure_devops'),body=JSON.stringify({id:'azure-delivery-123',eventType:'git.pullrequest.created',createdDate:new Date().toISOString(),resource:{pullRequestId:42,title:'Review me',repository:{id:'repo-1',name:'Waypoint'}}}),endpoint=`${base}/v1/native-hooks/${channel.channelId}`,headers={'content-type':'application/json',authorization:`Basic ${Buffer.from(`waypoint:${channel.secret}`).toString('base64')}`},authorized=await fetch(endpoint,{method:'POST',headers,body});expect(authorized.status).toBe(202);expect((await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Basic ${Buffer.from('waypoint:wrong').toString('base64')}`},body})).status).toBe(401);const pulled=await client.pullWebhookEvents(),opened=await openInboundWebhook(pulled.events[0].ciphertextBase64,owner.encryptionPublicKey,owner.encryptionPrivateKey);expect(opened).toMatchObject({version:2,connectorId:'azure_devops',sourceEventId:'azure-delivery-123',eventType:'azure_devops.git.pullrequest.created',payload:{'resource.pullRequestId':42,'resource.repository.name':'Waypoint'}});expect(JSON.stringify(opened)).not.toContain(channel.secret);expect((await client.acknowledgeWebhookEvent(pulled.events[0].eventId)).acknowledged).toBe(true);expect((await fetch(endpoint,{method:'POST',headers,body})).status).toBe(401)})
})
const createHashHex=(body:Buffer)=>createHash('sha256').update(body).digest('hex')
