import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { WorkspaceStore } from './store.js';
import type { InboundChange } from './sync/sync-store.js';

const roots:string[]=[];
afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true})});
function fixture(){const root=mkdtempSync(path.join(tmpdir(),'waypoint-activity-'));roots.push(root);const store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),workspace=store.createWorkspace('Activity',root);return{store,workspace}}
const png=new Uint8Array([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]);
const context=(capturedAt=new Date().toISOString())=>({capturedAt,deviceId:'mac-fixture',displayId:'display-1',appBundleId:'com.example.editor',appProcess:'editor',appTitle:'Fixture editor',locked:false,sleeping:false,diskAvailableBytes:1024**3,identityAfterCapture:'com.example.editor'});

describe('workspace activity capture lifecycle',()=>{
  it('persists restart-safe policy and never captures before explicit resume',()=>{const{store,workspace}=fixture();expect(store.captureActivitySnapshot(workspace.id,context(),png)).toMatchObject({accepted:false,reason:'paused'});store.setActivityCapturePolicy(workspace.id,{version:1,enabled:true,paused:false,retentionDays:183,syncRaw:false,exclusions:['com.example.private']});expect(store.activityCapturePolicy(workspace.id)).toMatchObject({enabled:true,paused:false,retentionDays:183,syncRaw:false});store.close()});
  it('stores bounded provenance, supports search, and leaks no title or hash to activity receipts',()=>{const{store,workspace}=fixture();store.setActivityCapturePolicy(workspace.id,{version:1,enabled:true,paused:false,retentionDays:90,syncRaw:false,exclusions:[]});const result=store.captureActivitySnapshot(workspace.id,context(),png);expect(result.accepted).toBe(true);expect(store.listActivitySnapshots(workspace.id,'fixture')).toHaveLength(1);expect(store.activityCaptureStorage(workspace.id)).toEqual({count:1,bytes:png.byteLength});const activity=store.listActivity(workspace.id,{query:'capture.saved'});expect(JSON.stringify(activity)).not.toContain('Fixture editor');expect(JSON.stringify(activity)).not.toMatch(/[a-f0-9]{64}/);store.close()});
  it('rechecks the latest exclusion immediately before persistence',()=>{const{store,workspace}=fixture();store.setActivityCapturePolicy(workspace.id,{version:1,enabled:true,paused:false,retentionDays:90,syncRaw:false,exclusions:[]});expect(()=>store.captureActivitySnapshot(workspace.id,context(),png,()=>{store.setActivityCapturePolicy(workspace.id,{...store.activityCapturePolicy(workspace.id),exclusions:['com.example.editor']})})).toThrow('app_excluded');expect(store.listActivitySnapshots(workspace.id)).toEqual([]);expect(store.listAttachments(workspace.id)).toEqual([]);store.close()});
  it('hard deletes and journals anti-resurrection tombstones when raw sync is opted in',()=>{const{store,workspace}=fixture();store.setActivityCapturePolicy(workspace.id,{version:1,enabled:true,paused:false,retentionDays:90,syncRaw:true,exclusions:[]});const snapshot=store.captureActivitySnapshot(workspace.id,context(),png).snapshot!;expect(store.pendingSyncChanges(workspace.id).map((item)=>item.objectKind)).toEqual(expect.arrayContaining(['activity_snapshot','attachment']));store.deleteActivitySnapshot(workspace.id,snapshot.id);expect(store.listActivitySnapshots(workspace.id)).toEqual([]);expect(store.listAttachments(workspace.id)).toEqual([]);expect(store.pendingSyncChanges(workspace.id).filter((item)=>item.operation==='delete')).toHaveLength(2);expect(()=>store.captureActivitySnapshot(workspace.id,{...context(),capturedAt:new Date(Date.now()-91*86_400_000).toISOString()},png)).not.toThrow();store.close()});
  it('purges expired rows at an exact UTC boundary',()=>{const{store,workspace}=fixture();store.setActivityCapturePolicy(workspace.id,{version:1,enabled:true,paused:false,retentionDays:90,syncRaw:false,exclusions:[]});const capturedAt=new Date().toISOString(),id=store.captureActivitySnapshot(workspace.id,context(capturedAt),png).snapshot!.id;expect(store.purgeExpiredActivitySnapshots(workspace.id,new Date(Date.parse(capturedAt)+90*86_400_000-1).toISOString())).toBe(0);expect(store.purgeExpiredActivitySnapshots(workspace.id,new Date(Date.parse(capturedAt)+90*86_400_000).toISOString())).toBe(1);expect(()=>store.deleteActivitySnapshot(workspace.id,id)).toThrow('not found');store.close()});
  it('keeps raw snapshots out of backup unless raw sync/backup is explicitly enabled',()=>{const{store,workspace}=fixture();store.setActivityCapturePolicy(workspace.id,{version:1,enabled:true,paused:false,retentionDays:90,syncRaw:false,exclusions:[]});store.captureActivitySnapshot(workspace.id,context(),png);let archive=store.exportWorkspace(workspace.id);expect(archive.objects.activity_snapshots).toEqual([]);expect((archive.objects.attachments as Array<Record<string,unknown>>).some((row)=>row.name==='activity.png')).toBe(false);store.setActivityCapturePolicy(workspace.id,{...store.activityCapturePolicy(workspace.id),syncRaw:true});archive=store.exportWorkspace(workspace.id);expect(archive.objects.activity_snapshots).toHaveLength(1);expect((archive.objects.attachments as Array<Record<string,unknown>>).some((row)=>row.name==='activity.png')).toBe(true);store.close()});
  it('restores opted-in raw snapshots paused with validated provenance',()=>{const{store,workspace}=fixture();store.setActivityCapturePolicy(workspace.id,{version:1,enabled:true,paused:false,retentionDays:183,syncRaw:true,exclusions:['private-app']});store.captureActivitySnapshot(workspace.id,context(),png);const archive=store.exportWorkspace(workspace.id),restored=store.restoreWorkspace(archive,'Restored',path.join(path.dirname(store.databasePath),'restored'));expect(store.activityCapturePolicy(restored.id)).toMatchObject({enabled:true,paused:true,retentionDays:183,syncRaw:true,exclusions:['private-app']});expect(store.listActivitySnapshots(restored.id)).toHaveLength(1);store.close()});
  it('tombstones previously synced raw history even after sync is disabled',()=>{const{store,workspace}=fixture();store.setActivityCapturePolicy(workspace.id,{version:1,enabled:true,paused:false,retentionDays:90,syncRaw:true,exclusions:[]});const snapshot=store.captureActivitySnapshot(workspace.id,context(),png).snapshot!;store.setActivityCapturePolicy(workspace.id,{...store.activityCapturePolicy(workspace.id),syncRaw:false});store.deleteActivitySnapshot(workspace.id,snapshot.id);expect(store.pendingSyncChanges(workspace.id).filter((item)=>item.operation==='delete').map((item)=>item.objectKind).sort()).toEqual(['activity_snapshot','attachment']);store.close()});
  it('fails closed for opted-out inbound raw history and validates opted-in resumable attachment provenance',()=>{const{store,workspace}=fixture(),capturedAt=new Date().toISOString(),expiresAt=new Date(Date.now()+90*86_400_000).toISOString(),snapshotId='remote-snapshot-001',attachmentId='remote-attachment-01',digest='4c4b6a3be1314ab86138bef4314dde022e600960d8689a2c8f8631802d20dab6';const change=(overrides:Partial<InboundChange>):InboundChange=>({envelopeId:`env-${String(overrides.id)}`,workspaceId:workspace.id,objectId:snapshotId,objectKind:'activity_snapshot',operation:'upsert',id:'remote-change-001',deviceId:'peer-device',sequence:1,clock:{'peer-device':1},payload:{id:snapshotId,attachmentId,capturedAt,deviceId:'peer-device',displayId:'display-1',appBundleId:'com.example.editor',appProcess:'editor',policyVersion:1,sourceSha256:digest,expiresAt,createdAt:capturedAt},createdAt:capturedAt,...overrides});expect(()=>store.applyInboundSyncChange(change({}))).toThrow('disabled');store.setActivityCapturePolicy(workspace.id,{version:1,enabled:false,paused:true,retentionDays:90,syncRaw:true,exclusions:[]});expect(store.applyInboundSyncChange(change({envelopeId:'env-enabled',id:'remote-change-002',sequence:2,clock:{'peer-device':2}}))).toBe('applied');expect(()=>store.applyInboundSyncChange(change({envelopeId:'env-bad-attachment',id:'remote-change-003',objectId:attachmentId,objectKind:'attachment',sequence:3,clock:{'peer-device':3},payload:{id:attachmentId,ownerId:snapshotId,name:'wrong.jpg',mediaType:'image/jpeg',sha256:digest,bytes:png.byteLength,createdAt:capturedAt}}),1)).toThrow('provenance');const transfer='remote-change-004';expect(store.applyInboundSyncChange(change({envelopeId:'env-valid-attachment',id:transfer,objectId:attachmentId,objectKind:'attachment',sequence:3,clock:{'peer-device':3},payload:{id:attachmentId,ownerId:snapshotId,name:'activity.png',mediaType:'image/png',sha256:digest,bytes:png.byteLength,createdAt:capturedAt}}),1)).toBe('applied');expect(store.missingInboundAttachmentChunks(workspace.id,transfer,1)).toEqual([0]);expect(store.acceptInboundAttachmentChunk(workspace.id,transfer,0,1,png)).toBe(true);expect(store.listActivitySnapshots(workspace.id)).toHaveLength(1);store.close()});
  it('returns private bytes only through exact workspace-scoped snapshot identity',()=>{const{store,workspace}=fixture(),other=store.createWorkspace('Other',path.dirname(store.databasePath));store.setActivityCapturePolicy(workspace.id,{version:1,enabled:true,paused:false,retentionDays:90,syncRaw:false,exclusions:[]});const id=store.captureActivitySnapshot(workspace.id,context(),png).snapshot!.id;expect(Buffer.from(store.readActivitySnapshot(workspace.id,id).dataBase64,'base64')).toEqual(Buffer.from(png));expect(()=>store.readActivitySnapshot(other.id,id)).toThrow('not found');store.close()});
});
