import {mkdtempSync,realpathSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {describe,expect,it} from 'vitest'
import {WorkspaceStore} from './store.js'
import {assertAutomationSkillVerified,automationProposalDigest,validateAutomationProposal} from './webhook-automations.js'

describe('Azure DevOps exact skill automation dry setup',()=>{
  it('prepares the scv2 PR-created Claude skill route without an external mutation',()=>{
    const root=realpathSync.native(mkdtempSync(path.join(tmpdir(),'waypoint-azdo-skill-dry-'))),store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),workspace=store.createWorkspace('Azure DevOps skill dry run',root),profile=store.listSecurityProfiles(workspace.id).find((item)=>item.name==='Developer · approve changes')!,definition=validateAutomationProposal({version:1,title:'scv2 automatic PR review',trigger:{connectorId:'azure_devops',eventType:'azure_devops.git.pullrequest.created',filters:{'resource.repository.name':'scv2'}},action:{kind:'ai_skill',provider:'claude',model:'claude-sonnet',securityProfileId:profile.id,skillIdentifier:'auto-pr-review',instruction:'/auto-pr-review --source azure-devops --use-event-payload'},delivery:{channelId:'channel_0000000000000001',endpoint:'https://waypoint-relay.johnnycode.ai/v1/native-hooks/channel_0000000000000001',reachability:'public_relay'},provisioning:{mode:'az_devops_invoke',organization:'https://dev.azure.com/example',project:'scv2',repository:'scv2',targetBranch:'refs/heads/main'}}),proposal=store.createAutomationProposal(workspace.id,undefined,definition)
    expect(proposal).toMatchObject({status:'proposed',definition:{action:{kind:'ai_skill',provider:'claude',skillIdentifier:'auto-pr-review'},delivery:{reachability:'public_relay'},provisioning:{mode:'az_devops_invoke',project:'scv2'}},question:{status:'pending'}})
    expect(proposal.proposalDigest).toBe(automationProposalDigest(proposal.definition));expect(proposal.definition.action).toMatchObject({executionRoot:store.workspaceExecutionRoot(workspace.id),profileDigest:expect.stringMatching(/^[a-f0-9]{64}$/)});expect(proposal.receipt).toBeUndefined();expect(store.listAutomationRulesAndRuns(workspace.id)).toMatchObject({rules:[],runs:[]});store.decideAutomationProposal(workspace.id,proposal.id,proposal.proposalDigest,'approve');store.beginAutomationProvisioning(workspace.id,proposal.id,proposal.proposalDigest);store.checkpointAutomationProvisioning(workspace.id,proposal.id,proposal.proposalDigest,{executed:true,outcome:'partial',summary:'Fake Waypoint receiver and Azure provider hook created',delivery:proposal.definition.delivery,externalId:'fake-azure-subscription',rollback:{waypoint:{operation:'delete_channel',channelId:proposal.definition.delivery.channelId},provider:{operation:'delete_subscription',id:'fake-azure-subscription'}}});const applied=store.finishAutomationProvisioning(workspace.id,proposal.id,proposal.proposalDigest,{status:'applied',summary:'Fake Azure hook reconciled and exact rule enabled',externalId:'fake-azure-subscription',delivery:{channelId:proposal.definition.delivery.channelId!,endpoint:proposal.definition.delivery.endpoint!,reachability:'public_relay'},rollback:{waypoint:{operation:'delete_channel'},provider:{operation:'delete_subscription'}}});expect(applied).toMatchObject({status:'applied',receipt:{decision:'approved',externalMutation:{status:'applied',externalId:'fake-azure-subscription'}}});expect(store.listAutomationRulesAndRuns(workspace.id).rules).toEqual([expect.objectContaining({status:'enabled',action:expect.objectContaining({kind:'ai_skill',provider:'claude',skillIdentifier:'auto-pr-review'}),connectorId:'azure_devops',proposalId:proposal.id})]);store.close()
  })
  it('does not create an approval record when the Waypoint receiver is unavailable',()=>{const root=realpathSync.native(mkdtempSync(path.join(tmpdir(),'waypoint-azdo-no-receiver-'))),store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),workspace=store.createWorkspace('Azure DevOps missing receiver',root),profile=store.listSecurityProfiles(workspace.id).find((item)=>item.name==='Developer · approve changes')!,definition=validateAutomationProposal({version:1,title:'missing receiver',trigger:{connectorId:'azure_devops',eventType:'azure_devops.git.pullrequest.created',filters:{}},action:{kind:'ai_prompt',provider:'claude',securityProfileId:profile.id,instruction:'Review PR'},delivery:{reachability:'not_configured'},provisioning:{mode:'az_devops_invoke'}});expect(()=>store.createAutomationProposal(workspace.id,undefined,definition)).toThrow(/Waypoint receiver prerequisite/);expect(store.listAutomationProposals(workspace.id)).toEqual([]);store.close()})
  it('requires the exact current provider inventory proof before central proposal creation',()=>{const definition=validateAutomationProposal({version:1,title:'verified skill',trigger:{connectorId:'generic',eventType:'generic.test',filters:{}},action:{kind:'ai_skill',provider:'claude',securityProfileId:'profile',skillIdentifier:'auto-pr-review',instruction:'/auto-pr-review --event-context'},delivery:{reachability:'not_configured'},provisioning:{mode:'manual'}});expect(()=>assertAutomationSkillVerified(definition)).toThrow(/has not been verified/);expect(()=>assertAutomationSkillVerified(definition,{provider:'codex',identifier:'auto-pr-review'})).toThrow(/has not been verified/);expect(()=>assertAutomationSkillVerified(definition,{provider:'claude',identifier:'missing'})).toThrow(/has not been verified/);expect(()=>assertAutomationSkillVerified(definition,{provider:'claude',identifier:'auto-pr-review'})).not.toThrow()})
})
