import {describe,expect,it} from 'vitest'
import {runBackupAdministration} from './backup-administration-runner.js'

class FakeWorker{private listeners=new Map<string,(value:unknown)=>void>();terminated=false;once(event:'message',listener:(value:unknown)=>void):this;once(event:'error',listener:()=>void):this;once(event:'exit',listener:(code:number)=>void):this;once(event:'message'|'error'|'exit',listener:((value:unknown)=>void)|(()=>void)|((code:number)=>void)){this.listeners.set(event,listener as (value:unknown)=>void);return this}emit(event:'message'|'error'|'exit',value:unknown){this.listeners.get(event)?.(value)}async terminate(){this.terminated=true;return 1}}

describe('off-main backup administration',()=>{
  it('returns a validated result only after the worker exits cleanly',async()=>{const worker=new FakeWorker(),pending=runBackupAdministration('verify','/private/path/backup.json',()=>worker),counts=Object.fromEntries(['documents','revisions','chats','messages','memories','memory_suggestions','commitments','rule_suggestions','rule_suggestion_sources','learned_rules','rule_outcomes','relationships','attachments','meetings','fixture_playbooks','fixture_playbook_runs','activities','tombstones','security_profiles','executions','execution_events'].map((key)=>[key,key==='documents'?1:0]));worker.emit('message',{status:'passed',fileName:'/worker/leak.json',version:3,exportedAt:new Date().toISOString(),counts,totalObjects:1});const concurrent=await runBackupAdministration('verify','/tmp/concurrent.json',()=>new FakeWorker());expect(concurrent).toMatchObject({status:'failed',code:'busy'});worker.emit('exit',0);await expect(pending).resolves.toMatchObject({status:'passed',fileName:'backup.json'})})
  it('allows only one worker and releases the slot after completion',async()=>{const worker=new FakeWorker(),first=runBackupAdministration('drill','/tmp/first.json',()=>worker);await expect(runBackupAdministration('verify','/secret/second.json',()=>new FakeWorker())).resolves.toMatchObject({status:'failed',fileName:'second.json',code:'busy'});worker.emit('message',{status:'failed',fileName:'first.json',code:'invalid',remediation:'untrusted'});worker.emit('exit',0);await first;const next=new FakeWorker(),third=runBackupAdministration('verify','/tmp/third.json',()=>next);next.emit('error',new Error('private raw failure'));await expect(third).resolves.toEqual({status:'failed',fileName:'third.json',code:'worker_failed',remediation:'Waypoint could not complete the local backup check. Keep the original backup unchanged and try again.'})})
  it('rejects malformed messages and abnormal exits without exposing worker data',async()=>{for(const deliver of [(worker:FakeWorker)=>{worker.emit('message',{status:'passed',fileName:'/leaked/path'});worker.emit('exit',0)},(worker:FakeWorker)=>worker.emit('exit',7)]){const worker=new FakeWorker(),pending=runBackupAdministration('verify','/safe/selected.json',()=>worker);deliver(worker);await expect(pending).resolves.toMatchObject({status:'failed',fileName:'selected.json',code:'worker_failed'})}})
  it('terminates a hung drill, removes its parent-owned directory, and releases the slot',async()=>{const worker=new FakeWorker();let removed='';const pending=runBackupAdministration('drill','/tmp/hung.json',()=>worker,{deadlineMs:5,remove:async(target)=>{removed=target}});await expect(pending).resolves.toMatchObject({status:'failed',code:'worker_failed'});expect(worker.terminated).toBe(true);expect(removed).toContain('waypoint-restore-worker-');const next=new FakeWorker(),nextRun=runBackupAdministration('verify','/tmp/next.json',()=>next);next.emit('exit',9);await nextRun})
})
