import {mkdtempSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import type {ExportArchive} from './types.js'
import {createHash} from 'node:crypto'
import {readBackupReadonly,validateArchive} from './backup.js'
import {WorkspaceStore} from './store.js'

const RESTORED_TABLES=['documents','revisions','chats','messages','memories','memory_suggestions','commitments','rule_suggestions','rule_suggestion_sources','learned_rules','rule_outcomes','relationships','attachments','document_import_sources','meetings','fixture_playbooks','fixture_playbook_runs','local_trigger_settings','local_events','local_trigger_rules','local_trigger_runs','external_inbound_events','activities','tombstones','security_profiles','executions','execution_events'] as const
export type BackupCheckResult={status:'passed';fileName:string;version:2|3;exportedAt:string;counts:Record<string,number>;totalObjects:number}|{status:'failed';fileName:string;code:'invalid'|'unsupported'|'too_large'|'io'|'restore_failed'|'cleanup_failed'|'busy'|'worker_failed';remediation:string}
export type RestoreDrillResult=BackupCheckResult&{drill?:{databaseIntegrity:'ok';foreignKeyViolations:0;missingFiles:0;digestMismatches:0;searchDifference:0;countsMatch:true;temporaryDataRemoved:true}}

function safeName(filePath:string):string{return path.basename(filePath).slice(0,255)||'selected backup'}
export function summarizeBackup(archive:ExportArchive,fileName:string):Extract<BackupCheckResult,{status:'passed'}>{archive=validateArchive(archive);const workspace=archive.workspace as Record<string,unknown>,createdAt=Date.parse(String(workspace.created_at)),exportedAt=Date.parse(archive.exportedAt),futureLimit=Date.now()+5*60_000;if(typeof workspace.id!=='string'||!workspace.id||typeof workspace.name!=='string'||!workspace.name.trim()||typeof workspace.created_at!=='string'||!Number.isFinite(createdAt))throw new Error('Archive workspace identity is invalid');if(createdAt>futureLimit||exportedAt>futureLimit||exportedAt<createdAt)throw new Error('Archive timestamp ordering is invalid');for(const row of archive.objects.attachments??[]){const item=row as Record<string,unknown>,bytes=Buffer.from(String(item.data_base64),'base64');if(!/^[a-f0-9]{64}$/.test(String(item.sha256))||createHash('sha256').update(bytes).digest('hex')!==item.sha256)throw new Error('Archive attachment integrity check failed')}for(const row of archive.objects.meetings??[]){const item=row as Record<string,unknown>;if(item.audio_data_base64==null)continue;const bytes=Buffer.from(String(item.audio_data_base64),'base64');if(!/^[a-f0-9]{64}$/.test(String(item.sha256))||createHash('sha256').update(bytes).digest('hex')!==item.sha256)throw new Error('Archive meeting audio integrity check failed')}const counts=Object.fromEntries(RESTORED_TABLES.map((table)=>[table,(archive.objects[table]??[]).length]));return{status:'passed',fileName:safeName(fileName),version:archive.version,exportedAt:archive.exportedAt,counts,totalObjects:Object.values(counts).reduce((sum,count)=>sum+count,0)}}
function failure(filePath:string,error:unknown,drill=false):Extract<BackupCheckResult,{status:'failed'}>{const message=error instanceof Error?error.message:'',code=drill?'restore_failed':/size limit|too many|oversized|exceeds/i.test(message)?'too_large':/Unsupported archive version|unsupported/i.test(message)?'unsupported':/ENOENT|EACCES|EPERM|is a directory/i.test(message)?'io':'invalid';return{status:'failed',fileName:safeName(filePath),code,remediation:code==='too_large'?'Choose a backup within Waypoint’s documented local limits.':code==='unsupported'?'Use a backup version supported by this Waypoint build.':code==='io'?'Check that the selected file is readable and try again.':drill?'Keep the original backup unchanged and use a different verified backup.':'Choose an unmodified Waypoint backup and verify it again.'}}
export function inspectBackupFile(filePath:string):BackupCheckResult{try{return summarizeBackup(readBackupReadonly(filePath),filePath)}catch(error){return failure(filePath,error)}}
export function runRestoreDrill(filePath:string,temporaryParent=tmpdir(),dependencies:{createStore?:(databasePath:string)=>WorkspaceStore;remove?:(target:string)=>void}={}):RestoreDrillResult{
  const inspected=inspectBackupFile(filePath);if(inspected.status==='failed')return inspected
  let root:string|undefined,store:WorkspaceStore|undefined,result!:RestoreDrillResult
  try{const archive=readBackupReadonly(filePath);root=mkdtempSync(path.join(temporaryParent,'waypoint-restore-drill-'));store=dependencies.createStore?.(path.join(root,'drill.sqlite'))??new WorkspaceStore(path.join(root,'drill.sqlite'));const restored=store.restoreWorkspace(archive,'Restore drill',root),diagnostics=store.localDiagnostics(restored.id),roundTrip=summarizeBackup(store.exportWorkspace(restored.id),filePath),countsMatch=RESTORED_TABLES.every((table)=>roundTrip.counts[table]===inspected.counts[table]+(table==='activities'?1:0));if(diagnostics.integrity!=='ok'||diagnostics.foreignKeyViolations||diagnostics.missingFiles||diagnostics.digestMismatches||diagnostics.indexedObjects!==diagnostics.expectedObjects||!countsMatch)throw new Error('Restore drill verification failed');result={...inspected,drill:{databaseIntegrity:'ok',foreignKeyViolations:0,missingFiles:0,digestMismatches:0,searchDifference:0,countsMatch:true,temporaryDataRemoved:true}}}catch(error){result=failure(filePath,error,true)}finally{let cleanupFailed=false;try{store?.close()}catch{cleanupFailed=true}if(root)try{if(dependencies.remove)dependencies.remove(root);else rmSync(root,{recursive:true,force:true,maxRetries:2,retryDelay:50})}catch{cleanupFailed=true}if(cleanupFailed)result={status:'failed',fileName:safeName(filePath),code:'cleanup_failed',remediation:'Remove the temporary Waypoint restore-drill folder from the system temporary directory, then retry.'}}return result
}
