import {mkdirSync,mkdtempSync,readFileSync,readdirSync,rmSync,writeFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {afterEach,describe,expect,it} from 'vitest'
import {archiveIntegrity,writeAtomicBackup} from './backup.js'
import {inspectBackupFile,runRestoreDrill,summarizeBackup} from './backup-administration.js'
import {WorkspaceStore} from './store.js'

const roots:string[]=[]
afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true})})
function backup(){const root=mkdtempSync(path.join(tmpdir(),'waypoint-admin-test-')),store=new WorkspaceStore(path.join(root,'live.sqlite')),workspace=store.createWorkspace('Private workspace',root);roots.push(root);store.createDocument(workspace.id,'Needle','restore drill needle');const file=path.join(root,'private-name.json');writeAtomicBackup(file,store.exportWorkspace(workspace.id));store.close();return{root,file}}
describe('local backup administration',()=>{
  it('reports only bounded aggregate metadata for every portable family',()=>{const{file}=backup(),result=inspectBackupFile(file);expect(result).toMatchObject({status:'passed',fileName:'private-name.json',version:3,counts:{documents:1,revisions:1,document_import_sources:0,local_events:0,external_inbound_events:0,automation_proposals:0,automation_questions:0,automation_approval_receipts:0,automation_provisioning_events:0,automation_rules:0,automation_runs:0,tool_gateway_settings:0,tool_gateway_receipts:0,tool_failure_knowledge:0,provider_usage_receipts:0,hosted_runs:0,hosted_run_events:0,provider_sessions:0,provider_requests:0}});if(result.status==='passed'){expect(Object.keys(result.counts)).toHaveLength(41);expect(result.totalObjects).toBe(Object.values(result.counts).reduce((sum,count)=>sum+count,0))}expect(JSON.stringify(result)).not.toContain('Private workspace');expect(JSON.stringify(result)).not.toContain('restore drill needle')})
  it('runs the real restore path in isolation and removes all drill data',()=>{const{root,file}=backup(),temporaryParent=path.join(root,'temporary');mkdirSync(temporaryParent);const result=runRestoreDrill(file,temporaryParent);expect(result).toMatchObject({status:'passed',drill:{databaseIntegrity:'ok',countsMatch:true,temporaryDataRemoved:true}});expect(readdirSync(temporaryParent)).toEqual([])})
  it('returns sanitized failures for corruption and future versions',()=>{const{root,file}=backup();writeFileSync(file,'not json');expect(inspectBackupFile(file)).toMatchObject({status:'failed',fileName:'private-name.json',code:'invalid'});const value={version:99,exportedAt:new Date().toISOString(),workspace:{},objects:{}},future={...value,integrity:archiveIntegrity(value as never)},futureFile=path.join(root,'future.json');writeFileSync(futureFile,JSON.stringify(future));expect(inspectBackupFile(futureFile)).toMatchObject({status:'failed',code:'unsupported'});expect(()=>summarizeBackup(future as never,futureFile)).toThrow(/Unsupported/)})
  it('does not run crash recovery while inspecting a selected file',()=>{const{file}=backup(),previous=`${file}.previous`;writeFileSync(previous,'leave this sibling untouched');inspectBackupFile(file);expect(readFileSync(previous,'utf8')).toBe('leave this sibling untouched')})
  it('rejects embedded attachment bytes whose digest is false even with a valid envelope',()=>{const{file}=backup(),archive=JSON.parse(readFileSync(file,'utf8'));archive.objects.attachments=[{id:'attachment-1',data_base64:Buffer.from('tampered').toString('base64'),sha256:'0'.repeat(64)}];archive.integrity=archiveIntegrity({version:archive.version,exportedAt:archive.exportedAt,workspace:archive.workspace,objects:archive.objects});writeFileSync(file,JSON.stringify(archive));expect(inspectBackupFile(file)).toMatchObject({status:'failed',code:'invalid'})})
  it('rejects impossible workspace and export timestamp ordering',()=>{const{file}=backup(),archive=JSON.parse(readFileSync(file,'utf8'));archive.workspace.created_at=new Date(Date.now()+60_000).toISOString();archive.integrity=archiveIntegrity({version:archive.version,exportedAt:archive.exportedAt,workspace:archive.workspace,objects:archive.objects});writeFileSync(file,JSON.stringify(archive));expect(inspectBackupFile(file)).toMatchObject({status:'failed',code:'invalid'})})
  it('attempts deletion even if closing the drill database fails',()=>{const{root,file}=backup(),temporaryParent=path.join(root,'temporary');mkdirSync(temporaryParent);let removed=false;const result=runRestoreDrill(file,temporaryParent,{createStore:(database)=>{const store=new WorkspaceStore(database),close=store.close.bind(store);store.close=()=>{close();throw new Error('simulated close failure')};return store},remove:(target)=>{removed=true;rmSync(target,{recursive:true,force:true})}});expect(removed).toBe(true);expect(readdirSync(temporaryParent)).toEqual([]);expect(result).toMatchObject({status:'failed',code:'cleanup_failed'})})
})
