import { chmodSync,existsSync,mkdtempSync,readdirSync,statSync,truncateSync,writeFileSync } from 'node:fs'
import path from 'node:path'
import { tmpdir } from 'node:os'
import { DatabaseSync } from 'node:sqlite'
import { describe,expect,it } from 'vitest'
import { imageDimensions } from './chat-attachments.js'
import { WorkspaceStore } from './store.js'

function setup(){const root=mkdtempSync(path.join(tmpdir(),'waypoint-chat-attachment-')),database=path.join(root,'waypoint.sqlite'),store=new WorkspaceStore(database),workspace=store.createWorkspace('Private',path.join(root,'workspace')),chat=store.createChat(workspace.id,'Attachments'),message=store.addMessage(workspace.id,chat,'user','Review these files');return{root,database,store,workspace,chat,message}}
function source(root:string,name:string,bytes:string|Uint8Array):string{const file=path.join(root,name);writeFileSync(file,bytes);return file}
const statPermission=(file:string)=>statSync(file).mode&0o777
const chmodDirectory=(file:string,mode:number)=>chmodSync(file,mode)

describe('durable chat attachments',()=>{
  it('persists validated pasted image bytes and reads them back with integrity',()=>{const{store,workspace,chat}=setup(),png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64'),id=store.addAttachmentBytes(workspace.id,chat,'pasted-image.png','image/png',png),read=store.readAttachment(workspace.id,id);expect(read.metadata).toMatchObject({id,ownerId:chat,mediaType:'image/png',bytes:png.length});expect(read.bytes.equals(png)).toBe(true);store.close()})
  it('rejects unsafe image dimensions before decoder allocation',()=>{const oversized=Buffer.alloc(24);Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]).copy(oversized);oversized.writeUInt32BE(16384,16);oversized.writeUInt32BE(16384,20);expect(()=>imageDimensions('image/png',oversized)).toThrow('safe preview limit')})
  it('accepts every explicitly supported opaque binary family without parsing it',()=>{const{root,store,workspace,chat}=setup(),fixtures:Array<[string,string,Uint8Array|string]>=[['image.png','image/png',Uint8Array.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a])],['photo.jpg','image/jpeg',Uint8Array.from([0xff,0xd8,0xff,1])],['photo.jpeg','image/jpeg',Uint8Array.from([0xff,0xd8,0xff,2])],['anim.gif','image/gif','GIF89a'],['image.webp','image/webp',Uint8Array.from([0x52,0x49,0x46,0x46,0,0,0,0,0x57,0x45,0x42,0x50])],['paper.pdf','application/pdf','%PDF-'],['draft.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document','PK\u0003\u0004[Content_Types].xml word/document.xml'],['note.md','text/markdown','markdown'],['note.txt','text/plain','plain']];for(const[name,mime,bytes]of fixtures)store.addAttachment(workspace.id,chat,name,mime,source(root,name,bytes));expect(store.listAttachments(workspace.id,chat).map((item)=>item.name)).toEqual(fixtures.map(([name])=>name));store.close()})
  it('persists traceable chat/message metadata and prepares only truthful provider inputs',()=>{const{root,database,store,workspace,chat,message}=setup(),text=source(root,'context.md','# trusted context'),pdf=source(root,'reference.pdf','%PDF-1.7\nopaque bytes')
    const textId=store.addAttachment(workspace.id,message,'context.md','text/markdown',text),pdfId=store.addAttachment(workspace.id,chat,'reference.pdf','application/pdf',pdf)
    expect(store.listAttachments(workspace.id)).toEqual(expect.arrayContaining([expect.objectContaining({id:textId,ownerId:message,ownerKind:'message',name:'context.md',bytes:17}),expect.objectContaining({id:pdfId,ownerId:chat,ownerKind:'chat',mediaType:'application/pdf'})]))
    expect(store.prepareAttachmentForProvider(workspace.id,textId,{inlineText:true,filePaths:false,acceptedMediaTypes:['text/markdown'],maxBytes:1000})).toMatchObject({kind:'text',text:'# trusted context',sourceAttachmentId:textId})
    expect(store.prepareAttachmentForProvider(workspace.id,pdfId,{inlineText:true,filePaths:false,acceptedMediaTypes:['application/pdf'],maxBytes:1000})).toMatchObject({kind:'unsupported',reason:expect.stringContaining('cannot deliver')})
    expect(store.prepareAttachmentForProvider(workspace.id,pdfId,{inlineText:false,filePaths:true,acceptedMediaTypes:['application/pdf'],maxBytes:1000})).toMatchObject({kind:'path',path:expect.stringContaining(pdfId),sourceAttachmentId:pdfId})
    const attachmentRoot=path.join(root,'attachments');expect(statSync(attachmentRoot).isDirectory()).toBe(true);if(process.platform!=='win32')expect(statPermission(attachmentRoot)).toBe(0o700);store.close();if(process.platform!=='win32')chmodDirectory(attachmentRoot,0o755);const reopened=new WorkspaceStore(database);if(process.platform!=='win32')expect(statPermission(attachmentRoot)).toBe(0o700);expect(reopened.listAttachments(workspace.id)).toHaveLength(2);reopened.close()})

  it('enforces extension, MIME, and signature while leaving file size and count to the selected provider',()=>{const{root,store,workspace,message}=setup(),text=source(root,'plain.txt','plain')
    expect(()=>store.addAttachment(workspace.id,message,'wrong.png','image/png',text)).toThrow('signature')
    expect(()=>store.addAttachment(workspace.id,message,'wrong.txt','application/pdf',text)).toThrow('allowed pair')
    const huge=source(root,'huge.pdf','%PDF-');truncateSync(huge,25*1024*1024+1);expect(()=>store.addAttachment(workspace.id,message,'huge.pdf','application/pdf',huge)).not.toThrow()
    for(let index=0;index<21;index++)store.addAttachment(workspace.id,message,`note-${index}.txt`,'text/plain',text)
    const attachments=store.listAttachments(workspace.id,message);expect(attachments).toHaveLength(22);expect(attachments.find((item)=>item.name==='huge.pdf')).toMatchObject({syncEligible:false,localOnlyReason:'transport_file_size'});expect(attachments.find((item)=>item.name==='note-20.txt')).toMatchObject({syncEligible:false,localOnlyReason:'transport_owner_count'});expect(attachments.filter((item)=>item.syncEligible)).toHaveLength(20);expect(store.syncStatus(workspace.id)).toMatchObject({localOnlyAttachments:2});expect(store.pendingSyncChanges(workspace.id).some((change)=>change.objectKind==='attachment'&&(change.payload as Record<string,unknown>).bytes===25*1024*1024+1)).toBe(false);expect(store.pendingSyncChanges(workspace.id).filter((change)=>change.objectKind==='attachment')).toHaveLength(20);store.queueFullSyncSnapshot(workspace.id);expect(store.pendingSyncChanges(workspace.id).filter((change)=>change.objectKind==='attachment').every((change)=>Number((change.payload as Record<string,unknown>).bytes)<=25*1024*1024)).toBe(true);store.close()})

  it('keeps oversized sent files local and tells cross-device peers what is unavailable',()=>{const{root,store,workspace,chat}=setup(),huge=source(root,'local-only.pdf','%PDF-');truncateSync(huge,25*1024*1024+1);const attachmentId=store.addAttachment(workspace.id,chat,'local-only.pdf','application/pdf',huge),messageId=store.addMessage(workspace.id,chat,'user','Review the attachment',[attachmentId]),mutations=store.pendingSyncChanges(workspace.id),messageMutation=mutations.find((change)=>change.objectId===messageId&&change.objectKind==='message');expect(store.listChats(workspace.id).find((item)=>item.id===chat)?.messages.at(-1)?.body).toBe('Review the attachment');expect(String((messageMutation?.payload as Record<string,unknown>).body)).toContain('stored on the originating device only');expect(String((messageMutation?.payload as Record<string,unknown>).body)).toContain('local-only.pdf');expect(mutations.some((change)=>change.objectId===attachmentId&&change.objectKind==='attachment')).toBe(false);store.queueFullSyncSnapshot(workspace.id);const snapshotMessage=store.pendingSyncChanges(workspace.id).filter((change)=>change.objectId===messageId&&change.objectKind==='message').at(-1);expect(String((snapshotMessage?.payload as Record<string,unknown>).body)).toContain('stored on the originating device only');store.close()})

  it('rejects cross-workspace ownership and lookup',()=>{const{root,store,workspace,message}=setup(),other=store.createWorkspace('Other',path.join(root,'other')),otherChat=store.createChat(other.id,'Other'),text=source(root,'note.txt','note'),attachment=store.addAttachment(workspace.id,message,'note.txt','text/plain',text)
    expect(()=>store.addAttachment(other.id,message,'note.txt','text/plain',text)).toThrow('not found');expect(()=>store.listAttachments(other.id,message)).toThrow('not found');expect(()=>store.prepareAttachmentForProvider(other.id,attachment,{inlineText:true,filePaths:false,acceptedMediaTypes:['text/plain'],maxBytes:10})).toThrow('not found');expect(store.listAttachments(other.id,otherChat)).toEqual([]);store.close()})

  it('rolls database, sync metadata, and copied file back when journaling fails',()=>{const{root,database,store,workspace,message}=setup(),text=source(root,'rollback.txt','rollback'),admin=new DatabaseSync(database);admin.exec("CREATE TRIGGER reject_attachment_sync BEFORE INSERT ON sync_mutations WHEN NEW.object_kind='attachment' BEGIN SELECT RAISE(ABORT,'sync failed'); END;");admin.close()
    expect(()=>store.addAttachment(workspace.id,message,'rollback.txt','text/plain',text)).toThrow('sync failed');expect(store.listAttachments(workspace.id)).toEqual([]);expect(readdirSync(path.join(root,'attachments'))).toEqual([]);expect(store.pendingSyncChanges(workspace.id).some((change)=>change.objectKind==='attachment')).toBe(false);store.close()})

  it('cascade deletes message- and chat-owned files, metadata, and sync heads',()=>{const{root,store,workspace,chat,message}=setup(),image=source(root,'pixel.png',Uint8Array.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,1])),chatFile=store.addAttachment(workspace.id,chat,'pixel.png','image/png',image),messageFile=store.addAttachment(workspace.id,message,'pixel.png','image/png',image),relative=new Map((store.exportWorkspace(workspace.id).objects.attachments as Array<Record<string,unknown>>).map((row)=>[String(row.id),String(row.relative_path)]))
    store.deleteMessage(workspace.id,message);expect(store.listAttachments(workspace.id).map((item)=>item.id)).toEqual([chatFile]);expect(existsSync(path.join(root,'attachments',relative.get(messageFile)!))).toBe(false);expect(store.syncHead(workspace.id,messageFile)).toBeUndefined()
    store.deleteObject(workspace.id,'chat',chat);expect(store.listAttachments(workspace.id)).toEqual([]);expect(existsSync(path.join(root,'attachments',relative.get(chatFile)!))).toBe(false);store.close()})

  it('exports and restores remapped chat/message ownership with integrity',()=>{const{root,store,workspace,chat,message}=setup(),docx=source(root,'draft.docx','PK\u0003\u0004[Content_Types].xml word/document.xml'),text=source(root,'prompt.txt','provider context');store.addAttachment(workspace.id,chat,'draft.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',docx);store.addAttachment(workspace.id,message,'prompt.txt','text/plain',text)
    const archive=store.exportWorkspace(workspace.id),restored=store.restoreWorkspace(archive,'Restored',path.join(root,'restored')),attachments=store.listAttachments(restored.id);expect(attachments.map((item)=>item.ownerKind).sort()).toEqual(['chat','message']);expect(attachments.every((item)=>!([chat,message] as string[]).includes(item.ownerId))).toBe(true);expect(store.prepareAttachmentForProvider(restored.id,attachments.find((item)=>item.mediaType==='text/plain')!.id,{inlineText:true,filePaths:false,acceptedMediaTypes:['text/plain'],maxBytes:100})).toMatchObject({kind:'text',text:'provider context'});store.close()})

  it('detects stored digest corruption before export or provider delivery and journals content-minimized sync metadata',()=>{const{root,store,workspace,message}=setup(),text=source(root,'integrity.txt','original'),id=store.addAttachment(workspace.id,message,'integrity.txt','text/plain',text),archive=store.exportWorkspace(workspace.id),row=(archive.objects.attachments as Array<Record<string,unknown>>).find((item)=>item.id===id)!;writeFileSync(path.join(root,'attachments',String(row.relative_path)),'tampered')
    expect(()=>store.exportWorkspace(workspace.id)).toThrow('integrity');expect(()=>store.prepareAttachmentForProvider(workspace.id,id,{inlineText:true,filePaths:false,acceptedMediaTypes:['text/plain'],maxBytes:100})).toThrow('integrity');const sync=store.pendingSyncChanges(workspace.id).find((change)=>change.objectId===id)!;expect(sync.payload).toMatchObject({id,ownerId:message,name:'integrity.txt',bytes:8});expect(JSON.stringify(sync.payload)).not.toContain('relativePath');store.close()})
})
