import{mkdtempSync}from'node:fs'
import{tmpdir}from'node:os'
import path from'node:path'
import{describe,expect,it}from'vitest'
import{WorkspaceStore}from'./store.js'

describe('cross-workspace rollups',()=>{
  it('shares only explicitly granted summary families with source provenance',()=>{const root=mkdtempSync(path.join(tmpdir(),'waypoint-rollup-')),store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),personal=store.createWorkspace('Personal',root),client=store.createWorkspace('Client',path.join(root,'client')),privateWorkspace=store.createWorkspace('Private',path.join(root,'private'));store.createChat(client.id,'Client secret chat');store.createDocument(client.id,'Sensitive document','raw source body must not cross');store.createMemory(client.id,'Sensitive memory','private body must not cross');store.createMeeting(client.id,'Planning call');store.createChat(privateWorkspace.id,'Never shared');store.setCrossWorkspaceRollupSettings(personal.id,{standingEnabled:true,grants:[{sourceWorkspaceId:client.id,family:'meetings',enabled:true},{sourceWorkspaceId:client.id,family:'briefing_status',enabled:true}]});const result=store.composeCrossWorkspaceRollup(personal.id);expect(result.items).toEqual(expect.arrayContaining([expect.objectContaining({family:'meetings',sourceWorkspaceId:client.id,title:'Planning call'}),expect.objectContaining({family:'briefing_status',sourceWorkspaceId:client.id,counts:expect.objectContaining({chats:1,documents:1,memories:1})})]));expect(JSON.stringify(result)).not.toContain('raw source body');expect(JSON.stringify(result)).not.toContain('private body');expect(JSON.stringify(result)).not.toContain(privateWorkspace.id);expect(()=>store.setCrossWorkspaceRollupSettings(personal.id,{standingEnabled:false,grants:[{sourceWorkspaceId:personal.id,family:'meetings',enabled:true}]})).toThrow('invalid');store.close()})
  it('revokes grants immediately',()=>{const root=mkdtempSync(path.join(tmpdir(),'waypoint-rollup-')),store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),personal=store.createWorkspace('Personal',root),source=store.createWorkspace('Source',path.join(root,'source'));store.createMeeting(source.id,'Granted meeting');store.setCrossWorkspaceRollupSettings(personal.id,{standingEnabled:false,grants:[{sourceWorkspaceId:source.id,family:'meetings',enabled:true}]});expect(store.composeCrossWorkspaceRollup(personal.id).items).toHaveLength(1);store.setCrossWorkspaceRollupSettings(personal.id,{standingEnabled:false,grants:[]});expect(store.composeCrossWorkspaceRollup(personal.id).items).toEqual([]);store.close()})
})
