import {mkdtempSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {DatabaseSync} from 'node:sqlite'
import {describe,expect,it} from 'vitest'
import {WorkspaceStore} from './store.js'

function setup(){const root=mkdtempSync(path.join(tmpdir(),'waypoint-briefing-')),store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),workspace=store.createWorkspace('Personal',root),chat=store.createChat(workspace.id,'Plan');return{root,store,workspace,chat}}
function commitment(store:WorkspaceStore,workspaceId:string,chatId:string){store.addMessage(workspaceId,chatId,'user','I will finish the briefing.');store.scanMemorySuggestions(workspaceId,chatId);const item=store.listMemorySuggestions(workspaceId).find((value)=>value.category==='commitment')!;return String(store.resolveMemorySuggestion(workspaceId,String(item.id),'accept').acceptedObjectId)}

describe('workspace daily briefing',()=>{
  it('composes local sources with provenance, truthful coverage, and workspace isolation',()=>{const{root,store,workspace,chat}=setup(),commitmentId=commitment(store,workspace.id,chat),document=store.createDocument(workspace.id,'Plan','Keep it local'),memoryId=store.createMemory(workspace.id,'Preference','No automatic send'),other=store.createWorkspace('Other',path.join(root,'other')),brief=store.composeDailyBriefing(workspace.id,'America/New_York','2026-08-03T16:00:00Z');expect(brief.items[0].id).toBe(commitmentId);expect(new Set(brief.items.map((item)=>item.id))).toEqual(new Set([commitmentId,memoryId,document.id]));expect(brief.items.every((item)=>item.whyIncluded&&item.updatedAt)).toBe(true);expect(brief.coverage).toMatchObject({openCommitments:1,documents:1,memories:1,dismissed:0,omittedByLimit:0});expect(store.composeDailyBriefing(other.id,'UTC','2026-08-03T16:00:00Z').items).toEqual([]);store.close()})

  it('persists dismissal for one local day and makes it eligible the next day',()=>{const{store,workspace,chat}=setup(),id=commitment(store,workspace.id,chat),first=store.composeDailyBriefing(workspace.id,'UTC','2026-08-03T12:00:00Z');store.dismissBriefingItem(workspace.id,id,'commitment',first.localDay);expect(store.composeDailyBriefing(workspace.id,'UTC','2026-08-03T20:00:00Z')).toMatchObject({items:[],coverage:{dismissed:1}});expect(store.composeDailyBriefing(workspace.id,'UTC','2026-08-04T01:00:00Z').items[0].id).toBe(id);store.close()})

  it('retains a prior local-day dismissal across timezone travel and is activity-idempotent',()=>{const{store,workspace}=setup(),memory=store.createMemory(workspace.id,'Travel','Keep day state'),first=store.composeDailyBriefing(workspace.id,'Pacific/Honolulu','2026-08-04T05:00:00Z');store.dismissBriefingItem(workspace.id,memory,'memory',first.localDay);store.dismissBriefingItem(workspace.id,memory,'memory',first.localDay);store.composeDailyBriefing(workspace.id,'Pacific/Kiritimati','2026-08-04T05:00:00Z');expect(store.composeDailyBriefing(workspace.id,'Pacific/Honolulu','2026-08-04T05:00:00Z').items).toEqual([]);expect(store.listActivity(workspace.id).filter((item)=>item.action==='item.dismissed')).toHaveLength(1);store.close()})

  it('cascades content-minimized dismissal metadata with source deletion',()=>{const{store,workspace}=setup(),memory=store.createMemory(workspace.id,'Private','Sensitive body'),brief=store.composeDailyBriefing(workspace.id,'UTC','2026-08-03T12:00:00Z');store.dismissBriefingItem(workspace.id,memory,'memory',brief.localDay);store.deleteObject(workspace.id,'memory',memory);const raw=new DatabaseSync(store.databasePath),rows=raw.prepare('SELECT * FROM briefing_dismissals WHERE source_id=?').all(memory);raw.close();expect(rows).toEqual([]);store.close()})

  it('cleans a dismissed commitment on direct FK cascade and has the migration index',()=>{const{store,workspace,chat}=setup(),id=commitment(store,workspace.id,chat),brief=store.composeDailyBriefing(workspace.id,'UTC','2026-08-03T12:00:00Z');store.dismissBriefingItem(workspace.id,id,'commitment',brief.localDay);const source=String(store.listCommitments(workspace.id)[0].sourceMessageId),raw=new DatabaseSync(store.databasePath);raw.exec('PRAGMA foreign_keys=ON');raw.prepare('DELETE FROM messages WHERE id=?').run(source);expect(raw.prepare('SELECT * FROM briefing_dismissals WHERE source_id=?').all(id)).toEqual([]);expect(raw.prepare("SELECT name FROM sqlite_master WHERE type='index' AND name='idx_briefing_dismissals_day'").get()).toEqual({name:'idx_briefing_dismissals_day'});raw.close();store.close()})

  it('discloses a document whose current revision is missing',()=>{const{store,workspace}=setup(),document=store.createDocument(workspace.id,'Damaged note','Body'),raw=new DatabaseSync(store.databasePath);raw.exec('PRAGMA foreign_keys=OFF');raw.prepare('DELETE FROM revisions WHERE id=?').run(document.revisionId);raw.close();const brief=store.composeDailyBriefing(workspace.id,'UTC','2026-08-03T12:00:00Z'),item=brief.items.find((value)=>value.id===document.id)!;expect(item).toMatchObject({missingSource:true,detail:''});expect(brief.coverage.missingSources).toBe(1);expect(brief.omissions.join(' ')).toContain('missing its current revision');store.close()})

  it('fails closed for invalid workspace, timezone, day, and cross-workspace dismissal',()=>{const{root,store,workspace}=setup(),memory=store.createMemory(workspace.id,'Fact','Body'),other=store.createWorkspace('Other',path.join(root,'other'));expect(()=>store.composeDailyBriefing('missing','UTC')).toThrow('Workspace');expect(()=>store.composeDailyBriefing(workspace.id,'Bad/Zone')).toThrow('timezone');expect(()=>store.dismissBriefingItem(workspace.id,memory,'memory','tomorrow')).toThrow('day');expect(()=>store.dismissBriefingItem(workspace.id,memory,'memory','2026-99-99')).toThrow('day');expect(()=>store.dismissBriefingItem(other.id,memory,'memory','2026-08-03')).toThrow('source');store.close()})
})
