export const DAILY_BRIEFING_LIMITS={total:50,commitments:30} as const
export type BriefingSourceKind='commitment'|'document'|'memory'
export interface BriefingSource{id:string;kind:BriefingSourceKind;title:string;detail:string;detailTruncated?:boolean;missingSource?:boolean;updatedAt:string}
export interface BriefingItem extends BriefingSource{whyIncluded:string;freshness:'today'|'recent'|'stale'}
export interface DailyBriefing{version:1;generatedAt:string;timezone:string;localDay:string;items:BriefingItem[];coverage:{openCommitments:number;documents:number;memories:number;dismissed:number;missingSources:number;omittedByLimit:number};omissions:string[]}

export function localDayAt(instant:string,timezone:string):string{const date=new Date(instant);if(!Number.isFinite(date.valueOf()))throw new Error('Briefing instant is invalid');try{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),read=(type:string)=>parts.find((part)=>part.type===type)?.value;if(!read('year')||!read('month')||!read('day'))throw new Error();return`${read('year')}-${read('month')}-${read('day')}`}catch{throw new Error('Briefing timezone is invalid')}}

export function composeDailyBriefing(sources:BriefingSource[],dismissed:Set<string>,instant:string,timezone:string):DailyBriefing{const localDay=localDayAt(instant,timezone),generatedAt=new Date(instant).toISOString(),todayUtc=Date.parse(`${localDay}T00:00:00Z`),counts={openCommitments:sources.filter((item)=>item.kind==='commitment').length,documents:sources.filter((item)=>item.kind==='document').length,memories:sources.filter((item)=>item.kind==='memory').length,missingSources:sources.filter((item)=>item.missingSource).length},eligible=sources.filter((item)=>!dismissed.has(`${item.kind}:${item.id}`)),newest=(left:BriefingSource,right:BriefingSource)=>right.updatedAt.localeCompare(left.updatedAt)||left.id.localeCompare(right.id),commitments=eligible.filter((item)=>item.kind==='commitment').sort(newest).slice(0,DAILY_BRIEFING_LIMITS.commitments),knowledge=eligible.filter((item)=>item.kind!=='commitment').sort(newest).slice(0,DAILY_BRIEFING_LIMITS.total-commitments.length),selected=[...commitments,...knowledge],freshness=(updatedAt:string):BriefingItem['freshness']=>{const sourceDay=Date.parse(`${localDayAt(updatedAt,timezone)}T00:00:00Z`),days=Math.round((todayUtc-sourceDay)/86_400_000);return days<=0?'today':days<=7?'recent':'stale'};return{version:1,generatedAt,timezone,localDay,items:selected.map((item)=>({...item,freshness:freshness(item.updatedAt),whyIncluded:item.kind==='commitment'?'Open commitment requiring review':item.kind==='document'?'Local note selected by update order':'Local memory selected by update order'})),coverage:{...counts,dismissed:sources.length-eligible.length,omittedByLimit:eligible.length-selected.length},omissions:['External calendars, email, Teams, DevOps, meetings, and webhooks were not checked.','Recurring schedule state is unavailable in this local-only slice.','Source text is shown as a bounded local excerpt; open the source for full context.','This briefing is a bounded review aid and may be incomplete.']}}
