import {describe,expect,it} from 'vitest'
import {extractSuggestions,SUGGESTION_EXTRACTOR} from './derived-suggestions.js'

describe('local-patterns-v1 derived suggestion fixture',()=>{
  it('extracts explicit commitments, decisions, people, projects, facts, and dates with exact spans',()=>{const body="I will send the draft by 2026-08-10. We decided to use SQLite. Remember that launch is private. Follow up with Alice. Project: Atlas migration.";const values=extractSuggestions('message-fixture-01',body),categories=new Set(values.map((item)=>item.category));expect(categories).toEqual(new Set(['commitment','date','decision','fact','person','project']));for(const item of values){expect(body.slice(item.startOffset,item.endOffset)).toBe(item.sourceExcerpt);expect(item.confidence).toBeGreaterThanOrEqual(SUGGESTION_EXTRACTOR.threshold)}})
  it('does not turn ordinary discussion or assistant hedging into commitments',()=>{expect(extractSuggestions('message-fixture-02','Could this perhaps be useful? The draft seems interesting.')).toEqual([])})
  it('is deterministic, source-bound, and bounded',()=>{const body=Array.from({length:140},(_,index)=>`TODO: item ${index}.`).join(' '),first=extractSuggestions('message-fixture-03',body),second=extractSuggestions('message-fixture-03',body);expect(first).toEqual(second);expect(first).toHaveLength(100);expect(new Set(first.map((item)=>item.fingerprint)).size).toBe(100);expect(extractSuggestions('message-fixture-other',body)[0].fingerprint).not.toBe(first[0].fingerprint)})
  it('keeps the exact displayed source span while normalizing only the candidate body',()=>{const body='  Remember that   backups stay local.  ',item=extractSuggestions('message-fixture-04',body)[0];expect(item.sourceExcerpt).toBe('Remember that   backups stay local.');expect(body.slice(item.startOffset,item.endOffset)).toBe(item.sourceExcerpt);expect(item.body).toBe('Remember that backups stay local.')})
  it('keeps contradictory or updated statements separate for human review',()=>{const items=extractSuggestions('message-fixture-05','I will ship Friday. I will not ship Friday.');expect(items.map((item)=>item.body)).toEqual(['I will ship Friday.','I will not ship Friday.']);expect(new Set(items.map((item)=>item.fingerprint)).size).toBe(2)})
  it('recognizes an explicit commit phrase as a commitment',()=>{expect(extractSuggestions('message-fixture-06','I commit to review the acceptance report tomorrow.')).toEqual([expect.objectContaining({category:'commitment',body:'I commit to review the acceptance report tomorrow.'})])})
})
