import {mkdtempSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {DatabaseSync} from 'node:sqlite'
import {describe,expect,it} from 'vitest'
import {WorkspaceStore} from './store.js'

function setup(){const root=mkdtempSync(path.join(tmpdir(),'waypoint-derived-')),store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),workspace=store.createWorkspace('Personal',root),chat=store.createChat(workspace.id,'Planning');return{root,store,workspace,chat}}

describe('review-first derived knowledge',()=>{
  it('scans idempotently, preserves provenance, and resolves explicitly',()=>{const{store,workspace,chat}=setup();const commitmentMessage=store.addMessage(workspace.id,chat,'user','I will send the roadmap by 2026-08-10.'),factMessage=store.addMessage(workspace.id,chat,'assistant','Remember that the release remains private.');expect(store.scanMemorySuggestions(workspace.id,chat)).toBe(3);expect(store.scanMemorySuggestions(workspace.id,chat)).toBe(0);const suggestions=store.listMemorySuggestions(workspace.id),commitment=suggestions.find((item)=>item.category==='commitment')!,fact=suggestions.find((item)=>item.category==='fact')!,date=suggestions.find((item)=>item.category==='date')!;expect(commitment).toMatchObject({sourceMessageId:commitmentMessage,sourceExcerpt:'I will send the roadmap by 2026-08-10.',extractor:'local-patterns',extractorVersion:'1.0.0'});store.resolveMemorySuggestion(workspace.id,String(date.id),'reject');store.resolveMemorySuggestion(workspace.id,String(commitment.id),'accept',{title:'Send roadmap',body:'Send the reviewed roadmap'});const accepted=store.resolveMemorySuggestion(workspace.id,String(fact.id),'accept');expect(accepted.kind).toBe('memory');expect(store.listCommitments(workspace.id)[0]).toMatchObject({title:'Send roadmap',status:'open',sourceMessageId:commitmentMessage});store.setCommitmentCompleted(workspace.id,String(store.listCommitments(workspace.id)[0].id),true);expect(store.listCommitments(workspace.id)[0].status).toBe('completed');expect(store.listMemorySuggestions(workspace.id)).toEqual([]);expect(store.listMemories(workspace.id)[0]).toMatchObject({sourceObjectId:factMessage,ownership:'workspace-owned'});store.close()})

  it('cascades source-owned commitments and detaches accepted workspace memory on chat deletion',()=>{const{store,workspace,chat}=setup();store.addMessage(workspace.id,chat,'user','I will finish the migration. Remember that backups stay local.');store.scanMemorySuggestions(workspace.id,chat);for(const item of store.listMemorySuggestions(workspace.id))store.resolveMemorySuggestion(workspace.id,String(item.id),'accept');expect(store.listCommitments(workspace.id)).toHaveLength(1);expect(store.listMemories(workspace.id)).toHaveLength(1);store.deleteObject(workspace.id,'chat',chat);expect(store.listCommitments(workspace.id)).toEqual([]);expect(store.listMemorySuggestions(workspace.id)).toEqual([]);expect(store.listMemories(workspace.id)[0]).toMatchObject({sourceObjectId:null,ownership:'workspace-owned'});store.close()})

  it('backs up and restores reviewed suggestions and commitments under fresh identities',()=>{const{root,store,workspace,chat}=setup();store.addMessage(workspace.id,chat,'user','I will test the restore.');store.scanMemorySuggestions(workspace.id,chat);const item=store.listMemorySuggestions(workspace.id)[0];store.resolveMemorySuggestion(workspace.id,String(item.id),'accept');const archive=store.exportWorkspace(workspace.id),restored=store.restoreWorkspace(archive,'Restored',path.join(root,'restored'));expect(restored.id).not.toBe(workspace.id);expect(store.listCommitments(restored.id)).toEqual([expect.objectContaining({body:'I will test the restore.',status:'open'})]);store.close()})
  it('never turns an assistant promise into a user commitment',()=>{const{store,workspace,chat}=setup();store.addMessage(workspace.id,chat,'assistant','I will prepare the answer. Remember that the workspace is local.');store.scanMemorySuggestions(workspace.id,chat);expect(store.listMemorySuggestions(workspace.id).map((item)=>item.category)).toEqual(['fact']);store.close()})

  it('rejects stale provenance and terminal double resolution',()=>{const{store,workspace,chat}=setup(),messageId=store.addMessage(workspace.id,chat,'user','Remember that résumé data stays local.');store.scanMemorySuggestions(workspace.id,chat);const item=store.listMemorySuggestions(workspace.id)[0],database=new DatabaseSync(store.databasePath);database.prepare('UPDATE messages SET body=? WHERE id=?').run('Remember that résumé data may sync.',messageId);database.close();expect(()=>store.resolveMemorySuggestion(workspace.id,String(item.id),'accept')).toThrow('source changed');expect(store.listMemories(workspace.id)).toEqual([]);store.close()})

  it('enforces workspace isolation and terminal review state',()=>{const{store,root,workspace,chat}=setup(),other=store.createWorkspace('Other',path.join(root,'other'));store.addMessage(workspace.id,chat,'user','Remember that the private launch is Friday.');store.scanMemorySuggestions(workspace.id,chat);const item=store.listMemorySuggestions(workspace.id)[0];expect(store.listMemorySuggestions(other.id)).toEqual([]);expect(()=>store.resolveMemorySuggestion(other.id,String(item.id),'accept')).toThrow();store.resolveMemorySuggestion(workspace.id,String(item.id),'reject');expect(()=>store.resolveMemorySuggestion(workspace.id,String(item.id),'accept')).toThrow('Pending suggestion');store.close()})

  it('skips oversized messages and caps the aggregate scan budget',()=>{const{store,workspace,chat}=setup();store.addMessage(workspace.id,chat,'user',`Remember that ${'x'.repeat(100_001)}.`);expect(store.scanMemorySuggestions(workspace.id,chat)).toBe(0);for(let index=0;index<11;index++)store.addMessage(workspace.id,chat,'user',`Remember that item ${index} ${'x'.repeat(99_950)}.`);expect(store.scanMemorySuggestions(workspace.id,chat)).toBeLessThanOrEqual(10);store.close()})

  it('migrates a real schema-8 pending suggestion into a resolvable reviewed item',()=>{const{store,workspace,chat}=setup();store.addMessage(workspace.id,chat,'user','Remember that migration evidence stays local.');store.scanMemorySuggestions(workspace.id,chat);const databasePath=store.databasePath;store.close();const raw=new DatabaseSync(databasePath);raw.exec(`PRAGMA foreign_keys=OFF; DELETE FROM schema_versions WHERE version>=9; CREATE TABLE legacy_suggestions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,chat_id TEXT NOT NULL,source_message_id TEXT NOT NULL,source_role TEXT NOT NULL,category TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,source_excerpt TEXT NOT NULL,start_offset INTEGER NOT NULL,end_offset INTEGER NOT NULL,confidence REAL NOT NULL,extractor TEXT NOT NULL,extractor_version TEXT NOT NULL,fingerprint TEXT NOT NULL UNIQUE,status TEXT NOT NULL,accepted_object_id TEXT,resolved_at TEXT,created_at TEXT NOT NULL); INSERT INTO legacy_suggestions SELECT id,workspace_id,chat_id,source_message_id,source_role,category,title,body,source_excerpt,start_offset,end_offset,confidence,extractor,extractor_version,fingerprint,status,accepted_object_id,resolved_at,created_at FROM memory_suggestions; DROP TABLE memory_suggestions; ALTER TABLE legacy_suggestions RENAME TO memory_suggestions;`);raw.close();const reopened=new WorkspaceStore(databasePath),item=reopened.listMemorySuggestions(workspace.id)[0];expect(reopened.resolveMemorySuggestion(workspace.id,String(item.id),'accept').kind).toBe('memory');reopened.close()})

  it('cascades a direct source-message deletion',()=>{const{store,workspace,chat}=setup(),messageId=store.addMessage(workspace.id,chat,'user','I will remove this source.');store.scanMemorySuggestions(workspace.id,chat);expect(store.listMemorySuggestions(workspace.id)).toHaveLength(1);const raw=new DatabaseSync(store.databasePath);raw.exec('PRAGMA foreign_keys=ON');raw.prepare('DELETE FROM messages WHERE id=?').run(messageId);raw.close();expect(store.listMemorySuggestions(workspace.id)).toEqual([]);expect(store.listCommitments(workspace.id)).toEqual([]);store.close()})
})
