import {mkdtempSync,rmSync,writeFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {createHash} from 'node:crypto'
import {afterEach,describe,expect,it} from 'vitest'
import {WorkspaceStore} from './store.js'
import {archiveIntegrity} from './backup.js'
import {chunkExtractedText} from './document-ingestion.js'

const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true})})
function setup(){const root=mkdtempSync(path.join(tmpdir(),'waypoint-document-index-'));roots.push(root);const store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),workspace=store.createWorkspace('Private',root),body='Waypoint deletion removes every locally derived semantic chunk.',document=store.createDocument(workspace.id,'Imported',body),file=path.join(root,'source.txt');writeFileSync(file,body);const attachmentId=store.addAttachment(workspace.id,document.id,'source.txt','text/plain',file);store.registerDocumentImportSource(workspace.id,{documentId:document.id,revisionId:document.revisionId,attachmentId,sourceDigest:store.listAttachments(workspace.id,document.id)[0].sha256,textDigest:createHash('sha256').update(body).digest('hex'),extractor:'native-text',extractorVersion:'test'});const chunks=chunkExtractedText(body);return{root,store,workspace,document,attachmentId,chunks}}
function index(input:ReturnType<typeof setup>,modelDigest='generation-a',vector=[1,0]){return input.store.replaceDocumentChunkGeneration(input.workspace.id,{documentId:input.document.id,revisionId:input.document.revisionId,attachmentId:input.attachmentId},input.chunks.map((chunk)=>({...chunk,vector})),{provider:'ollama-local',providerVersion:'1',model:'qwen3-embedding:4b',modelDigest})}
describe('production document chunk lifecycle',()=>{
  it('returns matching chunk provenance only inside its workspace',()=>{const input=setup();index(input);expect(input.store.semanticSearch(input.workspace.id,[1,0],{provider:'ollama-local',providerVersion:'1',model:'qwen3-embedding:4b',modelDigest:'generation-a',chunkingDigest:input.chunks[0].policyDigest})[0]).toMatchObject({objectId:input.document.id,revisionId:input.document.revisionId,excerpt:input.chunks[0].text});const other=input.store.createWorkspace('Other',input.root);expect(input.store.semanticSearch(other.id,[1,0],{provider:'ollama-local',providerVersion:'1',model:'qwen3-embedding:4b',modelDigest:'generation-a',chunkingDigest:input.chunks[0].policyDigest})).toEqual([]);input.store.close()})
  it('retains two complete generations, rolls back, and preserves them on rejected replacement',()=>{const input=setup();index(input,'a',[1,0]);index(input,'b',[0,1]);index(input,'c',[1,1]);expect(input.store.semanticSearch(input.workspace.id,[1,0],{provider:'ollama-local',providerVersion:'1',model:'qwen3-embedding:4b',modelDigest:'a',chunkingDigest:input.chunks[0].policyDigest})).toEqual([]);expect(input.store.semanticSearch(input.workspace.id,[0,1],{provider:'ollama-local',providerVersion:'1',model:'qwen3-embedding:4b',modelDigest:'b',chunkingDigest:input.chunks[0].policyDigest})).toHaveLength(1);expect(()=>input.store.replaceDocumentChunkGeneration(input.workspace.id,{documentId:input.document.id,revisionId:input.document.revisionId,attachmentId:input.attachmentId},input.chunks.map((chunk)=>({...chunk,vector:[Number.NaN]})),{provider:'ollama-local',providerVersion:'1',model:'qwen3-embedding:4b',modelDigest:'bad'})).toThrow();expect(input.store.documentIndexStatus(input.workspace.id,input.document.id)).toMatchObject({state:'indexed',modelDigest:'c',retainedGenerations:2});expect(input.store.rollbackDocumentIndex(input.workspace.id,input.document.id)).toMatchObject({state:'indexed',modelDigest:'b',retainedGenerations:1});input.store.close()})
  it('purges chunks on edit and rejects false source provenance before deletion cascades',()=>{const input=setup();index(input);input.store.updateDocument(input.workspace.id,input.document.id,'Edited','new revision');expect(input.store.documentIndexStatus(input.workspace.id,input.document.id)).toMatchObject({state:'not_indexed',sourceAvailable:true});expect(()=>index({...input,document:{...input.document,revisionId:input.store.listDocuments(input.workspace.id)[0].revisionId},chunks:chunkExtractedText('new revision')})).toThrow(/provenance/i);input.store.deleteAttachment(input.workspace.id,input.attachmentId);expect(input.store.documentIndexStatus(input.workspace.id,input.document.id)).toMatchObject({state:'not_indexed',sourceAvailable:false});input.store.deleteObject(input.workspace.id,'document',input.document.id);expect(()=>input.store.documentIndexStatus(input.workspace.id,input.document.id)).toThrow(/not found/i);input.store.close()})
  it('backs up canonical text/source but intentionally rebuilds derived chunks',()=>{const input=setup();index(input);const archive=input.store.exportWorkspace(input.workspace.id),restored=input.store.restoreWorkspace(archive,'Restored',input.root),document=input.store.listDocuments(restored.id)[0];expect(document.body).toContain('derived semantic chunk');expect(input.store.documentIndexStatus(restored.id,document.id)).toMatchObject({state:'not_indexed',sourceAvailable:true,sourceName:'source.txt'});input.store.close()})
  it('rejects archive source provenance corruption even with a recomputed envelope digest',()=>{const input=setup(),archive=input.store.exportWorkspace(input.workspace.id),source=(archive.objects.document_import_sources as Array<Record<string,unknown>>)[0];source.text_digest='0'.repeat(64);archive.integrity=archiveIntegrity({version:archive.version,exportedAt:archive.exportedAt,workspace:archive.workspace,objects:archive.objects});expect(()=>input.store.restoreWorkspace(archive,'Corrupt',input.root)).toThrow(/provenance/i);input.store.close()})
})
