import path from 'node:path'
import {Worker} from 'node:worker_threads'
import type {DocumentChunk,ExtractedDocument} from './document-ingestion.js'
import {DOCUMENT_CHUNKING_POLICY} from './document-ingestion.js'
import {chunkingDigest} from './embedding-benchmark.js'
import {createHash} from 'node:crypto'

export type ExtractionResult=({status:'extracted';fileName:string;mediaType:string;sourceDigest:string;chunks:DocumentChunk[]}&ExtractedDocument)|{status:'failed';code:'extraction_failed'|'busy'|'timed_out';message:string}
let active=false
function failure(code:'extraction_failed'|'busy'|'timed_out'):ExtractionResult{return{status:'failed',code,message:code==='busy'?'Wait for the current local document import to finish.':code==='timed_out'?'Local extraction exceeded two minutes. Try a smaller document.':'Waypoint could not safely extract text from this document. It may be malformed, encrypted, empty, or unsupported.'}}
function sanitize(value:unknown,filePath:string,mediaType:string):ExtractionResult|undefined{if(!value||typeof value!=='object')return;const item=value as Record<string,unknown>;if(item.status==='failed')return failure('extraction_failed');if(item.status!=='extracted'||item.fileName!==path.basename(filePath)||item.mediaType!==mediaType||typeof item.sourceDigest!=='string'||!/^[a-f0-9]{64}$/.test(item.sourceDigest)||typeof item.text!=='string'||!item.text||item.text.length>2_000_000||typeof item.extractor!=='string'||typeof item.extractorVersion!=='string'||!Array.isArray(item.warnings)||!Array.isArray(item.chunks)||!item.chunks.length||item.chunks.length>2_000)return;const chunks=item.chunks as DocumentChunk[],text=item.text,policyDigest=chunkingDigest(DOCUMENT_CHUNKING_POLICY);if(chunks.some((chunk,index)=>chunk.index!==index||chunk.startOffset<0||chunk.endOffset<=chunk.startOffset||text.slice(chunk.startOffset,chunk.endOffset)!==chunk.text||chunk.text.length>DOCUMENT_CHUNKING_POLICY.maxCharacters||chunk.textDigest!==createHash('sha256').update(chunk.text).digest('hex')||chunk.policy!==DOCUMENT_CHUNKING_POLICY.id||chunk.policyVersion!==DOCUMENT_CHUNKING_POLICY.version||chunk.policyDigest!==policyDigest))return;return item as ExtractionResult}
export function extractDocumentOffMain(filePath:string,mediaType:string,deadlineMs=125_000):Promise<ExtractionResult>{if(active)return Promise.resolve(failure('busy'));active=true;return new Promise((resolve)=>{let worker:Worker;try{worker=new Worker(new URL('./document-extraction-worker.js',import.meta.url),{workerData:{filePath,mediaType},resourceLimits:{maxOldGenerationSizeMb:512,stackSizeMb:8}})}catch{active=false;resolve(failure('extraction_failed'));return}let message:ExtractionResult|undefined,settled=false;const finish=async(result:ExtractionResult,terminate=false)=>{if(settled)return;settled=true;clearTimeout(timer);if(terminate)try{await worker.terminate()}catch{/* Return the bounded failure. */}active=false;resolve(result)},timer=setTimeout(()=>void finish(failure('timed_out'),true),deadlineMs);worker.once('message',(value)=>{message=sanitize(value,filePath,mediaType)});worker.once('error',()=>void finish(failure('extraction_failed'),true));worker.once('exit',(code)=>void finish(code===0&&message?message:failure('extraction_failed')))})}
