import {readFileSync} from 'node:fs'
import {describe,expect,it} from 'vitest'
import {chunkExtractedText,extractDocument} from './document-ingestion.js'

function minimalPdf(text:string):Uint8Array{const objects=[`1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n`,`2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n`,`3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n`,`4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n`,`5 0 obj\n<< /Length ${text.length+28} >>\nstream\nBT /F1 12 Tf 72 720 Td (${text}) Tj ET\nendstream\nendobj\n`],header='%PDF-1.4\n',offsets=[0];let body=header;for(const object of objects){offsets.push(body.length);body+=object}const xref=body.length;body+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map((offset)=>String(offset).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(body)}
describe('local document extraction',()=>{
  it('extracts strict text and markdown locally',async()=>{await expect(extractDocument(Buffer.from('local knowledge'),'text/plain')).resolves.toMatchObject({text:'local knowledge',extractor:'native-text'});await expect(extractDocument(Buffer.from('# Heading\nBody'),'text/markdown')).resolves.toMatchObject({text:'# Heading\nBody'})})
  it('extracts a real DOCX without HTML or macros',async()=>{const bytes=readFileSync('node_modules/mammoth/test/test-data/single-paragraph.docx'),result=await extractDocument(bytes,'application/vnd.openxmlformats-officedocument.wordprocessingml.document');expect(result.extractor).toBe('mammoth');expect(result.text.length).toBeGreaterThan(0)})
  it('extracts a real text-bearing PDF',async()=>{await expect(extractDocument(minimalPdf('Waypoint PDF knowledge'),'application/pdf')).resolves.toMatchObject({text:'Waypoint PDF knowledge',extractor:'pdfjs',pages:1})})
  it('fails truthfully for empty, invalid UTF-8, and unapproved types',async()=>{await expect(extractDocument(new Uint8Array(),'text/plain')).rejects.toThrow(/file-size/);await expect(extractDocument(Uint8Array.from([0xff]),'text/plain')).rejects.toThrow(/UTF-8/);await expect(extractDocument(Buffer.from('image'),'image/png')).rejects.toThrow(/no approved/)})
  it('creates exact bounded overlapping chunks with stable provenance',()=>{const text=`First sentence. ${'middle '.repeat(300)}Final sentence.`,chunks=chunkExtractedText(text);expect(chunks.length).toBeGreaterThan(1);for(const chunk of chunks){expect(text.slice(chunk.startOffset,chunk.endOffset)).toBe(chunk.text);expect(chunk.text.length).toBeLessThanOrEqual(1_200);expect(chunk.policy).toBe('document-sentence-window');expect(chunk.textDigest).toMatch(/^[a-f0-9]{64}$/)}})
})
