import {describe,expect,it} from 'vitest'
import {CONSERVATIVE_PROFILE} from './ai-workbench.js'
import {createExecutionBudget,parseExecutionBudget,securityProfileDigest,serializeExecutionBudget} from './execution-budget.js'
const profile={...CONSERVATIVE_PROFILE,roots:['/tmp/workspace']}
const autonomousProfile={...profile,id:'workspace-autonomous-v1',name:'Autonomous developer',filesystem:'workspace-write' as const,tools:['tool-gateway','terminal','local-cli'],approval:'on-write' as const}
describe('conservative execution budgets',()=>{
  it('derives bounded root and child receipts from the trusted profile',()=>{const root=createExecutionBudget({kind:'root',profile,prompt:'hello',attachmentCount:2}),child=createExecutionBudget({kind:'child',profile,prompt:'review',attachmentCount:0});expect(root).toMatchObject({approvalOrigin:'explicit-chat-action',maxOutputBytes:8*1024*1024,maxChildren:1,maxAttempts:1,fallbackAllowed:false,externalCostAllowed:false,peerAllowed:false});expect(child).toMatchObject({approvalOrigin:'explicit-delegate-action',maxDurationMs:60_000,maxOutputBytes:2*1024*1024,maxChildren:0,maxAttachments:0});expect(parseExecutionBudget(serializeExecutionBudget(child))).toEqual(child)})
  it('accepts the exact bounded autonomous profile used by local tool workflows',()=>{expect(createExecutionBudget({kind:'root',profile:autonomousProfile,prompt:'search the workspace',attachmentCount:0})).toMatchObject({maxConcurrency:1,peerAllowed:false,externalCostAllowed:false,profileDigest:securityProfileDigest(autonomousProfile)})})
  it('rejects byte/count and unrecognized widened profile authority',()=>{expect(()=>createExecutionBudget({kind:'child',profile,prompt:'x',attachmentCount:1})).toThrow(/Attachment/);expect(()=>createExecutionBudget({kind:'root',profile,prompt:'🙂'.repeat(600_000),attachmentCount:0})).toThrow(/byte budget/);for(const widened of [{...profile,peerEligible:true},{...profile,tools:['shell']},{...profile,filesystem:'workspace-write' as const},{...autonomousProfile,tools:[...autonomousProfile.tools,'shell']},{...autonomousProfile,maxDurationMs:120_001}])expect(()=>createExecutionBudget({kind:'root',profile:widened,prompt:'x',attachmentCount:0})).toThrow(/boundary/)})
  it('fails closed on corrupt or widened durable receipts',()=>{expect(parseExecutionBudget('{"version":1}')).toBeUndefined();const child=createExecutionBudget({kind:'child',profile,prompt:'x',attachmentCount:0});expect(parseExecutionBudget(JSON.stringify({...child,maxDurationMs:120_000}))).toBeUndefined()})
})
