import {describe,expect,it} from 'vitest'
import {createExecutionBudget,parseExecutionBudget,securityProfileDigest,serializeExecutionBudget} from './execution-budget.js'
const profile={id:'chat-read-only-v1',name:'Chat · read only',roots:['/tmp/workspace'],filesystem:'read-only' as const,network:'provider-only' as const,tools:['provider-native'],approval:'always' as const,maxDurationMs:120_000,maxConcurrency:1,peerEligible:false,secretNames:[]}
const autonomousProfile={...profile,id:'developer-approve-v1',name:'Developer · approve changes',filesystem:'workspace-write' as const,tools:['provider-native','terminal','local-cli','mcp','skills','subagents'],approval:'on-write' as const}
const bypassProfile={...autonomousProfile,id:'bypass-no-prompts-v1',name:'Bypass permissions · no prompts',network:'enabled' as const,tools:[...autonomousProfile.tools,'web','browser','waypoint'],approval:'never' as const}
describe('provider-native execution authority',()=>{
  it('records provider-native prompt, attachment, token, output, and time behavior without Waypoint caps',()=>{const root=createExecutionBudget({kind:'root',profile,prompt:'hello',attachmentCount:21}),child=createExecutionBudget({kind:'child',profile,prompt:'review',attachmentCount:0});expect(root).toMatchObject({version:2,approvalOrigin:'explicit-chat-action',providerNativeLimits:true,maxPromptBytes:0,maxAttachments:0,maxDurationMs:0,maxOutputBytes:0,maxChildren:1,maxAttempts:1,fallbackAllowed:false,externalCostAllowed:false,peerAllowed:false});expect(child).toMatchObject({approvalOrigin:'explicit-delegate-action',providerNativeLimits:true,maxPromptBytes:0,maxDurationMs:0,maxOutputBytes:0,maxChildren:0,maxAttachments:0});expect(parseExecutionBudget(serializeExecutionBudget(child))).toEqual(child)})
  it('accepts the exact bounded developer profile used by rich provider workflows',()=>{expect(createExecutionBudget({kind:'root',profile:autonomousProfile,prompt:'search the workspace',attachmentCount:0})).toMatchObject({maxConcurrency:1,peerAllowed:false,externalCostAllowed:false,profileDigest:securityProfileDigest(autonomousProfile)})})
  it('accepts only the exact explicit no-prompt bypass profile used by native providers',()=>{expect(createExecutionBudget({kind:'root',profile:bypassProfile,prompt:'complete the task',attachmentCount:0})).toMatchObject({providerNativeLimits:true,maxDurationMs:0,maxOutputBytes:0,profileDigest:securityProfileDigest(bypassProfile)});expect(()=>createExecutionBudget({kind:'root',profile:{...bypassProfile,name:'Developer · approve changes'},prompt:'x',attachmentCount:0})).toThrow(/boundary/)})
  it('accepts large provider-native input while rejecting invalid counts and widened profile authority',()=>{expect(()=>createExecutionBudget({kind:'root',profile,prompt:'x',attachmentCount:-1})).toThrow(/invalid/);expect(()=>createExecutionBudget({kind:'root',profile,prompt:'🙂'.repeat(600_000),attachmentCount:21})).not.toThrow();for(const widened of [{...profile,peerEligible:true},{...profile,tools:['shell']},{...profile,filesystem:'workspace-write' as const},{...autonomousProfile,tools:[...autonomousProfile.tools,'shell']},{...autonomousProfile,maxDurationMs:120_001}])expect(()=>createExecutionBudget({kind:'root',profile:widened,prompt:'x',attachmentCount:0})).toThrow(/boundary/)})
  it('fails closed on corrupt or widened durable receipts',()=>{expect(parseExecutionBudget('{"version":1}')).toBeUndefined();const child=createExecutionBudget({kind:'child',profile,prompt:'x',attachmentCount:0});expect(parseExecutionBudget(JSON.stringify({...child,maxDurationMs:120_000}))).toBeUndefined()})
})
