import {describe,expect,it} from 'vitest'
import {CONSERVATIVE_PROFILE} from './ai-workbench.js'
import {createExecutionBudget,parseExecutionBudget,serializeExecutionBudget} from './execution-budget.js'
const profile={...CONSERVATIVE_PROFILE,roots:['/tmp/workspace']}
describe('conservative execution budgets',()=>{
  it('derives bounded root and child receipts from the trusted profile',()=>{const root=createExecutionBudget({kind:'root',profile,prompt:'hello',attachmentCount:2}),child=createExecutionBudget({kind:'child',profile,prompt:'review',attachmentCount:0});expect(root).toMatchObject({approvalOrigin:'explicit-chat-action',maxOutputBytes:8*1024*1024,maxChildren:1,maxAttempts:1,fallbackAllowed:false,externalCostAllowed:false,peerAllowed:false});expect(child).toMatchObject({approvalOrigin:'explicit-delegate-action',maxDurationMs:60_000,maxOutputBytes:2*1024*1024,maxChildren:0,maxAttachments:0});expect(parseExecutionBudget(serializeExecutionBudget(child))).toEqual(child)})
  it('rejects byte/count and widened profile authority',()=>{expect(()=>createExecutionBudget({kind:'child',profile,prompt:'x',attachmentCount:1})).toThrow(/Attachment/);expect(()=>createExecutionBudget({kind:'root',profile,prompt:'🙂'.repeat(600_000),attachmentCount:0})).toThrow(/byte budget/);for(const widened of [{...profile,peerEligible:true},{...profile,tools:['shell']},{...profile,filesystem:'workspace-write' as const}])expect(()=>createExecutionBudget({kind:'root',profile:widened,prompt:'x',attachmentCount:0})).toThrow(/boundary/)})
  it('fails closed on corrupt or widened durable receipts',()=>{expect(parseExecutionBudget('{"version":1}')).toBeUndefined();const child=createExecutionBudget({kind:'child',profile,prompt:'x',attachmentCount:0});expect(parseExecutionBudget(JSON.stringify({...child,maxDurationMs:120_000}))).toBeUndefined()})
})
