import {mkdtempSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {DatabaseSync} from 'node:sqlite'
import {afterEach,describe,expect,it} from 'vitest'
import {WorkspaceStore} from './store.js'
const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true})})
function setup(){const root=mkdtempSync(path.join(tmpdir(),'waypoint-inbound-'));roots.push(root);const store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),workspace=store.createWorkspace('Private',root);return{root,store,workspace}}
describe('quarantined external inbound lifecycle',()=>{
  it('imports idempotently with exact unmatched provenance and workspace isolation',()=>{const{store,workspace,root}=setup(),other=store.createWorkspace('Other',path.join(root,'other')),input={eventId:'external_event_000001',channelId:'external_channel_0001',eventType:'build.completed',occurredAt:new Date().toISOString(),receivedAt:new Date().toISOString(),payload:{result:'ok'}};expect(store.importExternalInboundEvent(workspace.id,input)).toMatchObject({idempotent:false});expect(store.importExternalInboundEvent(workspace.id,input)).toMatchObject({idempotent:true});expect(store.listExternalInboundEvents(workspace.id)).toEqual([expect.objectContaining({eventType:'build.completed',status:'quarantined',runCount:0,runStatus:undefined,payload:{result:'ok'}})]);expect(store.listExternalInboundEvents(other.id)).toEqual([]);store.close()})
  it('recovers a valid six-day-old relay event, isolates local identity, and rejects conflicting duplicate provenance',()=>{const{store,workspace,root}=setup(),other=store.createWorkspace('Other',path.join(root,'other')),receivedAt=new Date(Date.now()-6*86_400_000).toISOString(),input={eventId:'external_event_000003',channelId:'external_channel_0003',eventType:'build.completed',occurredAt:receivedAt,receivedAt,payload:{result:'ok'}};store.importExternalInboundEvent(workspace.id,input);expect(store.listExternalInboundEvents(workspace.id)).toEqual([expect.objectContaining({sourceEventId:input.eventId})]);expect(()=>store.importExternalInboundEvent(workspace.id,{...input,payload:{result:'changed'}})).toThrow(/collision/);store.importExternalInboundEvent(other.id,input);expect(store.listExternalInboundEvents(other.id)[0]).toMatchObject({sourceEventId:input.eventId});expect(store.listExternalInboundEvents(other.id)[0].id).not.toBe(store.listExternalInboundEvents(workspace.id)[0].id);store.close()})
  it('backs up/restores six-day provenance and hard-deletes owned inbound content',()=>{const{store,workspace,root}=setup(),receivedAt=new Date(Date.now()-6*86_400_000).toISOString(),input={eventId:'external_event_000002',channelId:'external_channel_0002',eventType:'build.completed',occurredAt:receivedAt,receivedAt,payload:{result:'ok'}};store.importExternalInboundEvent(workspace.id,input);const restored=store.restoreWorkspace(store.exportWorkspace(workspace.id),'Restored',path.join(root,'restored'));expect(store.listExternalInboundEvents(restored.id)).toEqual([expect.objectContaining({sourceEventId:input.eventId,channelId:input.channelId,payloadDigest:store.listExternalInboundEvents(workspace.id)[0].payloadDigest})]);store.deleteExternalInboundEvent(workspace.id,store.listExternalInboundEvents(workspace.id)[0].id);expect(store.listExternalInboundEvents(workspace.id)).toEqual([]);const raw=new DatabaseSync(store.databasePath);raw.exec('PRAGMA foreign_keys=ON');raw.prepare('DELETE FROM workspaces WHERE id=?').run(restored.id);raw.close();expect(()=>store.listExternalInboundEvents(restored.id)).toThrow();store.close()})
  it('migrates an actual schema-16 workspace into the inbound schema',()=>{const{store,workspace}=setup(),databasePath=store.databasePath;store.close();const raw=new DatabaseSync(databasePath);raw.exec('DELETE FROM schema_versions WHERE version>=17; DROP TABLE external_inbound_events; DROP TABLE tool_gateway_receipts; DROP TABLE tool_gateway_settings;');raw.close();const reopened=new WorkspaceStore(databasePath);reopened.importExternalInboundEvent(workspace.id,{eventId:'external_event_000004',channelId:'external_channel_0004',eventType:'build.completed',occurredAt:new Date().toISOString(),receivedAt:new Date().toISOString(),payload:{result:'ok'}});expect(reopened.listExternalInboundEvents(workspace.id)).toHaveLength(1);reopened.close()})
})
