import{createRequire}from'node:module'
import path from'node:path'
import{fork,type ChildProcess}from'node:child_process'

type Chunk={samples:Float32Array;progress:number}
type Tts={sampleRate:number;numSpeakers:number;generateAsync(input:{text:string;sid:number;speed:number;enableExternalBuffer?:boolean;onProgress:(chunk:Chunk)=>boolean}):Promise<{samples:Float32Array;sampleRate:number}>}
type Factory=(config:Record<string,unknown>)=>Promise<Tts>
export type FastSpeechMetric={firstAudioMs?:number;generationMs:number;sampleRate?:number;sampleCount:number;canceled:boolean}
export function fastSpeechSegments(text:string,max=180){const clean=text.replace(/\s+/g,' ').trim(),result:string[]=[];let pending=clean;while(pending.length){const opening=pending.match(/^.{8,80}?[.!?](?=\s|$)/)?.[0];if(opening&&opening.length<pending.length){result.push(opening);pending=pending.slice(opening.length).trim();continue}if(pending.length<=max){result.push(pending);break}const window=pending.slice(0,max+1),sentence=Math.max(window.lastIndexOf('. '),window.lastIndexOf('! '),window.lastIndexOf('? ')),space=window.lastIndexOf(' '),cut=sentence>8?sentence+1:space>24?space:max;result.push(pending.slice(0,cut).trim());pending=pending.slice(cut).trim()}return result.filter(Boolean)}

const runtimeFactory:Factory=async(config)=>{const require=createRequire(import.meta.url),runtime=require('sherpa-onnx-node')as{OfflineTts:{createAsync(config:Record<string,unknown>):Promise<Tts>}};return runtime.OfflineTts.createAsync(config)}
export class FastLocalSpeechAdapter{
 private engine?:Promise<Tts>;private sequence=0
 constructor(private readonly root:string,private readonly factory:Factory=runtimeFactory,private readonly clock=()=>performance.now()){}
 private load(){return this.engine??=this.factory({model:{kitten:{model:path.join(this.root,'model.fp16.onnx'),voices:path.join(this.root,'voices.bin'),tokens:path.join(this.root,'tokens.txt'),dataDir:path.join(this.root,'espeak-ng-data'),lengthScale:1}},maxNumSentences:1,numThreads:2,provider:'cpu'})}
 async probe(){try{const engine=await this.load();return engine.sampleRate>8_000&&engine.numSpeakers>0}catch{this.engine=undefined;return false}}
 async speak(text:string,onChunk:(samples:Float32Array,sampleRate:number,index:number)=>void):Promise<FastSpeechMetric>{const id=++this.sequence,start=this.clock(),engine=await this.load();let firstAudioMs:number|undefined,sampleCount=0,index=0;const result=await engine.generateAsync({text,sid:0,speed:1,onProgress:(chunk)=>{if(id!==this.sequence)return false;if(chunk.samples.length){firstAudioMs??=Math.max(0,this.clock()-start);sampleCount+=chunk.samples.length;onChunk(new Float32Array(chunk.samples),engine.sampleRate,index++)}return id===this.sequence}});if(id!==this.sequence)return{firstAudioMs,generationMs:Math.max(0,this.clock()-start),sampleRate:engine.sampleRate,sampleCount,canceled:true};if(!sampleCount&&result.samples.length){firstAudioMs??=Math.max(0,this.clock()-start);sampleCount=result.samples.length;onChunk(new Float32Array(result.samples),result.sampleRate,index)}return{firstAudioMs,generationMs:Math.max(0,this.clock()-start),sampleRate:engine.sampleRate,sampleCount,canceled:false}}
 stop(){this.sequence++}
}

type Forker=(modulePath:string,args:string[],options:Parameters<typeof fork>[2])=>ChildProcess
export class FastLocalSpeechProcessAdapter{
 private child?:ChildProcess;private sequence=0;private readiness?:Promise<boolean>
 constructor(private readonly root:string,private readonly workerPath:string,private readonly forker:Forker=fork,private readonly clock=()=>performance.now()){}
 private launch(args:string[]=[]){return this.forker(this.workerPath,[this.root,...args],{stdio:['ignore','ignore','ignore','ipc'],serialization:'advanced',execArgv:[],env:{ELECTRON_RUN_AS_NODE:'1',PATH:process.env.PATH??'',LANG:process.env.LANG??'en_US.UTF-8'}})}
 async probe(){if(this.readiness)return this.readiness;const pending=(()=>{const child=this.launch(['--probe']);return new Promise<boolean>((resolve)=>{let settled=false;const finish=(value:boolean)=>{if(settled)return;settled=true;clearTimeout(timer);if(child.connected)child.disconnect();if(!child.killed)child.kill('SIGTERM');resolve(value)},timer=setTimeout(()=>finish(false),10_000);child.on('message',(value)=>finish((value as{type?:string;ready?:boolean}).type==='probe'&&(value as{ready?:boolean}).ready===true));child.once('error',()=>finish(false));child.once('exit',()=>finish(false))})})();this.readiness=pending;const ready=await pending;if(!ready&&this.readiness===pending)this.readiness=undefined;return ready}
 async speak(text:string,onChunk:(samples:Float32Array,sampleRate:number,index:number)=>void):Promise<FastSpeechMetric>{this.stop();const id=++this.sequence,start=this.clock();let firstAudioMs:number|undefined,sampleCount=0,sampleRate:number|undefined,index=0;for(const segment of fastSpeechSegments(text)){if(id!==this.sequence)return{firstAudioMs,generationMs:Math.max(0,this.clock()-start),sampleRate,sampleCount,canceled:true};const audio=await this.segment(id,segment);if(!audio)return{firstAudioMs,generationMs:Math.max(0,this.clock()-start),sampleRate,sampleCount,canceled:true};firstAudioMs??=Math.max(0,this.clock()-start);sampleRate=audio.sampleRate;sampleCount+=audio.samples.length;onChunk(audio.samples,audio.sampleRate,index++)}return{firstAudioMs,generationMs:Math.max(0,this.clock()-start),sampleRate,sampleCount,canceled:false}}
 private segment(id:number,text:string){const child=this.launch();this.child=child;return new Promise<{samples:Float32Array;sampleRate:number}|undefined>((resolve,reject)=>{let settled=false;const finish=(value:{samples:Float32Array;sampleRate:number}|undefined|Error)=>{if(settled)return;settled=true;if(this.child===child)this.child=undefined;if(child.connected)child.disconnect();if(!child.killed)child.kill('SIGTERM');if(value instanceof Error)reject(value);else resolve(value)};child.on('message',(value)=>{if(id!==this.sequence)return finish(undefined);const message=value as{type?:string;samples?:Float32Array;sampleRate?:number};if(message.type==='audio'&&message.samples instanceof Float32Array&&Number.isInteger(message.sampleRate))finish({samples:new Float32Array(message.samples),sampleRate:message.sampleRate!});else if(message.type==='failed')finish(new Error('voice_tts_failed'))});child.once('spawn',()=>child.send({type:'speak',text}));child.once('error',()=>finish(new Error('voice_tts_failed')));child.once('exit',()=>{if(!settled)finish(id!==this.sequence?undefined:new Error('voice_tts_failed'))})})}
 stop(){this.sequence++;const child=this.child;this.child=undefined;if(child){if(child.connected)child.disconnect();if(!child.killed)child.kill('SIGTERM')}}
}

export class FastLocalTranscriptionProcessAdapter{
 private child?:ChildProcess;private readiness?:Promise<boolean>
 constructor(private readonly root:string,private readonly workerPath:string,private readonly forker:Forker=fork){}
 private launch(args:string[]=[]){return this.forker(this.workerPath,[this.root,...args],{stdio:['ignore','ignore','ignore','ipc'],serialization:'advanced',execArgv:[],env:{ELECTRON_RUN_AS_NODE:'1',PATH:process.env.PATH??'',LANG:process.env.LANG??'en_US.UTF-8'}})}
 async probe(){if(this.readiness)return this.readiness;const pending=this.runProbe();this.readiness=pending;const ready=await pending;if(!ready&&this.readiness===pending)this.readiness=undefined;return ready}
 private runProbe(){const child=this.launch(['--probe']);return new Promise<boolean>((resolve)=>{let settled=false;const finish=(value:boolean)=>{if(settled)return;settled=true;clearTimeout(timer);if(child.connected)child.disconnect();if(!child.killed)child.kill('SIGTERM');resolve(value)},timer=setTimeout(()=>finish(false),15_000);child.on('message',(value)=>finish((value as{type?:string;ready?:boolean}).type==='probe'&&(value as{ready?:boolean}).ready===true));child.once('error',()=>finish(false));child.once('exit',()=>finish(false))})}
 transcribe(audio:Uint8Array,signal?:AbortSignal){this.stop();const child=this.launch();this.child=child;return new Promise<{text:string;provider:'sherpa-whisper'}>((resolve,reject)=>{let settled=false;const finish=(value:{text:string;provider:'sherpa-whisper'}|Error)=>{if(settled)return;settled=true;signal?.removeEventListener('abort',cancel);if(this.child===child)this.child=undefined;if(child.connected)child.disconnect();if(!child.killed)child.kill('SIGTERM');if(value instanceof Error)reject(value);else resolve(value)},cancel=()=>finish(new Error('voice_canceled'));signal?.addEventListener('abort',cancel,{once:true});child.on('message',(value)=>{const message=value as{type?:string;text?:string};if(message.type==='transcript'&&typeof message.text==='string')finish({text:message.text,provider:'sherpa-whisper'});else if(message.type==='failed')finish(new Error('voice_runtime_failed'))});child.once('spawn',()=>child.send({type:'transcribe',audio:new Uint8Array(audio)}));child.once('error',()=>finish(new Error('voice_runtime_failed')));child.once('exit',()=>{if(!settled)finish(signal?.aborted?new Error('voice_canceled'):new Error('voice_runtime_failed'))})})}
 stop(){const child=this.child;this.child=undefined;if(child){if(child.connected)child.disconnect();if(!child.killed)child.kill('SIGTERM')}}
}
