import {mkdtempSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {DatabaseSync} from 'node:sqlite'
import {describe,expect,it} from 'vitest'
import {WorkspaceStore} from './store.js'

function setup(){const root=mkdtempSync(path.join(tmpdir(),'waypoint-rules-')),store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),workspace=store.createWorkspace('Personal',root),chat=store.createChat(workspace.id,'Corrections');return{root,store,workspace,chat}}
function repeated(store:WorkspaceStore,workspaceId:string,chatId:string){const first=store.addMessage(workspaceId,chatId,'user','Always use concise headings.'),second=store.addMessage(workspaceId,chatId,'user','ALWAYS   use concise headings!');store.addMessage(workspaceId,chatId,'assistant','Always use concise headings.');expect(store.scanRuleSuggestions(workspaceId)).toBe(1);return{first,second,item:store.listRuleSuggestions(workspaceId)[0]}}

describe('review-first learned rules',()=>{
  it('requires repeated user directives and preserves exact source provenance',()=>{const{store,workspace,chat}=setup(),{item}=repeated(store,workspace.id,chat);expect(String(item.statement).toLowerCase()).toBe('always use concise headings');expect(item).toMatchObject({scope:'workspace',extractor:'local-directives',extractorVersion:'1.0.0'});expect(item.sources).toHaveLength(2);expect(new Set((item.sources as Array<Record<string,unknown>>).map((source)=>source.excerpt))).toEqual(new Set(['Always use concise headings.','ALWAYS   use concise headings!']));expect(store.scanRuleSuggestions(workspace.id)).toBe(0);store.close()})

  it('requires a current dry run, supports disable and revert, and minimizes outcomes',()=>{const{store,workspace,chat}=setup(),{item}=repeated(store,workspace.id,chat);expect(()=>store.resolveRuleSuggestion(workspace.id,String(item.id),'approve')).toThrow('dry run');expect(store.dryRunRuleSuggestion(workspace.id,String(item.id))).toMatchObject({matchCount:2});store.resolveRuleSuggestion(workspace.id,String(item.id),'approve');let rule=store.listLearnedRules(workspace.id)[0];expect(rule).toMatchObject({version:1,enabled:true,scope:'workspace'});store.setLearnedRuleEnabled(workspace.id,String(rule.id),false);store.revertLearnedRule(workspace.id,String(rule.id));rule=store.listLearnedRules(workspace.id)[0];expect(rule.enabled).toBe(true);expect((rule.outcomes as Array<Record<string,unknown>>).map((outcome)=>outcome.action)).toEqual(['reverted','disabled','approved','dry_run']);expect(JSON.stringify(rule.outcomes)).not.toContain('headings');store.close()})

  it('invalidates changed provenance and cascades rules below two sources',()=>{const{store,workspace,chat}=setup(),{first,item}=repeated(store,workspace.id,chat);store.dryRunRuleSuggestion(workspace.id,String(item.id));store.resolveRuleSuggestion(workspace.id,String(item.id),'approve');const raw=new DatabaseSync(store.databasePath);raw.prepare('UPDATE messages SET body=? WHERE id=?').run('Always use long headings.',first);raw.close();expect(store.listLearnedRules(workspace.id)).toEqual([]);expect(store.listRuleSuggestions(workspace.id)).toEqual([]);store.close()})

  it('merges later supporting sources so one original deletion does not erase a valid rule',()=>{const{store,workspace,chat}=setup(),{first,second,item}=repeated(store,workspace.id,chat);store.dryRunRuleSuggestion(workspace.id,String(item.id));store.resolveRuleSuggestion(workspace.id,String(item.id),'approve');const third=store.addMessage(workspace.id,chat,'user','Always use concise headings.');expect(store.scanRuleSuggestions(workspace.id)).toBe(0);const raw=new DatabaseSync(store.databasePath);expect((raw.prepare('SELECT count(*) count FROM rule_suggestion_sources').get() as {count:number}).count).toBe(3);raw.close();store.deleteMessage(workspace.id,first);expect(store.listLearnedRules(workspace.id)).toHaveLength(1);store.deleteMessage(workspace.id,second);expect(store.listLearnedRules(workspace.id)).toEqual([]);expect(third).toBeTruthy();store.close()})

  it('isolates workspaces and exposes navigable graph relationships',()=>{const{root,store,workspace,chat}=setup(),other=store.createWorkspace('Other',path.join(root,'other')),document=store.createDocument(workspace.id,'Decision','Local'),relationship=store.createRelationship(workspace.id,chat,document.id,'supports');repeated(store,workspace.id,chat);expect(store.listRuleSuggestions(other.id)).toEqual([]);expect(()=>store.dryRunRuleSuggestion(other.id,String(store.listRuleSuggestions(workspace.id)[0].id))).toThrow();expect(store.graph(workspace.id)).toMatchObject({nodes:expect.arrayContaining([expect.objectContaining({id:chat}),expect.objectContaining({id:document.id})]),edges:[expect.objectContaining({id:relationship,type:'supports'})]});expect(store.graph(other.id)).toEqual({nodes:[],edges:[]});store.close()})

  it('backs up and restores approved rules with remapped provenance',()=>{const{root,store,workspace,chat}=setup(),{item}=repeated(store,workspace.id,chat);store.dryRunRuleSuggestion(workspace.id,String(item.id));store.resolveRuleSuggestion(workspace.id,String(item.id),'approve');const restored=store.restoreWorkspace(store.exportWorkspace(workspace.id),'Restored',path.join(root,'restored')),rules=store.listLearnedRules(restored.id);expect(rules).toHaveLength(1);expect(rules[0]).toMatchObject({statement:expect.stringMatching(/concise headings/i),enabled:true,version:1});expect(store.listRuleSuggestions(restored.id)).toEqual([]);store.close()})

  it('migrates an actual schema-10 store with rule tables and invalidation trigger',()=>{const{store}=setup(),databasePath=store.databasePath;store.close();const raw=new DatabaseSync(databasePath);raw.exec('PRAGMA foreign_keys=OFF;DELETE FROM schema_versions WHERE version=11;DROP TABLE rule_outcomes;DROP TABLE learned_rules;DROP TABLE rule_suggestion_sources;DROP TABLE rule_suggestions;');raw.close();const reopened=new WorkspaceStore(databasePath),check=new DatabaseSync(databasePath);expect(check.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='learned_rules'").get()).toEqual({name:'learned_rules'});expect(check.prepare("SELECT name FROM sqlite_master WHERE type='trigger' AND name='invalidate_rule_after_source_delete'").get()).toEqual({name:'invalidate_rule_after_source_delete'});check.close();reopened.close()})
})
