import { chmodSync, existsSync, mkdtempSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { DatabaseSync } from 'node:sqlite'
import { describe, expect, it } from 'vitest'
import { WorkspaceStore } from './store.js'

const png=new Uint8Array(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl1sAAAAASUVORK5CYII=','base64'))
function fixture(){const root=mkdtempSync(path.join(tmpdir(),'waypoint-manual-capture-')),store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),workspace=store.createWorkspace('Capture QA',root);return{root,store,workspace}}

describe('manual screen capture lifecycle',()=>{
  it('persists curated settings and exact capture bytes through read and flatten',()=>{const{root,store,workspace}=fixture(),other=store.createWorkspace('Other',path.join(root,'other'));expect(store.screenCaptureSettings(workspace.id)).toMatchObject({workflow:process.platform==='win32'?'quick':'guided',mode:'region',retentionDays:30,maxCaptures:100});store.setScreenCaptureSettings(workspace.id,{workflow:'guided',mode:'window',shortcut:'CommandOrControl+Shift+9',retentionDays:7,maxCaptures:50});expect(store.screenCaptureSettings(workspace.id)).toMatchObject({workflow:'guided'});const capture=store.createScreenCapture(workspace.id,{title:'Harmless fixture',mode:'window',sourceId:'window:1',sourceName:'Fixture',capturedAt:new Date().toISOString(),width:100,height:80},png);expect(store.listScreenCaptures(workspace.id)).toEqual([expect.objectContaining({id:capture.id,sourceName:'Fixture',flattened:false})]);expect(Buffer.from(store.readScreenCapture(workspace.id,capture.id).dataBase64,'base64')).toEqual(Buffer.from(png));store.updateScreenCapture(workspace.id,capture.id,[],png);expect(Buffer.from(store.readScreenCapture(workspace.id,capture.id).dataBase64,'base64')).toEqual(Buffer.from(png));expect(()=>store.readScreenCapture(other.id,capture.id)).toThrow('not found');store.close()})
  it('creates provenance-bearing chat and knowledge derivatives then cascades their bytes',()=>{const{root,store,workspace}=fixture(),chat=store.createChat(workspace.id,'Screenshot chat'),capture=store.createScreenCapture(workspace.id,{title:'Bug screenshot',mode:'display',sourceId:'screen:1',sourceName:'Display 1',capturedAt:new Date().toISOString(),width:100,height:80},png),chatAttachment=store.addScreenCaptureToChat(workspace.id,capture.id,chat).attachment,knowledge=store.addScreenCaptureToKnowledge(workspace.id,capture.id),paths=[chatAttachment.id,knowledge.attachmentId].map((id)=>path.join(root,'attachments',`${id}-screen-capture.png`));expect(paths.every(existsSync)).toBe(true);expect(store.listDocuments(workspace.id).some((item)=>item.id===knowledge.documentId)).toBe(true);store.deleteScreenCapture(workspace.id,capture.id);expect(paths.every((item)=>!existsSync(item))).toBe(true);expect(store.listDocuments(workspace.id).some((item)=>item.id===knowledge.documentId)).toBe(false);expect(store.listAttachments(workspace.id,chat)).toEqual([]);store.close()})
  it('adds a capture to one queued chat idempotently and preserves it across restart',()=>{const{root,store,workspace}=fixture(),chat=store.createChat(workspace.id,'Durable screenshot'),capture=store.createScreenCapture(workspace.id,{title:'Durable screenshot',mode:'window',sourceId:'window:fixture',sourceName:'Fixture',capturedAt:new Date().toISOString(),width:1,height:1},png),first=store.addScreenCaptureToChat(workspace.id,capture.id,chat),retry=store.addScreenCaptureToChat(workspace.id,capture.id,chat);expect(first.created).toBe(true);expect(retry).toMatchObject({created:false,attachment:{id:first.attachment.id,ownerId:chat,mediaType:'image/png'}});expect(store.listChatAttachments(workspace.id,chat)).toHaveLength(1);store.close();const reopened=new WorkspaceStore(path.join(root,'waypoint.sqlite'));expect(reopened.listChatAttachments(workspace.id,chat)).toEqual([expect.objectContaining({id:first.attachment.id,sha256:first.attachment.sha256})]);reopened.close()})
  it('allows the same capture to be queued again after its prior copy is sent',()=>{const{store,workspace}=fixture(),chat=store.createChat(workspace.id,'Repeat screenshot'),capture=store.createScreenCapture(workspace.id,{title:'Repeat screenshot',mode:'window',sourceId:'window:fixture',sourceName:'Fixture',capturedAt:new Date().toISOString(),width:1,height:1},png),first=store.addScreenCaptureToChat(workspace.id,capture.id,chat);store.addMessage(workspace.id,chat,'user','first',[first.attachment.id]);const second=store.addScreenCaptureToChat(workspace.id,capture.id,chat);expect(second).toMatchObject({created:true,attachment:{ownerId:chat}});expect(second.attachment.id).not.toBe(first.attachment.id);store.close()})
  it('fails closed without duplicate rows or orphan files on invalid chat and write failure',()=>{const{root,store,workspace}=fixture(),chat=store.createChat(workspace.id,'Failure screenshot'),capture=store.createScreenCapture(workspace.id,{title:'Failure screenshot',mode:'window',sourceId:'window:fixture',sourceName:'Fixture',capturedAt:new Date().toISOString(),width:1,height:1},png),attachmentRoot=path.join(root,'attachments');chmodSync(attachmentRoot,0o500);try{expect(()=>store.addScreenCaptureToChat(workspace.id,capture.id,chat)).toThrow();expect(store.listChatAttachments(workspace.id,chat)).toEqual([])}finally{chmodSync(attachmentRoot,0o700)}store.deleteObject(workspace.id,'chat',chat);expect(()=>store.addScreenCaptureToChat(workspace.id,capture.id,chat)).toThrow('not found');store.close()})
  it('enforces retention without periodic or background capture state',()=>{const{store,workspace}=fixture();store.setScreenCaptureSettings(workspace.id,{workflow:'quick',mode:'region',shortcut:'CommandOrControl+Shift+8',retentionDays:7,maxCaptures:10});store.createScreenCapture(workspace.id,{title:'Expired',mode:'region',sourceId:'screen:1',sourceName:'Display',capturedAt:new Date(Date.now()-8*86400000).toISOString(),width:10,height:10},png);expect(store.listScreenCaptures(workspace.id)).toEqual([]);store.close()})

  it('repairs only untouched Windows workflow rows auto-flipped by shipped migration 34',()=>{const{root,store,workspace}=fixture(),chosen=store.createWorkspace('Chosen quick',path.join(root,'chosen'));store.setScreenCaptureSettings(workspace.id,{workflow:'guided',mode:'region',shortcut:'CommandOrControl+Shift+8',retentionDays:30,maxCaptures:100});store.setScreenCaptureSettings(chosen.id,{workflow:'quick',mode:'region',shortcut:'CommandOrControl+Shift+8',retentionDays:30,maxCaptures:100});const databasePath=store.databasePath;store.close();const raw=new DatabaseSync(databasePath);raw.exec("DELETE FROM schema_versions WHERE version IN (38,39);UPDATE schema_versions SET applied_at='2026-08-07T18:00:00.000Z' WHERE version=34");raw.prepare("UPDATE screen_capture_settings SET workflow='quick',updated_at=? WHERE workspace_id=?").run('2026-08-07T17:59:59.000Z',workspace.id);raw.prepare("UPDATE screen_capture_settings SET workflow='quick',updated_at=? WHERE workspace_id=?").run('2026-08-07T18:00:01.000Z',chosen.id);raw.close();const reopened=new WorkspaceStore(databasePath);expect(reopened.screenCaptureSettings(workspace.id).workflow).toBe('guided');expect(reopened.screenCaptureSettings(chosen.id).workflow).toBe('quick');reopened.close()})
  it('backs up and restores local captures with validated provenance and editable layers',()=>{const{root,store,workspace}=fixture();store.setScreenCaptureSettings(workspace.id,{workflow:'guided',mode:'display',shortcut:'CommandOrControl+Alt+8',retentionDays:90,maxCaptures:250});const capture=store.createScreenCapture(workspace.id,{title:'Restore fixture',mode:'display',sourceId:'screen:fixture',sourceName:'Fixture display',capturedAt:new Date().toISOString(),width:100,height:80},png);store.updateScreenCapture(workspace.id,capture.id,[{id:'box',tool:'rectangle',x:1,y:1,width:20,height:10,color:'#ff0000',stroke:2}]);const archive=store.exportWorkspace(workspace.id),restored=store.restoreWorkspace(archive,'Restored captures',path.join(root,'restored'));expect(store.screenCaptureSettings(restored.id)).toMatchObject({workflow:'guided',mode:'display',retentionDays:90,maxCaptures:250});expect(store.listScreenCaptures(restored.id)).toEqual([expect.objectContaining({title:'Restore fixture',sourceName:'Fixture display',layers:[expect.objectContaining({tool:'rectangle'})]})]);store.close()})
})
