import { existsSync, mkdtempSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { WorkspaceStore } from './store.js'

const png=new Uint8Array(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl1sAAAAASUVORK5CYII=','base64'))
function fixture(){const root=mkdtempSync(path.join(tmpdir(),'waypoint-manual-capture-')),store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),workspace=store.createWorkspace('Capture QA',root);return{root,store,workspace}}

describe('manual screen capture lifecycle',()=>{
  it('persists curated settings and exact capture bytes through read and flatten',()=>{const{root,store,workspace}=fixture(),other=store.createWorkspace('Other',path.join(root,'other'));expect(store.screenCaptureSettings(workspace.id)).toMatchObject({workflow:'quick',mode:'region',retentionDays:30,maxCaptures:100});store.setScreenCaptureSettings(workspace.id,{workflow:'guided',mode:'window',shortcut:'CommandOrControl+Shift+9',retentionDays:7,maxCaptures:50});expect(store.screenCaptureSettings(workspace.id)).toMatchObject({workflow:'guided'});const capture=store.createScreenCapture(workspace.id,{title:'Harmless fixture',mode:'window',sourceId:'window:1',sourceName:'Fixture',capturedAt:new Date().toISOString(),width:100,height:80},png);expect(store.listScreenCaptures(workspace.id)).toEqual([expect.objectContaining({id:capture.id,sourceName:'Fixture',flattened:false})]);expect(Buffer.from(store.readScreenCapture(workspace.id,capture.id).dataBase64,'base64')).toEqual(Buffer.from(png));store.updateScreenCapture(workspace.id,capture.id,[],png);expect(Buffer.from(store.readScreenCapture(workspace.id,capture.id).dataBase64,'base64')).toEqual(Buffer.from(png));expect(()=>store.readScreenCapture(other.id,capture.id)).toThrow('not found');store.close()})
  it('creates provenance-bearing chat and knowledge derivatives then cascades their bytes',()=>{const{root,store,workspace}=fixture(),chat=store.createChat(workspace.id,'Screenshot chat'),capture=store.createScreenCapture(workspace.id,{title:'Bug screenshot',mode:'display',sourceId:'screen:1',sourceName:'Display 1',capturedAt:new Date().toISOString(),width:100,height:80},png),chatAttachment=store.addScreenCaptureToChat(workspace.id,capture.id,chat),knowledge=store.addScreenCaptureToKnowledge(workspace.id,capture.id),paths=[chatAttachment,knowledge.attachmentId].map((id)=>path.join(root,'attachments',`${id}-screen-capture.png`));expect(paths.every(existsSync)).toBe(true);expect(store.listDocuments(workspace.id).some((item)=>item.id===knowledge.documentId)).toBe(true);store.deleteScreenCapture(workspace.id,capture.id);expect(paths.every((item)=>!existsSync(item))).toBe(true);expect(store.listDocuments(workspace.id).some((item)=>item.id===knowledge.documentId)).toBe(false);expect(store.listAttachments(workspace.id,chat)).toEqual([]);store.close()})
  it('enforces retention without periodic or background capture state',()=>{const{store,workspace}=fixture();store.setScreenCaptureSettings(workspace.id,{workflow:'quick',mode:'region',shortcut:'CommandOrControl+Shift+8',retentionDays:7,maxCaptures:10});store.createScreenCapture(workspace.id,{title:'Expired',mode:'region',sourceId:'screen:1',sourceName:'Display',capturedAt:new Date(Date.now()-8*86400000).toISOString(),width:10,height:10},png);expect(store.listScreenCaptures(workspace.id)).toEqual([]);store.close()})
  it('backs up and restores local captures with validated provenance and editable layers',()=>{const{root,store,workspace}=fixture();store.setScreenCaptureSettings(workspace.id,{workflow:'guided',mode:'display',shortcut:'CommandOrControl+Alt+8',retentionDays:90,maxCaptures:250});const capture=store.createScreenCapture(workspace.id,{title:'Restore fixture',mode:'display',sourceId:'screen:fixture',sourceName:'Fixture display',capturedAt:new Date().toISOString(),width:100,height:80},png);store.updateScreenCapture(workspace.id,capture.id,[{id:'box',tool:'rectangle',x:1,y:1,width:20,height:10,color:'#ff0000',stroke:2}]);const archive=store.exportWorkspace(workspace.id),restored=store.restoreWorkspace(archive,'Restored captures',path.join(root,'restored'));expect(store.screenCaptureSettings(restored.id)).toMatchObject({workflow:'guided',mode:'display',retentionDays:90,maxCaptures:250});expect(store.listScreenCaptures(restored.id)).toEqual([expect.objectContaining({title:'Restore fixture',sourceName:'Fixture display',layers:[expect.objectContaining({tool:'rectangle'})]})]);store.close()})
})
