import {describe,expect,it,vi} from 'vitest'
import {FetchOpenRouterTransport,OpenRouterClient,decideHostedRoute,openRouterCapability,summarizeUsage,type OpenRouterSettings,type ProviderUsageReceipt} from './openrouter-provider.js'
const settings:OpenRouterSettings={enabled:true,liveRequestsEnabled:true,strategicModel:'moonshot/kimi-k3',everydayModel:'deepseek/v4-flash',fallbackProvider:'codex',monthlyCapMicros:1000,ytdCapMicros:5000,perRequestCapMicros:100,warningPercent:80}
const receipt=(costMicros:number,finishedAt='2026-08-03T12:00:00.000Z'):ProviderUsageReceipt=>({id:`r${costMicros}`,workspaceId:'w1',provider:'openrouter',model:'deepseek/v4-flash',role:'everyday',status:'completed',costMicros,promptTokens:2,completionTokens:3,requestDigest:'a'.repeat(64),startedAt:finishedAt,finishedAt})
describe('OpenRouter provider policy',()=>{
 it('fails truthfully through no-key, activation, model, and cap states',()=>{expect(openRouterCapability(settings,false).state).toBe('no_key');expect(openRouterCapability({...settings,liveRequestsEnabled:false},true).state).toBe('activation_required');expect(openRouterCapability({...settings,strategicModel:''},true).state).toBe('model_required');expect(openRouterCapability(settings,true,summarizeUsage([receipt(1000)],settings,new Date('2026-08-03T12:00:00Z'))).state).toBe('cap_reached')})
 it('aggregates integer cost and uses only an approved subscription fallback at cap',()=>{const summary=summarizeUsage([receipt(800),{...receipt(200),id:'r2',workspaceId:'w2',model:'moonshot/kimi-k3'}],settings,new Date('2026-08-03T12:00:00Z'));expect(summary).toMatchObject({monthMicros:1000,ytdMicros:1000,capReached:true,warning:true});expect(summary.byWorkspace).toHaveLength(2);expect(decideHostedRoute({settings,keyConfigured:true,summary,role:'strategic',availableSubscriptions:['codex']})).toMatchObject({provider:'codex',fallback:true});expect(()=>decideHostedRoute({settings,keyConfigured:true,summary,role:'strategic',availableSubscriptions:['claude']})).toThrow('No eligible')})
 it('uses fixture transport for bounded success and cancellation without a network call',async()=>{const complete=vi.fn(async()=>({responseId:'fixture-1',text:'ok',promptTokens:3,completionTokens:1,costMicros:25})),client=new OpenRouterClient({complete}),controller=new AbortController(),result=await client.run({workspaceId:'w1',role:'everyday',model:'deepseek/v4-flash',prompt:'fixture',apiKey:'not-a-real-key',signal:controller.signal,now:()=> '2026-08-03T12:00:00.000Z'});expect(result.receipt).toMatchObject({status:'completed',costMicros:25});expect(complete).toHaveBeenCalledOnce();const canceled=new AbortController();canceled.abort();const failing=new OpenRouterClient({complete:async()=>{throw new Error('stopped')}});await expect(failing.run({workspaceId:'w1',role:'strategic',model:'moonshot/kimi-k3',prompt:'fixture',apiKey:'x',signal:canceled.signal})).rejects.toMatchObject({message:'provider_canceled',receipt:{status:'canceled'}})})
 it('implements the production contract with an injected fetch and requires provider cost',async()=>{const fetcher=vi.fn(async(_url:unknown,init?:RequestInit)=>{expect(init?.headers).toMatchObject({authorization:'Bearer protected-test-key'});const body=JSON.parse(String(init?.body));expect(body).toMatchObject({max_completion_tokens:4096,provider:{data_collection:'deny',zdr:true}});expect(body.provider.max_price.prompt).toBeGreaterThan(0);return new Response(JSON.stringify({id:'gen-fixture',choices:[{message:{content:'answer'}}],usage:{prompt_tokens:4,completion_tokens:2,cost:0.000123}}),{status:200})}),transport=new FetchOpenRouterTransport(fetcher as typeof fetch),result=await transport.complete({apiKey:'protected-test-key',model:'fixture/model',prompt:'hello',signal:new AbortController().signal,requestCapMicros:100_000});expect(result).toMatchObject({costMicros:123,text:'answer'});expect(fetcher).toHaveBeenCalledOnce();const missing=new FetchOpenRouterTransport((async()=>new Response(JSON.stringify({id:'x',choices:[{message:{content:'x'}}],usage:{prompt_tokens:1,completion_tokens:1}}))) as typeof fetch);await expect(missing.complete({apiKey:'x',model:'fixture/model',prompt:'x',signal:new AbortController().signal,requestCapMicros:100_000})).rejects.toThrow('provider_cost_unavailable')})
 it('fails closed when returned provider cost exceeds the reserved per-request ceiling',async()=>{const client=new OpenRouterClient({complete:async()=>({responseId:'over-cap',text:'answer',promptTokens:1,completionTokens:1,costMicros:101})});await expect(client.run({workspaceId:'w1',role:'everyday',model:'deepseek/v4-flash',prompt:'fixture',apiKey:'fixture-key',signal:new AbortController().signal,requestCapMicros:100})).rejects.toMatchObject({message:'provider_cost_cap_exceeded',receipt:{status:'failed'}})})
})
