import {describe,expect,it} from 'vitest'
import {createLocalEventEnvelope,localTriggerDryRun,suggestedTriggerRule} from './proactive-triggers.js'
const workspaceId='11111111-1111-4111-8111-111111111111',now='2026-08-03T12:00:00.000Z'
describe('local proactive trigger contracts',()=>{
  it('creates bounded authority-free envelopes deterministically',()=>{const event=createLocalEventEnvelope({workspaceId,eventType:'document.imported',idempotencyKey:'fixture-1',payload:{title:'Fixture',count:1},now});expect(event).toMatchObject({schemaVersion:1,source:'webhook.fixture.local',authority:{network:false,publicIngress:false,externalEffects:false,unattended:false}});expect(event.payloadDigest).toMatch(/^[a-f0-9]{64}$/)})
  it('rejects authority-shaped, nested, stale, and oversized payloads',()=>{expect(()=>createLocalEventEnvelope({workspaceId,eventType:'x',idempotencyKey:'1',payload:{action:'send'},now})).toThrow(/schema/);expect(()=>createLocalEventEnvelope({workspaceId,eventType:'x',idempotencyKey:'1',payload:{nested:{} as never},now})).toThrow(/schema/);expect(()=>createLocalEventEnvelope({workspaceId,eventType:'x',idempotencyKey:'1',payload:{value:'x'},occurredAt:'2026-08-01T00:00:00Z',now})).toThrow(/replay/)})
  it('rejects instruction-shaped and non-canonical event types',()=>{for(const eventType of ['Document.Imported','document imported','document.imported\nsend','document..imported','document.imported.'])expect(()=>createLocalEventEnvelope({workspaceId,eventType,idempotencyKey:'1',payload:{value:'x'},now})).toThrow(/identity/)})
  it('rejects non-record and authority-shaped payloads',()=>{for(const payload of [['x'], 'x', {authority:'admin'},{network:true},{publicIngress:true},{unattended:true},{externalEffects:true}])expect(()=>createLocalEventEnvelope({workspaceId,eventType:'document.imported',idempotencyKey:'1',payload:payload as never,now})).toThrow(/schema/)})
  it('binds dry runs to exact rules/events and kill-switch dominance',()=>{const event=createLocalEventEnvelope({workspaceId,eventType:'document.imported',idempotencyKey:'1',payload:{title:'Fixture'},now}),rule=suggestedTriggerRule(workspaceId,event.eventType),input={workspaceId,ruleId:'rule',ruleVersion:1,ruleDigest:rule.digest,eventId:event.id,eventDigest:event.payloadDigest,eventType:event.eventType,definitionJson:JSON.stringify(rule.definition),killSwitch:false};expect(localTriggerDryRun(input)).toMatchObject({status:'dry_run',proposedEffects:0,matched:true});expect(()=>localTriggerDryRun({...input,killSwitch:true})).toThrow(/kill switch/)})
})
