import {mkdtempSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {DatabaseSync} from 'node:sqlite'
import {afterEach,describe,expect,it} from 'vitest'
import {WorkspaceStore} from './store.js'
import {archiveIntegrity} from './backup.js'
const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true})})
function setup(){const root=mkdtempSync(path.join(tmpdir(),'waypoint-trigger-'));roots.push(root);const store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),workspace=store.createWorkspace('Private',root);return{root,store,workspace}}
describe('local proactive trigger lifecycle',()=>{
  it('quarantines fixtures, rejects replay, approves paused, dry-runs idempotently, and obeys kill',()=>{const input=setup(),eventId=input.store.createLocalWebhookFixture(input.workspace.id,'document.imported','fixture-1',{title:'Synthetic'});expect(()=>input.store.createLocalWebhookFixture(input.workspace.id,'document.imported','fixture-1',{title:'Replay'})).toThrow(/replay/);let lab=input.store.listLocalTriggerLab(input.workspace.id);expect(lab).toMatchObject({killSwitch:false,authority:{network:false,publicIngress:false,unattended:false},events:[{id:eventId,status:'quarantined'}],rules:[{status:'suggested'}]});const ruleId=lab.rules[0].id;expect(()=>input.store.dryRunLocalTriggerRule(input.workspace.id,ruleId)).toThrow(/paused/);input.store.approveLocalTriggerRule(input.workspace.id,ruleId);expect(input.store.dryRunLocalTriggerRule(input.workspace.id,ruleId)).toMatchObject({status:'dry_run',proposedEffects:0,idempotent:false});expect(input.store.dryRunLocalTriggerRule(input.workspace.id,ruleId)).toMatchObject({status:'dry_run',idempotent:true});input.store.setLocalTriggerKillSwitch(input.workspace.id,true);expect(()=>input.store.dryRunLocalTriggerRule(input.workspace.id,ruleId)).toThrow(/kill switch/);input.store.setLocalTriggerKillSwitch(input.workspace.id,false);lab=input.store.listLocalTriggerLab(input.workspace.id);expect(lab.rules[0].runs).toHaveLength(1);input.store.close()})
  it('bounds retry/dead-letter, isolates workspaces, and cascades event ownership',()=>{const input=setup(),other=input.store.createWorkspace('Other',input.root);input.store.createLocalWebhookFixture(input.workspace.id,'chat.completed','fixture-2',{count:1});const rule=input.store.listLocalTriggerLab(input.workspace.id).rules[0];input.store.approveLocalTriggerRule(input.workspace.id,rule.id);expect(input.store.dryRunLocalTriggerRule(input.workspace.id,rule.id,true).status).toBe('retrying');expect(input.store.dryRunLocalTriggerRule(input.workspace.id,rule.id,true).status).toBe('retrying');expect(input.store.dryRunLocalTriggerRule(input.workspace.id,rule.id,true).status).toBe('dead_letter');expect(input.store.listLocalTriggerLab(other.id).rules).toEqual([]);input.store.deleteLocalTriggerEvent(input.workspace.id,rule.sourceEventId);expect(input.store.listLocalTriggerLab(input.workspace.id)).toMatchObject({events:[],rules:[]});input.store.close()})
  it('keeps failure retries separate from a successful dry run and idempotently caps dead letters',()=>{const input=setup();input.store.createLocalWebhookFixture(input.workspace.id,'chat.completed','fixture-retry',{count:1});const rule=input.store.listLocalTriggerLab(input.workspace.id).rules[0];input.store.approveLocalTriggerRule(input.workspace.id,rule.id);expect(input.store.dryRunLocalTriggerRule(input.workspace.id,rule.id,true)).toMatchObject({status:'retrying',attempt:1});expect(input.store.dryRunLocalTriggerRule(input.workspace.id,rule.id)).toMatchObject({status:'dry_run',attempt:1,idempotent:false});expect(input.store.dryRunLocalTriggerRule(input.workspace.id,rule.id,true)).toMatchObject({status:'retrying',attempt:2});expect(input.store.dryRunLocalTriggerRule(input.workspace.id,rule.id,true)).toMatchObject({status:'dead_letter',attempt:3,idempotent:false});expect(input.store.dryRunLocalTriggerRule(input.workspace.id,rule.id,true)).toMatchObject({status:'dead_letter',attempt:3,idempotent:true});input.store.close()})
  it('fails closed when stored event or rule provenance is tampered',()=>{const input=setup();input.store.createLocalWebhookFixture(input.workspace.id,'document.imported','fixture-tamper',{title:'Original'});const rule=input.store.listLocalTriggerLab(input.workspace.id).rules[0],raw=new DatabaseSync(input.store.databasePath);raw.prepare("UPDATE local_events SET payload_json='{}' WHERE id=?").run(rule.sourceEventId);raw.close();expect(()=>input.store.listLocalTriggerLab(input.workspace.id)).toThrow(/event provenance/);expect(()=>input.store.approveLocalTriggerRule(input.workspace.id,rule.id)).toThrow(/event provenance/);input.store.close();const second=setup();second.store.createLocalWebhookFixture(second.workspace.id,'document.imported','fixture-rule',{title:'Original'});const secondRule=second.store.listLocalTriggerLab(second.workspace.id).rules[0],rawRule=new DatabaseSync(second.store.databasePath);rawRule.prepare("UPDATE local_trigger_rules SET definition_json='{}' WHERE id=?").run(secondRule.id);rawRule.close();expect(()=>second.store.listLocalTriggerLab(second.workspace.id)).toThrow(/trigger provenance/);expect(()=>second.store.approveLocalTriggerRule(second.workspace.id,secondRule.id)).toThrow(/trigger provenance/);second.store.close()})
  it('fails closed when stored run history provenance is tampered',()=>{const input=setup();input.store.createLocalWebhookFixture(input.workspace.id,'document.imported','fixture-run',{title:'Original'});const rule=input.store.listLocalTriggerLab(input.workspace.id).rules[0];input.store.approveLocalTriggerRule(input.workspace.id,rule.id);input.store.dryRunLocalTriggerRule(input.workspace.id,rule.id);const raw=new DatabaseSync(input.store.databasePath);raw.prepare("UPDATE local_trigger_runs SET attempt=99,run_digest=? WHERE rule_id=?").run('f'.repeat(64),rule.id);raw.close();expect(()=>input.store.listLocalTriggerLab(input.workspace.id)).toThrow(/run provenance/);input.store.close()})
  it('binds stored run history to its rule source event',()=>{const input=setup();input.store.createLocalWebhookFixture(input.workspace.id,'document.imported','fixture-run-a',{title:'A'});const rule=input.store.listLocalTriggerLab(input.workspace.id).rules[0];input.store.approveLocalTriggerRule(input.workspace.id,rule.id);input.store.dryRunLocalTriggerRule(input.workspace.id,rule.id);const otherEvent=input.store.createLocalWebhookFixture(input.workspace.id,'document.imported','fixture-run-b',{title:'B'}),raw=new DatabaseSync(input.store.databasePath);raw.prepare('UPDATE local_trigger_runs SET event_id=? WHERE rule_id=?').run(otherEvent,rule.id);raw.close();expect(()=>input.store.listLocalTriggerLab(input.workspace.id)).toThrow(/run provenance/);input.store.close()})
  it('migrates a real schema-15 store without losing existing workspace data',()=>{const input=setup(),databasePath=input.store.databasePath,workspaceId=input.workspace.id;input.store.createDocument(workspaceId,'Preserved','Before migration');input.store.close();const raw=new DatabaseSync(databasePath);raw.exec('PRAGMA foreign_keys=OFF; DELETE FROM schema_versions WHERE version=16; DROP TABLE local_trigger_runs; DROP TABLE local_trigger_rules; DROP TABLE local_events; DROP TABLE local_trigger_settings;');raw.close();const reopened=new WorkspaceStore(databasePath);expect(reopened.listDocuments(workspaceId)).toEqual([expect.objectContaining({title:'Preserved'})]);reopened.createLocalWebhookFixture(workspaceId,'document.imported','fixture-migrated',{title:'After'});expect(reopened.listLocalTriggerLab(workspaceId).rules).toHaveLength(1);reopened.close()})
  it('backs up, validates, remaps, restores, and rejects tampered trigger authority',()=>{const input=setup();input.store.createLocalWebhookFixture(input.workspace.id,'memory.suggested','fixture-3',{category:'decision'});const rule=input.store.listLocalTriggerLab(input.workspace.id).rules[0];input.store.approveLocalTriggerRule(input.workspace.id,rule.id);input.store.dryRunLocalTriggerRule(input.workspace.id,rule.id);input.store.setLocalTriggerKillSwitch(input.workspace.id,true);const archive=input.store.exportWorkspace(input.workspace.id),restored=input.store.restoreWorkspace(archive,'Restored',input.root),lab=input.store.listLocalTriggerLab(restored.id);expect(lab).toMatchObject({killSwitch:true,events:[{eventType:'memory.suggested'}],rules:[{status:'paused',runs:[{status:'dry_run',proposedEffects:0}]}]});const tampered=structuredClone(archive),event=(tampered.objects.local_events as Array<Record<string,unknown>>)[0];event.authority_json=JSON.stringify({network:true});tampered.integrity=archiveIntegrity({version:tampered.version,exportedAt:tampered.exportedAt,workspace:tampered.workspace,objects:tampered.objects});expect(()=>input.store.restoreWorkspace(tampered,'Bad',input.root)).toThrow(/authority/);input.store.close()})
})
