import {createHash,randomUUID} from 'node:crypto'

export const LOCAL_TRIGGER_LIMITS={maxPayloadBytes:16*1024,maxFields:32,maxEvents:500,maxRules:100,maxRunsPerRule:50,replayWindowMs:24*60*60*1000,maxClockSkewMs:5*60*1000} as const
export const LOCAL_TRIGGER_AUTHORITY={source:'webhook.fixture.local',network:false,publicIngress:false,schedule:false,model:false,externalEffects:false,unattended:false,proposedEffects:0} as const
export type LocalTriggerPayload=Record<string,string|number|boolean|null>
export type LocalEventEnvelope={id:string;schemaVersion:1;workspaceId:string;source:typeof LOCAL_TRIGGER_AUTHORITY.source;eventType:string;occurredAt:string;receivedAt:string;idempotencyKey:string;payload:LocalTriggerPayload;payloadDigest:string;authority:typeof LOCAL_TRIGGER_AUTHORITY}
const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex')
const forbidden=/token|secret|password|authorization|authority|cookie|scope|action|tool|prompt|provider|schedule|send|write|network|public.?ingress|unattended|external.?effects/i
export function createLocalEventEnvelope(input:{workspaceId:string;eventType:string;idempotencyKey:string;payload:LocalTriggerPayload;occurredAt?:string;receivedAt?:string;now?:string}):LocalEventEnvelope{const receivedAt=new Date(input.receivedAt??input.now??new Date().toISOString()),occurredAt=new Date(input.occurredAt??receivedAt.toISOString());if(!/^[0-9a-f-]{36}$/i.test(input.workspaceId)||!/^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/.test(input.eventType)||input.eventType.length>80||!input.idempotencyKey||input.idempotencyKey.length>128)throw new Error('Local event identity is invalid');if(!Number.isFinite(receivedAt.valueOf())||!Number.isFinite(occurredAt.valueOf())||occurredAt.valueOf()>receivedAt.valueOf()+LOCAL_TRIGGER_LIMITS.maxClockSkewMs||occurredAt.valueOf()<receivedAt.valueOf()-LOCAL_TRIGGER_LIMITS.replayWindowMs)throw new Error('Local event timestamp is outside the replay window');if(!input.payload||Array.isArray(input.payload)||Object.getPrototypeOf(input.payload)!==Object.prototype)throw new Error('Local event payload violates the fixture schema');const entries=Object.entries(input.payload);if(entries.length>LOCAL_TRIGGER_LIMITS.maxFields||entries.some(([key,value])=>!key||key.length>80||forbidden.test(key)||!['string','number','boolean'].includes(typeof value)&&value!==null||typeof value==='string'&&value.length>2000||typeof value==='number'&&!Number.isFinite(value)))throw new Error('Local event payload violates the fixture schema');if(Buffer.byteLength(JSON.stringify(input.payload))>LOCAL_TRIGGER_LIMITS.maxPayloadBytes)throw new Error('Local event payload exceeds the local limit');return{id:randomUUID(),schemaVersion:1,workspaceId:input.workspaceId,source:LOCAL_TRIGGER_AUTHORITY.source,eventType:input.eventType,occurredAt:occurredAt.toISOString(),receivedAt:receivedAt.toISOString(),idempotencyKey:input.idempotencyKey,payload:input.payload,payloadDigest:digest(input.payload),authority:LOCAL_TRIGGER_AUTHORITY}}
export function suggestedTriggerRule(workspaceId:string,eventType:string){const definition={schemaVersion:1,workspaceId,eventType,match:'exact-event-type',operation:'local.preview',proposedEffects:0,authority:LOCAL_TRIGGER_AUTHORITY},statement=`When a local ${eventType} fixture is observed, prepare a review preview.`;return{statement,definition,digest:digest({statement,definition})}}
export function localTriggerDryRun(input:{workspaceId:string;ruleId:string;ruleVersion:number;ruleDigest:string;eventId:string;eventDigest:string;eventType:string;definitionJson:string;killSwitch:boolean}){if(input.killSwitch)throw new Error('Workspace automation kill switch is active');const expected=suggestedTriggerRule(input.workspaceId,input.eventType);if(input.ruleVersion!==1||input.ruleDigest!==expected.digest||input.definitionJson!==JSON.stringify(expected.definition))throw new Error('Local trigger definition provenance is invalid');const definition=JSON.parse(input.definitionJson) as Record<string,unknown>;if(definition.workspaceId!==input.workspaceId||definition.eventType!==input.eventType||definition.operation!=='local.preview'||definition.proposedEffects!==0||JSON.stringify(definition.authority)!==JSON.stringify(LOCAL_TRIGGER_AUTHORITY))throw new Error('Local trigger definition does not match the event');const base={schemaVersion:1 as const,workspaceId:input.workspaceId,ruleId:input.ruleId,ruleVersion:input.ruleVersion,ruleDigest:input.ruleDigest,eventId:input.eventId,eventDigest:input.eventDigest,status:'dry_run' as const,matched:true,proposedEffects:0 as const,authority:LOCAL_TRIGGER_AUTHORITY,omissions:['No listener, schedule, account, model, network call, notification, send, write, or unattended action was invoked.']};return{...base,digest:digest(base)}}
