import type {CliCapability,CliName} from '../../spikes/cli-capabilities.js'

export const ROUTING_POLICY_VERSION=1 as const
const registry={
  codex:{provider:'codex' as const,device:'local' as const,privacyClass:'signed-in-cli' as const,costClass:'subscription' as const,mediaTypes:['text/plain','text/markdown','image/png','image/jpeg','image/webp','image/gif'],maxBytes:20*1024*1024},
  claude:{provider:'claude' as const,device:'local' as const,privacyClass:'signed-in-cli' as const,costClass:'subscription' as const,mediaTypes:['text/plain','text/markdown'],maxBytes:512*1024},
}
export interface RouteProposal{version:1;selected?:CliName;eligible:CliName[];fallback:CliName[];fallbackEnabled:boolean;device:'local';securityProfileId:string;explanation:string[];providers:Array<{provider:CliName;eligible:boolean;version?:string;reason?:string;deliverableAttachmentIds:string[];localOnlyAttachmentIds:string[];privacyClass:'signed-in-cli';costClass:'subscription'}>}
export function proposeRoute(input:{capabilities:CliCapability[];preferred:CliName;allowFallback:boolean;securityProfileId:string;attachments:Array<{id:string;mediaType:string;bytes:number}>}):RouteProposal{
  if(!input.securityProfileId)throw new Error('A security profile is required for routing')
  const providers=(['codex','claude'] as const).map((provider)=>{const declared=registry[provider],mediaTypes=declared.mediaTypes as readonly string[],capability=input.capabilities.find((item)=>item.name===provider),eligible=Boolean(capability?.available&&capability.compatible!==false),deliverable=input.attachments.filter((item)=>mediaTypes.includes(item.mediaType)&&item.bytes<=declared.maxBytes).map((item)=>item.id),localOnly=input.attachments.filter((item)=>!mediaTypes.includes(item.mediaType)||item.bytes>declared.maxBytes).map((item)=>item.id);return{provider,eligible,version:capability?.version,reason:eligible?undefined:capability?.compatibilityError||capability?.error||`${provider} CLI is unavailable`,deliverableAttachmentIds:deliverable,localOnlyAttachmentIds:localOnly,privacyClass:declared.privacyClass,costClass:declared.costClass}})
  const eligible=providers.filter((item)=>item.eligible).map((item)=>item.provider),selected=eligible.includes(input.preferred)?input.preferred:input.allowFallback?eligible[0]:undefined,fallback=input.allowFallback&&selected?eligible.filter((item)=>item!==selected):[]
  const explanation=[selected?`Selected ${selected}: explicit local CLI preference is eligible.`:`No eligible route: ${input.preferred} is unavailable or incompatible and fallback is ${input.allowFallback?'exhausted':'disabled'}.`,'Execution device is local; provider privacy class is signed-in CLI; cost class is subscription.',`Security profile ${input.securityProfileId} remains authoritative.`,input.allowFallback?'Fallback is limited to another eligible local signed-in CLI under the same profile.':'Fallback is disabled.']
  return{version:ROUTING_POLICY_VERSION,selected,eligible,fallback,fallbackEnabled:input.allowFallback,device:'local',securityProfileId:input.securityProfileId,explanation,providers}
}
export function assertRoute(proposal:RouteProposal,requested:CliName,profileId:string):void{if(proposal.version!==ROUTING_POLICY_VERSION||proposal.device!=='local'||proposal.securityProfileId!==profileId||proposal.selected!==requested||!proposal.eligible.includes(requested))throw new Error('Requested provider is not eligible under the current routing policy')}
