import { mkdtempSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { WorkspaceStore } from './store.js';

function fixture(){const root=mkdtempSync(path.join(os.tmpdir(),'waypoint-reflection-')),store=new WorkspaceStore(path.join(root,'waypoint.sqlite')),workspace=store.createWorkspace('Reflection',root);return{root,store,workspace}}

describe('workspace reflection proposals',()=>{
  it('creates review-only duplicate proposals with exact provenance and accepts atomically',()=>{const{store,workspace}=fixture(),one=store.createMemory(workspace.id,'Preference','Use concise answers.'),two=store.createMemory(workspace.id,'Preference copy','Use concise answers.');const run=store.createReflectionRun(workspace.id,[one,two]);expect(run.proposalCount).toBe(1);const proposal=store.listReflectionProposals(workspace.id,run.runId)[0];expect(proposal).toMatchObject({kind:'duplicate',status:'proposed',proposedBody:'Use concise answers.'});expect(String(proposal.sourceIds).split(',').sort()).toEqual([one,two].sort());const accepted=store.resolveReflectionProposal(workspace.id,String(proposal.id),'accept')as{memoryId:string};expect(store.listMemories(workspace.id).some((item)=>item.id===accepted.memoryId&&item.ownership==='source-owned')).toBe(true);store.resolveReflectionProposal(workspace.id,String(proposal.id),'rollback');expect(store.listMemories(workspace.id).some((item)=>item.id===accepted.memoryId)).toBe(false);store.close()});
  it('fails closed across workspaces and cascades accepted derivatives with source deletion',()=>{const{store,workspace}=fixture(),other=store.createWorkspace('Other',mkdtempSync(path.join(os.tmpdir(),'waypoint-reflection-other-'))),one=store.createMemory(workspace.id,'A','same'),two=store.createMemory(workspace.id,'B','same'),foreign=store.createMemory(other.id,'Foreign','same');expect(()=>store.createReflectionRun(workspace.id,[one,foreign])).toThrow('outside this workspace');const run=store.createReflectionRun(workspace.id,[one,two]),proposal=store.listReflectionProposals(workspace.id,run.runId)[0],accepted=store.resolveReflectionProposal(workspace.id,String(proposal.id),'accept')as{memoryId:string};store.deleteObject(workspace.id,'memory',one);expect(store.listMemories(workspace.id).some((item)=>item.id===accepted.memoryId)).toBe(false);expect(store.listReflectionRuns(workspace.id)[0].status).toBe('stale');store.close()});
  it('requires an explicit edit for contradictions and revalidates source digests',()=>{const{store,workspace}=fixture(),one=store.createMemory(workspace.id,'Office','Work in Louisville.'),two=store.createMemory(workspace.id,'Office','Work in Boston.'),run=store.createReflectionRun(workspace.id,[one,two]),proposal=store.listReflectionProposals(workspace.id,run.runId)[0];expect(proposal).toMatchObject({kind:'contradiction',proposedBody:''});expect(()=>store.resolveReflectionProposal(workspace.id,String(proposal.id),'accept')).toThrow('body is invalid');expect(store.resolveReflectionProposal(workspace.id,String(proposal.id),'edit','Current office is Louisville; Boston is historical.')).toHaveProperty('memoryId');store.close()});
  it('round-trips runs, proposals, provenance, and accepted revisions through backup restore',()=>{const{store,workspace,root}=fixture(),one=store.createMemory(workspace.id,'Preference','Use concise answers.'),two=store.createMemory(workspace.id,'Preference copy','Use concise answers.'),run=store.createReflectionRun(workspace.id,[one,two],'codex'),proposal=store.listReflectionProposals(workspace.id,run.runId)[0];store.resolveReflectionProposal(workspace.id,String(proposal.id),'accept');const archive=store.exportWorkspace(workspace.id),restored=store.restoreWorkspace(archive,'Restored reflection',path.join(root,'restored'));const restoredRun=store.listReflectionRuns(restored.id)[0],restoredProposal=store.listReflectionProposals(restored.id,String(restoredRun.id))[0];expect(restoredRun).toMatchObject({provider:'codex',status:'accepted'});expect(restoredProposal).toMatchObject({kind:'duplicate',status:'accepted'});expect(String(restoredProposal.sourceDigests).split(',')).toHaveLength(2);expect(store.listMemories(restored.id).some((item)=>item.id===restoredProposal.acceptedObjectId)).toBe(true);store.close()});
  it('enforces strict CLI proposal schema and truthful terminal lifecycle',()=>{const{store,workspace}=fixture(),source=store.createMemory(workspace.id,'Old claim','Review this claim.'),run=store.createReflectionRun(workspace.id,[source],'codex');store.markReflectionRunReviewing(workspace.id,run.runId);expect(store.listReflectionRuns(workspace.id)[0].status).toBe('reviewing');expect(()=>store.applyReflectionCliAnalysis(workspace.id,run.runId,'codex','1.0',[{kind:'rule',title:'Wrong object',beforeBody:'x',proposedBody:'y',rationale:'z',sourceIds:[source]}])).toThrow('authority');expect(()=>store.applyReflectionCliAnalysis(workspace.id,run.runId,'codex','1.0',[{kind:'stale',title:'Review',beforeBody:'x',proposedBody:'y',rationale:'z',sourceIds:[source],unknown:true}])).toThrow('schema');store.failReflectionRun(workspace.id,run.runId,'cancelled','user canceled');expect(store.listReflectionRuns(workspace.id)[0]).toMatchObject({status:'cancelled'});expect(store.listReflectionProposals(workspace.id,run.runId)).toEqual([]);store.close()});
  it('reconciles a reviewing run to failed after an application restart',()=>{const root=mkdtempSync(path.join(os.tmpdir(),'waypoint-reflection-restart-')),database=path.join(root,'waypoint.sqlite'),first=new WorkspaceStore(database),workspace=first.createWorkspace('Restart',root),source=first.createMemory(workspace.id,'Source','Body'),run=first.createReflectionRun(workspace.id,[source],'codex');first.markReflectionRunReviewing(workspace.id,run.runId);first.close();const reopened=new WorkspaceStore(database),restored=reopened.listReflectionRuns(workspace.id)[0];expect(restored.status).toBe('failed');expect(String(restored.omissionsJson)).toContain('Interrupted by application restart');reopened.close()});
});
