import { mkdtempSync, writeFileSync, existsSync, renameSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { DatabaseSync } from 'node:sqlite'
import { WorkspaceStore } from './store.js'

function fixture() {
  const root = mkdtempSync(path.join(tmpdir(), 'waypoint-store-'))
  const database = path.join(root, 'workspace.sqlite')
  const store = new WorkspaceStore(database)
  const workspace = store.createWorkspace('Personal', root)
  return { root, database, store, workspace }
}

const provenance = { provider: 'test', providerVersion: '1', model: 'fixture', modelDigest: 'digest', chunkingDigest: 'chunks-v1' }

describe('durable local workspace', () => {
  it('migrates the pre-ownership memory schema without positional column corruption', () => {
    const root = mkdtempSync(path.join(tmpdir(), 'waypoint-old-schema-')), database = path.join(root, 'workspace.sqlite')
    const legacy = new DatabaseSync(database)
    legacy.exec('CREATE TABLE memories(id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, source_object_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)')
    legacy.close()
    const store = new WorkspaceStore(database), workspace = store.createWorkspace('Migrated', root)
    const memoryId = store.createMemory(workspace.id, 'After migration', 'Body')
    expect(store.listMemories(workspace.id)).toEqual([expect.objectContaining({ id: memoryId, ownership: 'workspace-owned' })])
    store.close()
  })
  it('survives close and reopen with traceable text and semantic search', () => {
    const { database, store, workspace } = fixture()
    const document = store.createDocument(workspace.id, 'Deletion rules', 'Vectors and attachments disappear with their source document.')
    store.indexEmbedding(workspace.id, { objectId: document.id, objectKind: 'document', revisionId: document.revisionId }, [1, 0, 0], provenance)
    expect(store.searchText(workspace.id, 'attachments')[0]).toMatchObject({ objectId: document.id, revisionId: document.revisionId, method: 'text' })
    expect(store.semanticSearch(workspace.id, [.9, .1, 0], provenance)[0]).toMatchObject({ objectId: document.id, revisionId: document.revisionId, method: 'semantic' })
    expect(store.semanticSearch(workspace.id, [.9, .1, 0], { ...provenance, modelDigest: 'new-model-generation' })).toEqual([])
    store.close()
    const reopened = new WorkspaceStore(database)
    expect(reopened.searchText(workspace.id, 'attachments')[0].objectId).toBe(document.id)
    expect(reopened.semanticSearch(workspace.id, [1, 0, 0], provenance)[0].objectId).toBe(document.id)
    reopened.close()
  })

  it('persists chats, messages, memories and navigable typed graph edges', () => {
    const { store, workspace } = fixture()
    const document = store.createDocument(workspace.id, 'Routing', 'Show the selected execution device.')
    const chat = store.createChat(workspace.id, 'Routing discussion')
    store.addMessage(workspace.id, chat, 'user', 'Which device ran this task?')
    const memory = store.createMemory(workspace.id, 'Visible agency', 'Always expose execution provenance.', document.id)
    store.createRelationship(workspace.id, document.id, memory, 'supports')
    store.createRelationship(workspace.id, chat, memory, 'discusses')
    const graph = store.graph(workspace.id)
    expect(graph.nodes.map((node) => node.kind).sort()).toEqual(['chat', 'document', 'memory'])
    expect(graph.edges).toHaveLength(2)
    expect(store.searchText(workspace.id, 'device')).toHaveLength(2)
    store.close()
  })

  it('accepts only explicit text attachment types and stores by generated path', () => {
    const { root, store, workspace } = fixture()
    const document = store.createDocument(workspace.id, 'Attached', 'A source file follows.')
    const source = path.join(root, 'source.md')
    writeFileSync(source, '# Durable source')
    const attachmentId = store.addAttachment(workspace.id, document.id, 'source.md', 'text/markdown', source)
    expect(attachmentId).toBeTruthy()
    expect(store.counts().attachments).toBe(1)
    expect(() => store.addAttachment(workspace.id, document.id, 'image.png', 'image/png', source)).toThrow(/Unsupported/)
    store.close()
  })

  it('cascade-deletes a document, derived data, edges, attachments and queued indexes without leaking content into activity', () => {
    const { root, store, workspace } = fixture()
    const document = store.createDocument(workspace.id, 'Secret title', 'secret-body-needle')
    const memory = store.createMemory(workspace.id, 'Related', 'Safe memory')
    store.createRelationship(workspace.id, document.id, memory, 'supports')
    store.indexEmbedding(workspace.id, { objectId: document.id, objectKind: 'document', revisionId: document.revisionId }, [1, 0], provenance)
    const source = path.join(root, 'owned.txt'); writeFileSync(source, 'secret-attachment-needle')
    store.addAttachment(workspace.id, document.id, 'owned.txt', 'text/plain', source)
    store.deleteObject(workspace.id, 'document', document.id)
    const counts = store.counts()
    expect(counts).toMatchObject({ documents: 0, revisions: 0, relationships: 0, attachments: 0, embeddings: 0, search_fts: 1, tombstones: 1 })
    expect(store.searchText(workspace.id, 'secret')).toEqual([])
    expect(JSON.stringify(store.listActivity(workspace.id))).not.toContain('secret-body-needle')
    expect(JSON.stringify(store.listActivity(workspace.id))).not.toContain('secret-attachment-needle')
    expect(store.graph(workspace.id).edges).toEqual([])
    expect(existsSync(path.join(root, 'attachments'))).toBe(true)
    store.close()
  })

  it('cascades source-owned memories and detaches workspace-owned memories when a source is deleted', () => {
    const { store, workspace } = fixture()
    const document = store.createDocument(workspace.id, 'Source', 'Body')
    const retained = store.createMemory(workspace.id, 'Retained', 'Workspace knowledge', document.id)
    const dependent = store.createMemory(workspace.id, 'Dependent', 'Source knowledge', document.id, 'source-owned')
    store.createRelationship(workspace.id, document.id, retained, 'supports')
    store.createRelationship(workspace.id, document.id, dependent, 'supports')
    store.deleteObject(workspace.id, 'document', document.id)
    expect(store.listMemories(workspace.id)).toEqual([expect.objectContaining({ id: retained, ownership: 'workspace-owned', sourceObjectId: null })])
    expect(store.counts()).toMatchObject({ memories: 1, relationships: 0, tombstones: 2 })
    store.close()
  })

  it('cascade-deletes chat messages and their full-text entries', () => {
    const { store, workspace } = fixture()
    const chat = store.createChat(workspace.id, 'Disposable chat')
    const message = store.addMessage(workspace.id, chat, 'user', 'ephemeral-message-needle')
    const memory = store.createMemory(workspace.id, 'Related memory', 'Remains')
    store.createRelationship(workspace.id, message, memory, 'mentions')
    store.indexEmbedding(workspace.id, { objectId: message, objectKind: 'message' }, [1, 0], provenance)
    store.deleteObject(workspace.id, 'chat', chat)
    expect(store.counts()).toMatchObject({ chats: 0, messages: 0, relationships: 0, embeddings: 0, search_fts: 1, tombstones: 1 })
    expect(store.searchText(workspace.id, 'ephemeral')).toEqual([])
    store.close()
  })

  it('never returns text or semantic results from another workspace', () => {
    const { root, store, workspace } = fixture()
    const other = store.createWorkspace('Other', path.join(root, 'other'))
    const hidden = store.createDocument(other.id, 'Private elsewhere', 'cross-workspace-needle')
    store.indexEmbedding(other.id, { objectId: hidden.id, objectKind: 'document', revisionId: hidden.revisionId }, [1, 0], provenance)
    expect(store.searchText(workspace.id, 'cross-workspace')).toEqual([])
    expect(store.semanticSearch(workspace.id, [1, 0], provenance)).toEqual([])
    expect(() => store.indexEmbedding(workspace.id, { objectId: hidden.id, objectKind: 'document' }, [1, 0], provenance)).toThrow(/not found in workspace/)
    expect(() => store.deleteObject(workspace.id, 'document', hidden.id)).toThrow(/not found in workspace/)
    const local = store.createMemory(workspace.id, 'Local', 'Only here')
    expect(() => store.createRelationship(workspace.id, hidden.id, local, 'crosses')).toThrow(/not found in workspace/)
    expect(() => store.updateDocument(workspace.id, hidden.id, 'Changed', 'Changed')).toThrow(/not found in workspace/)
    expect(() => store.createMemory(workspace.id, 'Leaky source', 'No', hidden.id)).toThrow(/not found in workspace/)
    const otherChat = store.createChat(other.id, 'Other chat')
    expect(() => store.addMessage(workspace.id, otherChat, 'user', 'No')).toThrow(/not found in workspace/)
    expect(store.searchText(other.id, 'cross-workspace')).toHaveLength(1)
    store.close()
  })

  it('round-trips representative authored data into new object identities and rebuilds indexes', () => {
    const { root, store, workspace } = fixture()
    const document = store.createDocument(workspace.id, 'Exported note', 'restore-search-needle')
    const chat = store.createChat(workspace.id, 'Exported chat')
    store.addMessage(workspace.id, chat, 'assistant', 'restored-message-needle')
    const memory = store.createMemory(workspace.id, 'Exported memory', 'remember this', document.id)
    store.createRelationship(workspace.id, document.id, memory, 'supports')
    store.indexEmbedding(workspace.id, { objectId: document.id, objectKind: 'document', revisionId: document.revisionId }, [1, 0], provenance)
    const attachmentSource = path.join(root, 'exported.md'); writeFileSync(attachmentSource, '# restored attachment')
    store.addAttachment(workspace.id, document.id, 'exported.md', 'text/markdown', attachmentSource)
    const deleted = store.createDocument(workspace.id, 'Deleted before export', 'Gone')
    store.deleteObject(workspace.id, 'document', deleted.id)
    const originalActivityCount = store.listActivity(workspace.id).length
    const archive = store.exportWorkspace(workspace.id)
    const restored = store.restoreWorkspace(archive, 'Restored', path.join(root, 'restored'))
    expect(restored.id).not.toBe(workspace.id)
    expect(store.searchText(workspace.id, 'restore-search')).toHaveLength(1)
    expect(store.searchText(restored.id, 'restore-search')).toHaveLength(1)
    expect(store.searchText(workspace.id, 'restored-message')).toHaveLength(1)
    expect(store.searchText(restored.id, 'restored-message')).toHaveLength(1)
    expect(store.graph(restored.id)).toMatchObject({ edges: [{ type: 'supports' }] })
    expect(store.counts().embeddings).toBe(1)
    expect(store.counts().attachments).toBe(2)
    expect(store.counts().tombstones).toBe(2)
    expect(store.listActivity(restored.id)).toHaveLength(originalActivityCount + 1)
    expect(store.listActivity(restored.id).some((event) => event.action === 'workspace.restored')).toBe(true)
    store.close()
  })

  it('rolls back a failed relationship transaction without activity residue', () => {
    const { store, workspace } = fixture()
    const document = store.createDocument(workspace.id, 'One', 'Body')
    const memory = store.createMemory(workspace.id, 'Two', 'Body')
    store.createRelationship(workspace.id, document.id, memory, 'supports')
    const before = store.counts()
    expect(() => store.createRelationship(workspace.id, document.id, memory, 'supports')).toThrow()
    expect(store.counts()).toEqual(before)
    store.close()
  })

  it('captures initial chats and connected memories as atomic logical operations', () => {
    const { store, workspace } = fixture()
    const document = store.createDocument(workspace.id, 'Source', 'Body')
    store.captureChat(workspace.id, 'Atomic chat', 'First message')
    store.captureMemory(workspace.id, 'Atomic memory', 'Connected', document.id)
    expect(store.counts()).toMatchObject({ chats: 1, messages: 1, memories: 1, relationships: 1 })
    const before = store.counts()
    expect(() => store.captureChat('missing-workspace', 'No chat', 'No message')).toThrow()
    expect(() => store.captureMemory(workspace.id, 'No memory', 'No relation', 'missing-source')).toThrow()
    expect(store.counts()).toEqual(before)
    store.close()
  })

  it('rolls back the workspace and copied files when archive restore integrity fails', () => {
    const { root, store, workspace } = fixture()
    const document = store.createDocument(workspace.id, 'Archive', 'Body')
    const source = path.join(root, 'archive.txt'); writeFileSync(source, 'valid bytes')
    store.addAttachment(workspace.id, document.id, 'archive.txt', 'text/plain', source)
    const archive = structuredClone(store.exportWorkspace(workspace.id))
    ;(archive.objects.attachments[0] as Record<string, unknown>).data_base64 = Buffer.from('tampered').toString('base64')
    const before = store.counts()
    expect(() => store.restoreWorkspace(archive, 'Broken restore', path.join(root, 'broken'))).toThrow(/integrity/)
    expect(store.counts()).toEqual(before)
    store.close()
  })

  it('reconciles interrupted attachment add/delete states on startup', () => {
    const { root, database, store, workspace } = fixture()
    const document = store.createDocument(workspace.id, 'Recovery', 'Body')
    const source = path.join(root, 'recover.txt'); writeFileSync(source, 'recoverable')
    store.addAttachment(workspace.id, document.id, 'recover.txt', 'text/plain', source)
    const archive = store.exportWorkspace(workspace.id), relative = String((archive.objects.attachments[0] as Record<string, unknown>).relative_path)
    const attached = path.join(root, 'attachments', relative), staged = `${attached}.deleting-00000000-0000-4000-8000-000000000000`
    renameSync(attached, staged)
    writeFileSync(path.join(root, 'attachments', 'orphan.txt'), 'incomplete add')
    store.close()
    const reopened = new WorkspaceStore(database)
    expect(existsSync(attached)).toBe(true)
    expect(existsSync(staged)).toBe(false)
    expect(existsSync(path.join(root, 'attachments', 'orphan.txt'))).toBe(false)
    reopened.close()
  })
})
