import {EventEmitter} from 'node:events'
import {mkdtempSync,symlinkSync,writeFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {PassThrough} from 'node:stream'
import {describe,expect,it,vi} from 'vitest'
import {AiWaypointControlBridge,ToolGateway,discoverLocalCli,policyDigest,redactToolText,type ToolGatewayHooks,type ToolGatewayPolicy,type ToolResult} from './tool-gateway.js'

class FakeChild extends EventEmitter{stdout=new PassThrough();stderr=new PassThrough();stdin=new PassThrough();killed:string[]=[];kill(signal?:NodeJS.Signals){this.killed.push(signal??'SIGTERM');queueMicrotask(()=>this.emit('close',null,signal??'SIGTERM'));return true}}
const root=()=>{const value=mkdtempSync(path.join(tmpdir(),'waypoint-tools-'));writeFileSync(path.join(value,'safe.txt'),'hello');return value}
const policy=(workspaceRoot:string,override:Partial<ToolGatewayPolicy>={}):ToolGatewayPolicy=>({profileName:'Autonomous developer',roots:[workspaceRoot],denyPatterns:[],stopped:false,secretNames:['MY_TOKEN'],maxDurationMs:1000,maxConcurrency:1,suppressCommit:false,suppressPush:false,...override})
const request=(workspaceId:string,tool:'workspace.list_files'|'workspace.read_file'|'terminal.run'|'local_cli.run'|'waypoint.command',args:Record<string,unknown>,origin:'ui'|'ai'='ui')=>({version:1 as const,workspaceId,origin,tool,arguments:args})
function setup(child=new FakeChild()){const completed:ToolResult[]=[],progress:unknown[]=[],domain=vi.fn(async(_workspaceId:string,command:string)=>({value:{command},summary:`Ran ${command}`,rollbackRef:'undo-1'})),hooks:ToolGatewayHooks={domain,progress:(value)=>progress.push(value),complete:(value)=>completed.push(value)},gateway=new ToolGateway(hooks,(()=>child) as never);return{gateway,child,completed,progress,domain}}

describe('generic tool gateway',()=>{
  it('uses identical domain command semantics for UI and AI while blocking AI security settings',async()=>{const directory=root(),{gateway,domain}=setup(),ui=await gateway.execute(request('workspace_one','waypoint.command',{command:'chat.create',input:{title:'x'}},'ui'),policy(directory)),ai=await gateway.execute(request('workspace_one','waypoint.command',{command:'chat.create',input:{title:'x'}},'ai'),policy(directory));expect(ui.result?.receipt.summary).toBe(ai.result?.receipt.summary);expect(domain).toHaveBeenCalledTimes(2);const blocked=await gateway.execute(request('workspace_one','waypoint.command',{command:'security.profile.update'},'ai'),policy(directory));expect(blocked.result?.receipt).toMatchObject({status:'denied',code:'user_only_command'})})
  it('keeps file reads and listings inside the canonical root and records symlink escapes as terminal failures',async()=>{const directory=root(),outside=root();writeFileSync(path.join(outside,'secret.txt'),'no');symlinkSync(outside,path.join(directory,'escape'));const{gateway}=setup(),listed=await gateway.execute(request('workspace_one','workspace.list_files',{path:'.'}),policy(directory)),read=await gateway.execute(request('workspace_one','workspace.read_file',{path:'safe.txt'}),policy(directory));expect(listed.result?.value).toEqual(expect.arrayContaining([expect.objectContaining({name:'safe.txt'})]));expect(read.result?.output).toBe('hello');const escaped=await gateway.execute(request('workspace_one','workspace.read_file',{path:'escape/secret.txt'}),policy(directory));expect(escaped.result?.receipt).toMatchObject({status:'failed',code:'tool_error'})})
  it('redacts secrets and stable policy receipts never include configured secret values',()=>{const input='Authorization: Bearer abc.def\npassword=hunter2\nMY_TOKEN=topsecret\nhttps://u:p@example.test\n-----BEGIN PRIVATE KEY-----\nsecret\n-----END PRIVATE KEY-----';const output=redactToolText(input,['MY_TOKEN']);expect(output).not.toMatch(/abc\.def|hunter2|topsecret|u:p|BEGIN PRIVATE/);expect(output).toMatch(/REDACTED/);expect(policyDigest(policy(root()))).toMatch(/^[a-f0-9]{64}$/)})
  it('enforces deny patterns, secret dumps, task suppressions, PR and deployment authority',async()=>{const directory=root(),{gateway}=setup();for(const [command,code]of [['rm -rf build','deny_list'],['printenv','secret_environment'],['git commit -m x','task_suppressed_commit'],['gh pr create','explicit_authority_required'],['terraform apply','explicit_authority_required']] as const){const active=policy(directory,{denyPatterns:['rm\\s+-rf'],suppressCommit:true}),result=await gateway.execute(request('workspace_one','terminal.run',{command}),active);expect(result.result?.receipt).toMatchObject({status:'denied',code})}})
  it('streams bounded safe progress, completes, cancels, and honors stop without crossing workspaces',async()=>{const directory=root(),first=setup(),pending=await first.gateway.execute(request('workspace_one','terminal.run',{command:'printf ok'}),policy(directory));first.child.stdout.write('password=hunter2\nok');first.child.emit('close',0,null);await new Promise((resolve)=>setImmediate(resolve));expect(first.completed.at(-1)?.receipt.status).toBe('completed');expect(JSON.stringify(first.progress)).not.toContain('hunter2');const second=setup(),run=await second.gateway.execute(request('workspace_one','terminal.run',{command:'sleep 10'}),policy(directory));expect(second.gateway.cancel('workspace_two',run.runId)).toBe(false);expect(second.gateway.cancel('workspace_one',run.runId)).toBe(true);await new Promise((resolve)=>setImmediate(resolve));expect(second.completed.at(-1)?.receipt.status).toBe('canceled');first.gateway.stop('workspace_one');const stopped=await first.gateway.execute(request('workspace_one','terminal.run',{command:'true'}),policy(directory));expect(stopped.result?.receipt.code).toBe('workspace_stopped');expect(pending.runId).toBeTruthy()})
  it('enforces per-workspace concurrency, valid timeout budgets, and local CLI capability bounds',async()=>{const directory=root(),{gateway,child}=setup();await gateway.execute(request('workspace_one','terminal.run',{command:'sleep 10'}),policy(directory));const concurrent=await gateway.execute(request('workspace_one','terminal.run',{command:'echo no'}),policy(directory));expect(concurrent.result?.receipt.code).toBe('concurrency_limit');const invalid=await gateway.execute(request('workspace_two','terminal.run',{command:'echo no',timeoutMs:10}),policy(directory));expect(invalid.result?.receipt.code).toBe('invalid_timeout');child.emit('close',0,null);const unsupported=await gateway.execute(request('workspace_one','local_cli.run',{cli:'powershell',args:[]}),policy(directory));expect(unsupported.result?.receipt.code).toBe('unsupported_cli');expect(discoverLocalCli('git')).toMatchObject({name:'git',authentication:'existing-local-identity'})})
  it('fails closed for unknown tools and requires an interactive user origin for inherited local execution',async()=>{const directory=root(),{gateway}=setup(),unknown=await gateway.execute({...request('workspace_one','terminal.run',{command:'true'}),tool:'not.a.tool'} as never,policy(directory)).catch((error:Error)=>error);expect(unknown).toBeInstanceOf(Error);const terminal=await gateway.execute(request('workspace_one','terminal.run',{command:'python -c "print(1)"'},'ai'),policy(directory)),cli=await gateway.execute(request('workspace_one','local_cli.run',{cli:'gh',args:['api','user']},'ai'),policy(directory));expect(terminal.result?.receipt.code).toBe('interactive_local_execution_required');expect(cli.result?.receipt.code).toBe('interactive_local_execution_required')})
  it('redacts secrets split across output chunks before any content is exposed',async()=>{const directory=root(),{gateway,child,completed,progress}=setup();await gateway.execute(request('workspace_one','terminal.run',{command:'printf safe'}),policy(directory));child.stdout.write('pass');child.stdout.write('word=hunter2');child.emit('close',0,null);await new Promise((resolve)=>setImmediate(resolve));expect(completed.at(-1)?.output).not.toContain('hunter2');expect(JSON.stringify(progress)).not.toContain('hunter2')})
  it('provides a domain-only trusted-main AI bridge and terminal receipts for thrown operations',async()=>{const directory=root(),configured=policy(directory),{gateway,domain,completed}=setup(),bridge=new AiWaypointControlBridge(gateway,()=>configured),domainResult=await bridge.execute('workspace_one','chat.create',{title:'x'});expect(domainResult.result?.receipt).toMatchObject({origin:'ai',tool:'waypoint.command',status:'completed'});expect(domain).toHaveBeenCalled();const failingHooks:ToolGatewayHooks={domain:async()=>{throw new Error('domain exploded')},progress:()=>{},complete:(value)=>completed.push(value)},failing=new ToolGateway(failingHooks,(()=>{throw new Error('spawn exploded')}) as never),domainFailure=await failing.execute(request('workspace_one','waypoint.command',{command:'chat.create'},'ai'),configured),spawnFailure=await failing.execute(request('workspace_one','terminal.run',{command:'true'}),configured);expect(domainFailure.result?.receipt).toMatchObject({status:'failed',code:'tool_error'});expect(spawnFailure.result?.receipt).toMatchObject({status:'failed',code:'tool_error'});expect(completed.at(-1)?.receipt.status).toBe('failed')})
})
