import{createHash}from'node:crypto';import{mkdtempSync,mkdirSync,readdirSync,readFileSync,rmSync,symlinkSync,writeFileSync}from'node:fs';import os from'node:os';import path from'node:path';import{describe,expect,it}from'vitest';import{fixtureVoiceMetrics,verifyVoicePack,VoicePackManager,type VoicePackManifest}from'./voice-engine.js'
const body=Buffer.from('bounded local engine fixture'),digest=createHash('sha256').update(body).digest('hex');function manifest():VoicePackManifest{return{schemaVersion:1,kind:'fixture',engine:'full_duplex_experimental',version:'fixture-1',platform:'darwin',arch:'arm64',packageBytes:body.length,minimumRamBytes:16*1024**3,conversationOwner:'minicpm-o-4.5',components:[{role:'runtime',path:'bin/engine',bytes:body.length,sha256:digest,license:'MIT',source:'https://example.invalid/pinned-fixture'}]}}
describe('voice pack lifecycle',()=>{
 it('stages and verifies a fixture without ever making the experimental engine selectable',()=>{const root=mkdtempSync(path.join(os.tmpdir(),'waypoint-voice-pack-')),manager=new VoicePackManager(root,'darwin','arm64'),installed=manager.installFixture(manifest(),{'bin/engine':body});expect(installed).toMatchObject({ready:false,version:'fixture-1',conversationOwner:'minicpm-o-4.5',reason:expect.stringContaining('Fixture')});expect(readFileSync(path.join(root,'full_duplex_experimental/current/bin/engine'))).toEqual(body);manager.remove('full_duplex_experimental');expect(manager.status('full_duplex_experimental').ready).toBe(false)})
 it('resumes a digest-bound interrupted staging install without exposing it as ready',()=>{const root=mkdtempSync(path.join(os.tmpdir(),'waypoint-voice-resume-')),manager=new VoicePackManager(root,'darwin','arm64'),pack=manifest();expect(()=>manager.installFixture(pack,{'bin/engine':body},{interruptAfter:1})).toThrow('interrupted');expect(readdirSync(path.join(root,'full_duplex_experimental')).some(item=>item.startsWith('.staging-'))).toBe(true);expect(manager.installFixture(pack,{'bin/engine':body})).toMatchObject({ready:false,version:'fixture-1'})})
 it('rejects symlinked trusted roots and engine anchors before any cleanup or write',()=>{const parent=mkdtempSync(path.join(os.tmpdir(),'waypoint-voice-root-')),outside=mkdtempSync(path.join(os.tmpdir(),'waypoint-voice-outside-')),root=path.join(parent,'packs');symlinkSync(outside,root,process.platform==='win32'?'junction':'dir');const manager=new VoicePackManager(root,'darwin','arm64');expect(manager.status('full_duplex_experimental')).toMatchObject({ready:false,reason:expect.stringContaining('security')});expect(()=>manager.installFixture(manifest(),{'bin/engine':body})).toThrow('root')})
 it('fails closed on tampering, traversal, extra files, platform mismatch, and symlinks',()=>{const root=mkdtempSync(path.join(os.tmpdir(),'waypoint-voice-pack-bad-')),pack=manifest();mkdirSync(path.join(root,'bin'));writeFileSync(path.join(root,'manifest.json'),JSON.stringify(pack));writeFileSync(path.join(root,'bin/engine'),body);expect(()=>verifyVoicePack(root,{...pack,platform:'win32'},'darwin','arm64')).toThrow('platform');writeFileSync(path.join(root,'extra'),'unexpected');expect(()=>verifyVoicePack(root,pack,'darwin','arm64')).toThrow('unexpected');rmSync(path.join(root,'extra'));writeFileSync(path.join(root,'bin/engine'),'tampered');expect(()=>verifyVoicePack(root,pack,'darwin','arm64')).toThrow('integrity');const linkRoot=mkdtempSync(path.join(os.tmpdir(),'waypoint-voice-link-'));writeFileSync(path.join(linkRoot,'manifest.json'),JSON.stringify(pack));symlinkSync(path.join(root,'bin'),path.join(linkRoot,'bin'),process.platform==='win32'?'junction':'dir');expect(()=>verifyVoicePack(linkRoot,pack,'darwin','arm64')).toThrow('component');expect(()=>verifyVoicePack(root,{...pack,components:[{...pack.components[0],path:'../escape'}]},'darwin','arm64')).toThrow('manifest')})
 it('records deterministic interactive metrics and rejects post-cancel chunks',()=>{expect(fixtureVoiceMetrics([{atMs:240,durationMs:80},{atMs:320,durationMs:80}])).toMatchObject({firstAudioMs:240,turnEndMs:400,fixture:true});expect(fixtureVoiceMetrics([{atMs:200,durationMs:80}],300,360)).toMatchObject({interruptionMs:60});expect(()=>fixtureVoiceMetrics([{atMs:200,durationMs:80},{atMs:400,durationMs:80}],300,360)).toThrow('leaked')})
})
