import{createHash}from'node:crypto';import{EventEmitter}from'node:events';import{chmodSync,existsSync,mkdtempSync,mkdirSync,readFileSync,symlinkSync,writeFileSync}from'node:fs';import os from'node:os';import path from'node:path';import{describe,expect,it,vi}from'vitest';import{MAX_VOICE_AUDIO_BYTES,NativeSpeechAdapter,VoiceRuntimeRegistry,type BundledVoiceRuntime}from'./voice-runtime.js'
function fixture(){const root=mkdtempSync(path.join(os.tmpdir(),'waypoint-voice-runtime-')),binary=path.join(root,'whisper-cli'),model=path.join(root,'model.gguf'),config=path.join(root,'voice.json');writeFileSync(binary,'fixture');chmodSync(binary,0o700);writeFileSync(model,Buffer.alloc(2048));return{root,binary,model,config}}
function bundledFixture(){const value=fixture(),framework=path.join(value.root,'whisper.framework');writeFileSync(framework,'framework');const hash=(file:string)=>createHash('sha256').update(readFileSync(file)).digest('hex');return{value,bundled:{binaryPath:value.binary,modelPath:value.model,frameworkPath:framework,binarySha256:hash(value.binary),modelSha256:hash(value.model),frameworkSha256:hash(framework),label:'base.en q5_1'}satisfies BundledVoiceRuntime}}
describe('VoiceRuntimeRegistry',()=>{
 it('auto-selects an intact bundled runtime without legacy configuration',async()=>{const{value,bundled}=bundledFixture(),runner=vi.fn(async(_file:string,args:string[])=>{const output=args[args.indexOf('-of')+1];writeFileSync(`${output}.txt`,' bundled words ');return{stdout:'',stderr:''}}),runtime=new VoiceRuntimeRegistry(value.config,'darwin',runner,bundled,'arm64');expect(runtime.capability().stt).toMatchObject({available:true,source:'bundled',model:'base.en q5_1'});await expect(runtime.transcribe(new Uint8Array([82,73,70,70]))).resolves.toMatchObject({text:'bundled words'});expect(existsSync(value.config)).toBe(false)})
 it('fails closed when a bundled file does not match its pinned digest',()=>{const{value,bundled}=bundledFixture();writeFileSync(value.model,Buffer.alloc(2048,1));const runtime=new VoiceRuntimeRegistry(value.config,'darwin',undefined,bundled,'arm64');expect(runtime.capability().stt).toMatchObject({available:false,reason:expect.stringContaining('integrity')})})
 it('reports the bundled framework unavailable before its minimum macOS version',()=>{const{value,bundled}=bundledFixture(),runtime=new VoiceRuntimeRegistry(value.config,'darwin',undefined,bundled,'arm64','13.2.1');expect(runtime.capability().stt).toMatchObject({available:false,reason:expect.stringContaining('13.3')})})
 it('is truthful until explicit compatible local configuration and never stores audio in config',async()=>{const value=fixture(),runner=vi.fn(async()=>({stdout:'whisper.cpp CLI',stderr:''})),runtime=new VoiceRuntimeRegistry(value.config,'darwin',runner);expect(runtime.capability()).toMatchObject({stt:{available:false},tts:{available:true},rawAudioPersistence:false,cloudSpeech:false});await runtime.configure(value.binary,value.model);expect(runtime.capability().stt.available).toBe(true);expect(readFileSync(value.config,'utf8')).not.toContain('audio')})
 it('uses an ephemeral bounded wav and removes it after successful transcription',async()=>{const value=fixture(),runner=vi.fn(async(_file:string,args:string[])=>{if(args[0]==='--help')return{stdout:'whisper.cpp CLI',stderr:''};const output=args[args.indexOf('-of')+1];mkdirSync(path.dirname(output),{recursive:true});writeFileSync(`${output}.txt`,' local words ');return{stdout:'',stderr:''}}),runtime=new VoiceRuntimeRegistry(value.config,'darwin',runner);await runtime.configure(value.binary,value.model);await expect(runtime.transcribe(new Uint8Array([82,73,70,70]))).resolves.toMatchObject({text:'local words',provider:'whisper.cpp'});const call=runner.mock.calls.find((entry)=>entry[1].includes('-f'))!,audio=call[1][call[1].indexOf('-f')+1];expect(()=>readFileSync(audio)).toThrow();await expect(runtime.transcribe(new Uint8Array(MAX_VOICE_AUDIO_BYTES+1))).rejects.toThrow('voice_audio_size_invalid')})
 it('removes ephemeral audio on runner failure and reports missing runtime',async()=>{const value=fixture(),runner=vi.fn(async(_file:string,args:string[])=>{if(args[0]==='--help')return{stdout:'whisper.cpp',stderr:''};throw new Error('bad runtime')}),runtime=new VoiceRuntimeRegistry(value.config,'darwin',runner);await runtime.configure(value.binary,value.model);await expect(runtime.transcribe(new Uint8Array([1]))).rejects.toThrow('bad runtime');runtime.remove();await expect(runtime.transcribe(new Uint8Array([1]))).rejects.toThrow('voice_stt_unavailable')})
 it('rejects an incompatible executable before persisting configuration',async()=>{const value=fixture(),runtime=new VoiceRuntimeRegistry(value.config,'darwin',async()=>({stdout:'unrelated tool',stderr:''}));await expect(runtime.configure(value.binary,value.model)).rejects.toThrow('voice_runtime_incompatible');expect(runtime.capability().stt.available).toBe(false)})
 it('cleans crash residue on startup and rejects symlinked runtime paths',async()=>{const value=fixture(),stale=path.join(value.root,'voice-ephemeral','turn-stale');mkdirSync(stale,{recursive:true});writeFileSync(path.join(stale,'turn.wav'),'raw microphone fixture');const runtime=new VoiceRuntimeRegistry(value.config,'darwin',async()=>({stdout:'whisper.cpp',stderr:''}));expect(existsSync(stale)).toBe(false);const link=path.join(value.root,'linked-whisper');symlinkSync(value.binary,link);await expect(runtime.configure(link,value.model)).rejects.toThrow('voice_runtime_path_invalid')})
})
describe('NativeSpeechAdapter',()=>{it('suppresses stale completion and terminates speech on barge-in',()=>{const children:Array<EventEmitter&{killed:boolean;kill:ReturnType<typeof vi.fn>}>=[],launch=vi.fn(()=>{const child=Object.assign(new EventEmitter(),{killed:false,kill:vi.fn()});children.push(child);return child})as never,tts=new NativeSpeechAdapter('darwin',launch),first=vi.fn(),second=vi.fn();tts.speak('first',first);tts.speak('second',second);expect(children[0].kill).toHaveBeenCalledWith('SIGTERM');children[0].emit('exit',0,null);expect(first).not.toHaveBeenCalled();tts.stop();expect(children[1].kill).toHaveBeenCalledWith('SIGTERM')})})
