import{randomUUID}from'node:crypto';import{accessSync,constants,lstatSync,mkdirSync,mkdtempSync,readFileSync,renameSync,rmSync,writeFileSync}from'node:fs';import path from'node:path';import{execFile,spawn,type ChildProcess}from'node:child_process'
export const MAX_VOICE_AUDIO_BYTES=32*1024*1024
export type VoiceRuntimeConfig={version:1;binaryPath:string;modelPath:string;configuredAt:string}
export type VoiceCapability={stt:{available:boolean;provider:'whisper.cpp';reason:string;binaryPath?:string;modelPath?:string};tts:{available:boolean;provider:'macos-say'|'unavailable';reason:string};rawAudioPersistence:false;cloudSpeech:false}
type Runner=(file:string,args:string[],options:{timeout:number;maxBuffer:number;signal?:AbortSignal})=>Promise<{stdout:string;stderr:string}>
const defaultRunner:Runner=(file,args,options)=>new Promise((resolve,reject)=>execFile(file,args,{timeout:options.timeout,maxBuffer:options.maxBuffer,signal:options.signal,encoding:'utf8'},(error,stdout,stderr)=>error?reject(error):resolve({stdout,stderr})))
function regular(pathname:string){const stat=lstatSync(pathname);if(!stat.isFile()||stat.isSymbolicLink())throw new Error('voice_runtime_path_invalid');return stat}
export class VoiceRuntimeRegistry{
 private readonly ephemeralRoot:string
 constructor(private readonly configPath:string,private readonly platform=process.platform,private readonly runner:Runner=defaultRunner){this.ephemeralRoot=path.join(path.dirname(configPath),'voice-ephemeral');rmSync(this.ephemeralRoot,{recursive:true,force:true});mkdirSync(this.ephemeralRoot,{recursive:true,mode:0o700})}
 async configure(binaryPath:string,modelPath:string){binaryPath=path.resolve(binaryPath);modelPath=path.resolve(modelPath);accessSync(binaryPath,constants.R_OK|constants.X_OK);accessSync(modelPath,constants.R_OK);regular(binaryPath);const model=regular(modelPath);if(model.size<1024||model.size>20*1024*1024*1024)throw new Error('voice_model_size_invalid');const probe=await this.runner(binaryPath,['--help'],{timeout:5_000,maxBuffer:256*1024});if(!/whisper/i.test(`${probe.stdout}\n${probe.stderr}`))throw new Error('voice_runtime_incompatible');const value:VoiceRuntimeConfig={version:1,binaryPath,modelPath,configuredAt:new Date().toISOString()},temporary=`${this.configPath}.${randomUUID()}.partial`;writeFileSync(temporary,JSON.stringify(value),{flag:'wx',mode:0o600});renameSync(temporary,this.configPath);return this.capability()}
 remove(){rmSync(this.configPath,{force:true});return this.capability()}
 load():VoiceRuntimeConfig|undefined{try{const parsed=JSON.parse(readFileSync(this.configPath,'utf8'))as VoiceRuntimeConfig;if(parsed.version!==1||typeof parsed.binaryPath!=='string'||typeof parsed.modelPath!=='string')return undefined;return parsed}catch{return undefined}}
 capability():VoiceCapability{const config=this.load();let available=false,reason='Choose an installed whisper.cpp-compatible executable and local model. Waypoint will not download either.';if(config)try{accessSync(config.binaryPath,constants.R_OK|constants.X_OK);accessSync(config.modelPath,constants.R_OK);regular(config.binaryPath);regular(config.modelPath);available=true;reason='Configured local whisper.cpp runtime. Availability is revalidated for every turn.'}catch{reason='The configured local speech runtime or model is unavailable. Reconfigure it before listening.'}return{stt:{available,provider:'whisper.cpp',reason,...(config?{binaryPath:config.binaryPath,modelPath:config.modelPath}:{})},tts:this.platform==='darwin'?{available:true,provider:'macos-say',reason:'Uses the local macOS system voice.'}:{available:false,provider:'unavailable',reason:'Local speech playback is not yet reviewed for this platform.'},rawAudioPersistence:false,cloudSpeech:false}}
 async transcribe(wav:Uint8Array,signal?:AbortSignal){if(!wav.byteLength||wav.byteLength>MAX_VOICE_AUDIO_BYTES)throw new Error('voice_audio_size_invalid');if(signal?.aborted)throw new Error('voice_canceled');const config=this.load();if(!config||!this.capability().stt.available)throw new Error('voice_stt_unavailable');const root=mkdtempSync(path.join(this.ephemeralRoot,'turn-')),audio=path.join(root,'turn.wav'),output=path.join(root,'transcript');try{writeFileSync(audio,wav,{flag:'wx',mode:0o600});await this.runner(config.binaryPath,['-m',config.modelPath,'-f',audio,'-otxt','-of',output,'-nt'],{timeout:120_000,maxBuffer:1024*1024,signal});if(signal?.aborted)throw new Error('voice_canceled');const text=readFileSync(`${output}.txt`,'utf8').trim();if(!text||text.length>200_000)throw new Error('voice_transcript_invalid');return{text,provider:'whisper.cpp' as const,modelPath:config.modelPath}}finally{rmSync(root,{recursive:true,force:true})}}
}
export class NativeSpeechAdapter{
 private child?:ChildProcess;private sequence=0
 constructor(private readonly platform=process.platform,private readonly launch=spawn){}
 available(){return this.platform==='darwin'}
 speak(text:string,onDone:(result:'completed'|'canceled'|'failed')=>void){if(!this.available())throw new Error('voice_tts_unavailable');if(!text.trim()||text.length>200_000)throw new Error('voice_tts_text_invalid');this.stop();const sequence=++this.sequence,child=this.launch('/usr/bin/say',['--',text],{stdio:'ignore'});this.child=child;child.once('error',()=>{if(sequence===this.sequence){this.child=undefined;onDone('failed')}});child.once('exit',(code,signal)=>{if(sequence!==this.sequence)return;this.child=undefined;onDone(signal?'canceled':code===0?'completed':'failed')});return()=>this.stop()}
 stop(){this.sequence++;const child=this.child;this.child=undefined;if(child&&!child.killed)child.kill('SIGTERM')}
}
