import {mkdirSync,readFileSync,writeFileSync} from 'node:fs'
import path from 'node:path'
import {randomUUID} from 'node:crypto'
import sodium from 'libsodium-wrappers-sumo'
import {WaypointCrypto} from '../electron/core/sync/crypto.js'
import {toOpaqueRelayMessage} from '../electron/core/sync/relay-adapter.js'
import type {DeviceKeyPair} from '../electron/core/sync/types.js'
import {canonicalRelayRequest} from '../node/relay/server.js'

const [mode,directory,base]=process.argv.slice(2),workspaceId='hosted_workspace_001'
if(!mode||!directory)throw new Error('Usage: hosted-relay-validation <generate|roundtrip> <private-dir> [base-url]')
await sodium.ready
if(mode==='generate'){
  const crypto=await WaypointCrypto.create(),a=crypto.generateDevice('hosted_peer_a_001'),b=crypto.generateDevice('hosted_peer_b_001')
  mkdirSync(directory,{recursive:true});writeFileSync(path.join(directory,'clients.json'),JSON.stringify({workspaceId,workspaceKey:crypto.generateWorkspaceKey(),a,b}),{mode:0o600});writeFileSync(path.join(directory,'authority.json'),JSON.stringify({version:1,workspaces:[{workspaceId,keyEpoch:1,devices:[{...publicDevice(a),active:true,role:'owner'},{...publicDevice(b),active:true,role:'peer'}]}]})+'\n',{mode:0o600});process.stdout.write('Generated isolated hosted validation identities\n')
}else if(mode==='roundtrip'){
  if(!base)throw new Error('base-url is required');const crypto=await WaypointCrypto.create(),fixture=JSON.parse(readFileSync(path.join(directory,'clients.json'),'utf8')) as {workspaceId:string;workspaceKey:string;a:DeviceKeyPair;b:DeviceKeyPair},sentinel='hosted-waypoint-private-sentinel',now=new Date(),ab=crypto.encryptEnvelope({workspaceId:fixture.workspaceId,sender:fixture.a,recipient:fixture.b,workspaceKey:fixture.workspaceKey,payload:{body:sentinel,direction:'a-b'},keyEpoch:1,sequence:1,now,ttlMs:120_000}),ba=crypto.encryptEnvelope({workspaceId:fixture.workspaceId,sender:fixture.b,recipient:fixture.a,workspaceKey:fixture.workspaceKey,payload:{body:sentinel,direction:'b-a'},keyEpoch:1,sequence:1,now,ttlMs:120_000})
  const abMessage=toOpaqueRelayMessage(ab),baMessage=toOpaqueRelayMessage(ba),replayNonce=randomUUID();must(await signedFetch(base,'POST','/v1/messages',fixture.a,fixture.workspaceId,1,wire(abMessage),replayNonce),202);must(await signedFetch(base,'POST','/v1/messages',fixture.a,fixture.workspaceId,1,wire(abMessage),replayNonce),401);must(await signedFetch(base,'POST','/v1/messages',fixture.b,fixture.workspaceId,1,wire(baMessage)),202);must(await signedFetch(base,'GET',`/v1/messages?workspaceId=${fixture.workspaceId}&recipientDeviceId=${fixture.b.deviceId}`,fixture.a,fixture.workspaceId,1),403)
  const forB=await signedFetch(base,'GET',`/v1/messages?workspaceId=${fixture.workspaceId}&recipientDeviceId=${fixture.b.deviceId}`,fixture.b,fixture.workspaceId,1),forA=await signedFetch(base,'GET',`/v1/messages?workspaceId=${fixture.workspaceId}&recipientDeviceId=${fixture.a.deviceId}`,fixture.a,fixture.workspaceId,1),bPayload=await forB.json() as {messages:Array<{envelopeBase64:string}>},aPayload=await forA.json() as {messages:Array<{envelopeBase64:string}>};must(forB,200);must(forA,200);const bPlain=crypto.decryptEnvelope<{body:string;direction:string}>({envelope:decode(bPayload.messages[0].envelopeBase64),sender:fixture.a,recipient:fixture.b,workspaceKey:fixture.workspaceKey}),aPlain=crypto.decryptEnvelope<{body:string;direction:string}>({envelope:decode(aPayload.messages[0].envelopeBase64),sender:fixture.b,recipient:fixture.a,workspaceKey:fixture.workspaceKey});if(bPlain.body!==sentinel||aPlain.body!==sentinel)throw new Error('Hosted ciphertext validation failed');must(await signedFetch(base,'POST','/v1/acks',fixture.b,fixture.workspaceId,1,{workspaceId:fixture.workspaceId,recipientDeviceId:fixture.b.deviceId,messageId:abMessage.messageId}),200);writeFileSync(path.join(directory,'pending.json'),JSON.stringify({messageId:baMessage.messageId,replayNonce}),{mode:0o600});process.stdout.write('Hosted bidirectional encrypted delivery, auth denial, replay denial, decrypt, and ack passed\n')
}else if(mode==='recovery'){
  if(!base)throw new Error('base-url is required');const fixture=JSON.parse(readFileSync(path.join(directory,'clients.json'),'utf8')) as {workspaceId:string;workspaceKey:string;a:DeviceKeyPair;b:DeviceKeyPair},pending=JSON.parse(readFileSync(path.join(directory,'pending.json'),'utf8')) as {messageId:string;replayNonce:string},response=await signedFetch(base,'GET',`/v1/messages?workspaceId=${fixture.workspaceId}&recipientDeviceId=${fixture.a.deviceId}`,fixture.a,fixture.workspaceId,1),payload=await response.json() as {messages:Array<{messageId:string}>};must(response,200);if(!payload.messages.some((item)=>item.messageId===pending.messageId))throw new Error('Queued message did not survive restart');must(await signedFetch(base,'POST','/v1/acks',fixture.a,fixture.workspaceId,1,{workspaceId:fixture.workspaceId,recipientDeviceId:fixture.a.deviceId,messageId:pending.messageId}),200);process.stdout.write('Hosted restart persistence and recovery acknowledgement passed\n')
}else if(mode==='denied'){
  if(!base)throw new Error('base-url is required');const fixture=JSON.parse(readFileSync(path.join(directory,'clients.json'),'utf8')) as {workspaceId:string;a:DeviceKeyPair;b:DeviceKeyPair};must(await signedFetch(base,'GET',`/v1/messages?workspaceId=${fixture.workspaceId}&recipientDeviceId=${fixture.b.deviceId}`,fixture.b,fixture.workspaceId,1),401);process.stdout.write('Hosted revoked/old-epoch device denial passed\n')
}else throw new Error('Unknown validation mode')

function publicDevice({deviceId,signingPublicKey,encryptionPublicKey}:DeviceKeyPair){return{deviceId,signingPublicKey,encryptionPublicKey}}
function wire(message:ReturnType<typeof toOpaqueRelayMessage>){return{...message,envelope:undefined,envelopeBase64:Buffer.from(message.envelope).toString('base64')}}
function decode(value:string){return JSON.parse(Buffer.from(value,'base64').toString('utf8'))}
function must(response:Response,status:number){if(response.status!==status)throw new Error(`Expected HTTP ${status}, received ${response.status}`)}
async function signedFetch(origin:string,method:string,requestPath:string,device:DeviceKeyPair,workspace:string,keyEpoch:number,value?:unknown,nonce=randomUUID()){const body=value===undefined?Buffer.alloc(0):Buffer.from(JSON.stringify(value)),timestamp=new Date().toISOString(),canonical=canonicalRelayRequest(workspace,device.deviceId,keyEpoch,method,requestPath,timestamp,nonce,body),signature=sodium.to_base64(sodium.crypto_sign_detached(sodium.from_string(canonical),sodium.from_base64(device.signingPrivateKey,sodium.base64_variants.ORIGINAL)),sodium.base64_variants.ORIGINAL);return fetch(`${origin}${requestPath}`,{method,headers:{'content-type':'application/json','x-waypoint-workspace':workspace,'x-waypoint-device':device.deviceId,'x-waypoint-epoch':String(keyEpoch),'x-waypoint-timestamp':timestamp,'x-waypoint-nonce':nonce,'x-waypoint-signature':signature},body:method==='GET'?undefined:body})}
