import { FormEvent, StrictMode, useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import type { AttachmentMetadata, SanitizedSyncStatus, WorkspaceSummary } from '../electron/core/types'
import type { DiagnosticsReport } from '../electron/core/diagnostics'
import { failureAdvice, type ExecutionRunView } from './ai-workbench-ui'
import { reconcileSelectedChatId, RefreshGate } from './chat-selection'
import { groupChatHistory, type HistorySort } from './chat-history'
import waypointMark from './assets/waypoint-mark.svg'
import './styles.css'

type Chat=Awaited<ReturnType<Window['waypoint']['listChats']>>[number]
type Document=Awaited<ReturnType<Window['waypoint']['listDocuments']>>[number]
type Memory=Awaited<ReturnType<Window['waypoint']['listMemories']>>[number]
type Drawer='knowledge'|'activity'|'health'|'settings'|undefined

export function App(){
  const [workspace,setWorkspace]=useState<WorkspaceSummary>(),[workspaces,setWorkspaces]=useState<WorkspaceSummary[]>([])
  const [chats,setChats]=useState<Chat[]>([]),[selectedChatId,setSelectedChatId]=useState<string>(),[documents,setDocuments]=useState<Document[]>([]),[memories,setMemories]=useState<Memory[]>([]),[activity,setActivity]=useState<Array<Record<string,unknown>>>([])
  const [profiles,setProfiles]=useState<Awaited<ReturnType<Window['waypoint']['listSecurityProfiles']>>>([]),[runs,setRuns]=useState<Array<Record<string,unknown>>>([]),[capabilities,setCapabilities]=useState<Awaited<ReturnType<Window['waypoint']['cliCapabilities']>>>([])
  const [attachments,setAttachments]=useState<AttachmentMetadata[]>([]),[attachmentBusy,setAttachmentBusy]=useState(false),[chatCli,setChatCli]=useState<'codex'|'claude'>('codex')
  const [drawer,setDrawer]=useState<Drawer>(),[sidebarOpen,setSidebarOpen]=useState(false),[historyQuery,setHistoryQuery]=useState(''),[historySort,setHistorySort]=useState<HistorySort>('recent'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[diagnostics,setDiagnostics]=useState<DiagnosticsReport>(),[checking,setChecking]=useState(false),[syncStatus,setSyncStatus]=useState<SanitizedSyncStatus>()
  const [desktopSync,setDesktopSync]=useState<Awaited<ReturnType<Window['waypoint']['desktopSyncStatus']>>>(),[syncDevices,setSyncDevices]=useState<Awaited<ReturnType<Window['waypoint']['syncDevices']>>>([]),[pendingPeers,setPendingPeers]=useState<Awaited<ReturnType<Window['waypoint']['pendingSyncEnrollments']>>>([]),[bootstrapBundle,setBootstrapBundle]=useState('')
  const refreshGate=useRef(new RefreshGate()),composerRef=useRef<HTMLTextAreaElement>(null),overlayRef=useRef<HTMLElement>(null),previousFocusRef=useRef<HTMLElement|null>(null)

  function showError(reason:unknown){setError(reason instanceof Error?reason.message:String(reason))}
  async function refresh(next=workspace){if(!next)return;const token=refreshGate.current.begin();const [nextChats,nextDocuments,nextMemories,nextActivity,nextProfiles,nextRuns,nextSync,nextDesktop]=await Promise.all([window.waypoint.listChats(next.id),window.waypoint.listDocuments(next.id),window.waypoint.listMemories(next.id),window.waypoint.activity(next.id),window.waypoint.listSecurityProfiles(next.id),window.waypoint.listExecutions(next.id),window.waypoint.syncStatus(next.id),window.waypoint.desktopSyncStatus(next.id)]);if(!refreshGate.current.isCurrent(token))return;setChats(nextChats);setSelectedChatId((current)=>reconcileSelectedChatId(nextChats,current));setDocuments(nextDocuments);setMemories(nextMemories);setActivity(nextActivity);setProfiles(nextProfiles);setRuns(nextRuns);setSyncStatus(nextSync);setDesktopSync(nextDesktop);if(nextDesktop.configured){const [devices,pending]=await Promise.all([window.waypoint.syncDevices(next.id).catch(()=>[]),window.waypoint.pendingSyncEnrollments(next.id).catch(()=>[])]);if(refreshGate.current.isCurrent(token)){setSyncDevices(devices);setPendingPeers(pending)}}else{setSyncDevices([]);setPendingPeers([])}}
  async function selectWorkspace(next:WorkspaceSummary){setWorkspace(next);setSelectedChatId(undefined);setDrawer(undefined);await refresh(next)}
  useEffect(()=>{void Promise.all([window.waypoint.bootstrap(),window.waypoint.cliCapabilities()]).then(async([{workspaces:available},nextCapabilities])=>{setWorkspaces(available);setCapabilities(nextCapabilities);if(available[0])await selectWorkspace(available[0])}).catch(showError)
    // Initial bootstrap intentionally runs once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[])
  useEffect(()=>{if(!runs.some((run)=>run.status==='running'))return;const timer=window.setInterval(()=>void refresh().catch(showError),750);return()=>window.clearInterval(timer)})
  useEffect(()=>{if(!workspace||!selectedChatId)return;void window.waypoint.listChatAttachments(workspace.id,selectedChatId).then(setAttachments).catch(showError)},[workspace,selectedChatId,chats])
  useEffect(()=>{const available=capabilities.find((item)=>item.available&&item.compatible!==false);if(!available||capabilities.some((item)=>item.name===chatCli&&item.available&&item.compatible!==false))return;const timer=window.setTimeout(()=>setChatCli(available.name),0);return()=>window.clearTimeout(timer)},[capabilities,chatCli])
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'){setDrawer(undefined);setSidebarOpen(false)}if(event.metaKey&&event.key.toLowerCase()==='n'){event.preventDefault();void beginNewChat()}if(event.metaKey&&event.key.toLowerCase()==='k'){event.preventDefault();setDrawer('knowledge')}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)})
  useEffect(()=>{if(!drawer&&!sidebarOpen)return;previousFocusRef.current=document.activeElement instanceof HTMLElement?document.activeElement:null;const overlay=overlayRef.current;if(!overlay)return;const focusable=()=>[...overlay.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];window.setTimeout(()=>focusable()[0]?.focus(),0);const trap=(event:KeyboardEvent)=>{if(event.key!=='Tab')return;const items=focusable();if(!items.length)return;const first=items[0],last=items.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};overlay.addEventListener('keydown',trap);return()=>{overlay.removeEventListener('keydown',trap);previousFocusRef.current?.focus()}},[drawer,sidebarOpen])

  async function createWorkspace(event:FormEvent<HTMLFormElement>){event.preventDefault();try{const created=await window.waypoint.createWorkspace(String(new FormData(event.currentTarget).get('name')??''));setWorkspaces((current)=>[...current,created]);await selectWorkspace(created)}catch(reason){showError(reason)}}
  async function beginNewChat(){if(!workspace)return;try{const id=await window.waypoint.createChat(workspace.id,'New chat');await refresh();setSelectedChatId(id);setSidebarOpen(false);window.setTimeout(()=>composerRef.current?.focus(),0)}catch(reason){showError(reason)}}
  async function chooseAttachments(){if(!workspace||!selectedChatId)return;setAttachmentBusy(true);try{const result=await window.waypoint.selectChatAttachments(workspace.id,selectedChatId);setAttachments(result.attachments)}catch(reason){showError(reason)}finally{setAttachmentBusy(false)}}
  async function removeAttachment(id:string){if(!workspace||!selectedChatId)return;setAttachmentBusy(true);try{await window.waypoint.deleteAttachment(workspace.id,id);setAttachments(await window.waypoint.listChatAttachments(workspace.id,selectedChatId))}catch(reason){showError(reason)}finally{setAttachmentBusy(false)}}
  async function runChat(event:FormEvent<HTMLFormElement>,chatId:string){event.preventDefault();if(!workspace)return;const form=event.currentTarget,data=new FormData(form),prompt=String(data.get('prompt')??''),cli=String(data.get('cli')??chatCli) as 'codex'|'claude',profile=String(data.get('profile')??''),model=String(data.get('model')??'')||undefined,attachmentIds=attachments.filter((item)=>item.ownerId===chatId).map((item)=>item.id);setError('');try{const messageId=await window.waypoint.addMessage(workspace.id,chatId,'user',prompt,attachmentIds),started=await window.waypoint.runChat(workspace.id,chatId,messageId,cli,profile,prompt,model,undefined,attachmentIds);form.reset();const unsupported=started.attachmentDelivery.unsupported;setNotice(unsupported.length?`${unsupported.length} attachment${unsupported.length===1?' remains':'s remain'} local because ${cli} cannot accept the file type.`:`${cli} is responding…`);await refresh()}catch(reason){showError(reason);await refresh().catch(showError);setAttachments(await window.waypoint.listChatAttachments(workspace.id,chatId).catch(()=>[]))}}
  async function retryRun(run:ExecutionRunView){if(!workspace||!selectedChat)return;const source=selectedChat.messages.find((message)=>message.id===String(run.sourceMessageId??'')&&message.role==='user');if(!source){setError('This older run has no exact source message and cannot be retried safely.');return}const ids=attachments.filter((item)=>item.ownerId===source.id).map((item)=>item.id);try{await window.waypoint.runChat(workspace.id,selectedChat.id,source.id,String(run.cli) as 'codex'|'claude',String(run.securityProfileId),source.body,run.model?String(run.model):undefined,undefined,ids);setNotice('Retry started.');await refresh()}catch(reason){showError(reason);await refresh().catch(showError)}}
  async function cancelRun(id:string){try{await window.waypoint.cancelExecution(id);setNotice('Stopping the local CLI…');await refresh()}catch(reason){showError(reason)}}
  async function remove(kind:'document'|'chat'|'memory',id:string){if(!workspace||!window.confirm(`Delete this ${kind} and its owned local data? This cannot be undone.`))return;try{await window.waypoint.deleteObject(workspace.id,kind,id);await refresh()}catch(reason){showError(reason)}}
  async function saveMessageToKnowledge(messageId:string){if(!workspace)return;try{await window.waypoint.captureMessageAsDocument(workspace.id,messageId);setNotice('Saved to local knowledge.');await refresh()}catch(reason){showError(reason)}}
  async function editDocument(item:Document){if(!workspace)return;const title=window.prompt('Note title',item.title);if(title===null)return;const body=window.prompt('Note text',item.body);if(body===null)return;try{await window.waypoint.updateDocument(workspace.id,item.id,title,body);setNotice('Note updated locally.');await refresh()}catch(reason){showError(reason)}}
  async function runHealth(){if(!workspace)return;setChecking(true);try{setDiagnostics(await window.waypoint.diagnostics(workspace.id))}catch(reason){showError(reason)}finally{setChecking(false)}}
  async function exportWorkspace(){if(!workspace)return;try{const result=await window.waypoint.exportWorkspace(workspace.id);if(!result.canceled)setNotice('Protected-location reminder shown; backup saved and verified.')}catch(reason){showError(reason)}}
  async function restoreWorkspace(){try{const result=await window.waypoint.restoreWorkspace();if(result.workspace){setWorkspaces((current)=>[...current,result.workspace!]);await selectWorkspace(result.workspace)}}catch(reason){showError(reason)}}
  async function initializeSync(){if(!workspace)return;try{const result=await window.waypoint.initializeDesktopSync(workspace.id);if(result.bootstrap){setBootstrapBundle(JSON.stringify(result.bootstrap));setNotice('Protected owner identity created. Register the public bootstrap bundle on the relay, then refresh.')}await refresh()}catch(reason){showError(reason)}}
  async function invitePeer(){if(!workspace)return;try{const result=await window.waypoint.createSyncInvitation(workspace.id);await navigator.clipboard.writeText(result.token);setNotice(`One-use invitation copied. It expires ${new Date(result.expiresAt).toLocaleTimeString()}.`)}catch(reason){showError(reason)}}
  async function joinSync(){const token=window.prompt('Paste the one-use Waypoint enrollment token');if(!token)return;try{const result=await window.waypoint.submitSyncEnrollment(token);setNotice('Enrollment requested. After the owner approves, choose Complete enrollment.');if(workspaces.some((item)=>item.id===result.workspaceId))await refresh()}catch(reason){showError(reason)}}
  async function completeSync(){if(!workspace)return;try{await window.waypoint.completeSyncEnrollment(workspace.id);setNotice('This device is enrolled and the workspace key is protected locally.');await refresh()}catch(reason){showError(reason)}}
  async function approvePeer(requestId:string){if(!workspace)return;try{const result=await window.waypoint.approveSyncEnrollment(workspace.id,requestId);if(!result.canceled){setNotice('Device approved.');await refresh()}}catch(reason){showError(reason)}}
  async function revokePeer(deviceId:string){if(!workspace)return;try{const result=await window.waypoint.revokeSyncDevice(workspace.id,deviceId);if(!result.canceled){setNotice(`Device revoked; key epoch ${result.rotation?.keyEpoch} is active.`);await refresh()}}catch(reason){showError(reason)}}

  if(!workspace)return <main className="onboarding"><img className="brand-mark" src={waypointMark} alt="Waypoint"/><p className="kicker">Private by default</p><h1>Your thinking,<br/>close at hand.</h1><p>Waypoint keeps conversations and knowledge on this computer and uses only the signed-in CLI you choose.</p><form onSubmit={createWorkspace}><label>Workspace name<input name="name" required maxLength={120} autoFocus placeholder="Personal"/></label><button>Create workspace</button></form>{error&&<p role="alert" className="alert error">{error}</p>}</main>

  const selectedChat=chats.find((chat)=>chat.id===selectedChatId),chatRuns=runs.filter((run)=>run.chatId===selectedChatId),queued=attachments.filter((item)=>item.ownerId===selectedChatId),historyGroups=groupChatHistory(chats,historyQuery,historySort)
  return <div className="app-frame">
    <button className="mobile-menu icon-button" aria-label="Open conversations" onClick={()=>setSidebarOpen(true)}>☰</button>
    {sidebarOpen&&<button className="sidebar-scrim" aria-label="Close conversations" onClick={()=>setSidebarOpen(false)}/>}
    <aside ref={sidebarOpen?overlayRef:undefined} className={`left-sidebar ${sidebarOpen?'open':''}`} aria-label="Primary navigation" role={sidebarOpen?'dialog':undefined} aria-modal={sidebarOpen||undefined}>
      <div className="wordmark"><img src={waypointMark} alt=""/><strong>Waypoint</strong></div>
      <button className="new-chat" onClick={()=>void beginNewChat()}><span>＋</span> New chat <kbd>⌘N</kbd></button>
      <div className="history-tools"><label><span className="sr-only">Search conversations</span><b>⌕</b><input value={historyQuery} onChange={(event)=>setHistoryQuery(event.target.value)} placeholder="Search chats"/></label><select value={historySort} onChange={(event)=>setHistorySort(event.target.value as HistorySort)} aria-label="Sort conversations"><option value="recent">Recent</option><option value="title">A–Z</option></select></div>
      <nav className="conversation-list" aria-label="Conversations">{historyGroups.map((group)=><section key={group.label} aria-labelledby={`history-${group.label.replaceAll(' ','-')}`}><h2 id={`history-${group.label.replaceAll(' ','-')}`}>{group.label}</h2>{group.items.map((item)=>{const chat=chats.find((candidate)=>candidate.id===item.id)!;return <div className={`conversation-row ${chat.id===selectedChatId?'active':''}`} key={chat.id}><button className="conversation-select" aria-current={chat.id===selectedChatId?'page':undefined} onClick={()=>{setSelectedChatId(chat.id);setSidebarOpen(false);setDrawer(undefined)}}><span>{chat.title}</span><small>{chat.messages.at(-1)?.body||'No messages yet'}</small></button><button className="conversation-delete" aria-label={`Delete ${chat.title}`} onClick={()=>void remove('chat',chat.id)}>×</button></div>})}</section>)}{!historyGroups.length&&<p className="sidebar-empty">{historyQuery?'No matching conversations.':'Your conversations will live here.'}</p>}</nav>
      <nav className="utility-nav" aria-label="Workspace tools"><button onClick={()=>{setSidebarOpen(false);setDrawer('knowledge')}}><span>⌘</span> Knowledge <kbd>⌘K</kbd></button><button onClick={()=>{setSidebarOpen(false);setDrawer('activity')}}><span>↗</span> Activity</button><button onClick={()=>{setSidebarOpen(false);setDrawer('health')}}><span>♡</span> Health</button><button onClick={()=>{setSidebarOpen(false);setDrawer('settings')}}><span>⚙</span> Settings</button></nav>
      <div className="workspace-switcher"><label>Workspace<select value={workspace.id} onChange={(event)=>{const next=workspaces.find((item)=>item.id===event.target.value);if(next)void selectWorkspace(next)}}>{workspaces.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><small><i/> Local only</small></div>
    </aside>

    <main className="chat-main">
      <header className="chat-header"><button className="mobile-menu-inline icon-button" aria-label="Open conversations" onClick={()=>setSidebarOpen(true)}>☰</button><div><strong>{selectedChat?.title||'New conversation'}</strong><small>{chatCli} · local CLI</small></div><button className="knowledge-button" onClick={()=>setDrawer('knowledge')}>Knowledge <span>⌘K</span></button></header>
      {(error||notice)&&<div className={`toast ${error?'error':''}`} role={error?'alert':'status'}>{error||notice}<button aria-label="Dismiss" onClick={()=>{setError('');setNotice('')}}>×</button></div>}
      {selectedChat?<>
        <section className="transcript" aria-label="Conversation" aria-live="polite">{!selectedChat.messages.length&&<div className="empty-chat"><div className="compass">✦</div><h1>What are we working on?</h1><p>Ask Waypoint to think, write, research your local knowledge, or organize what matters.</p></div>}{selectedChat.messages.map((message)=><article key={message.id} className={`chat-message ${message.role}`}><div className="message-role">{message.role==='assistant'?<img className="assistant-mark" src={waypointMark} alt="Waypoint"/>:<span>You</span>}</div><div className="message-content"><p>{message.body}</p>{attachments.some((item)=>item.ownerId===message.id)&&<div className="sent-files">{attachments.filter((item)=>item.ownerId===message.id).map((item)=><span key={item.id}>▧ {item.name}<small>stored locally</small></span>)}</div>}{message.role==='assistant'&&<button className="message-action" onClick={()=>void saveMessageToKnowledge(message.id)}>＋ Save to knowledge</button>}</div></article>)}{chatRuns.filter((run)=>run.status!=='completed').map((value)=>{const run=value as ExecutionRunView,events=run.events??[],text=events.filter((event)=>event.type==='text').map((event)=>String(event.text??'')).join('');return <article className={`run-strip ${String(run.status)}`} key={String(run.id)}><div><span className="status-dot"/><strong>{run.status==='running'?`${run.cli} is responding`:String(run.status).replace('_',' ')}</strong>{text&&<p>{text}</p>}{failureAdvice(run)&&<small>{failureAdvice(run)}</small>}</div><div>{run.status==='running'&&<button onClick={()=>void cancelRun(String(run.id))}>Stop</button>}{['failed','timed_out','canceled'].includes(String(run.status))&&<button onClick={()=>void retryRun(run)}>Retry</button>}</div></article>})}</section>
        <div className="composer-dock"><form className="composer" onSubmit={(event)=>void runChat(event,selectedChat.id)}>{queued.length>0&&<div className="file-queue" aria-label="Queued attachments">{queued.map((item)=><span key={item.id}>▧ <b>{item.name}</b><small>{Math.ceil(item.bytes/1024)} KiB</small><button type="button" aria-label={`Remove ${item.name}`} onClick={()=>void removeAttachment(item.id)}>×</button></span>)}</div>}<textarea ref={composerRef} name="prompt" required rows={1} placeholder="Message Waypoint" aria-label="Message Waypoint" onKeyDown={(event)=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();event.currentTarget.form?.requestSubmit()}}}/><div className="composer-controls"><div><button type="button" className="attach" disabled={attachmentBusy} onClick={()=>void chooseAttachments()} aria-label="Attach files">＋</button><select name="cli" value={chatCli} onChange={(event)=>setChatCli(event.target.value as 'codex'|'claude')} aria-label="AI provider">{capabilities.map((item)=><option key={item.name} value={item.name} disabled={!item.available||item.compatible===false}>{item.name}{!item.available?' · unavailable':''}</option>)}</select><select name="profile" aria-label="Security profile">{profiles.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="model" placeholder="Default model" aria-label="Optional model"/></div><button className="send" aria-label="Send message">↑</button></div><p className="capability-copy">{chatCli==='codex'?'Images and text can be passed to the Codex CLI. PDF and Word stay local.':'Text can be passed to Claude. Images, PDF, and Word stay local.'}</p></form><small className="composer-hint">Enter to send · Shift Enter for a new line</small></div>
      </>:<section className="transcript"><div className="empty-chat"><div className="compass">✦</div><h1>Start with a conversation.</h1><p>Your chats become the path into notes, memories, and everything Waypoint knows.</p><button onClick={()=>void beginNewChat()}>New chat</button></div></section>}
    </main>

    {drawer&&<><button className="drawer-scrim" aria-label="Close panel" onClick={()=>setDrawer(undefined)}/><aside ref={overlayRef} className="right-drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title"><header><div><p>{workspace.name}</p><h2 id="drawer-title">{drawer[0].toUpperCase()+drawer.slice(1)}</h2></div><button className="icon-button" aria-label="Close panel" onClick={()=>setDrawer(undefined)}>×</button></header>
      {drawer==='knowledge'&&<div className="drawer-body"><p className="drawer-intro">Save useful assistant responses from chat, then browse and manage what Waypoint has retained locally.</p><section><h3>Notes <span>{documents.length}</span></h3>{documents.map((item)=><article className="knowledge-item" key={item.id}><div><strong>{item.title}</strong><p>{item.body.slice(0,180)}</p></div><div className="knowledge-actions"><button aria-label={`Edit ${item.title}`} onClick={()=>void editDocument(item)}>Edit</button><button aria-label={`Delete ${item.title}`} onClick={()=>void remove('document',item.id)}>Delete</button></div></article>)}{!documents.length&&<p className="drawer-empty">No notes yet. Use Save to knowledge on an assistant response.</p>}</section><section><h3>Memories <span>{memories.length}</span></h3>{memories.map((item)=><article className="knowledge-item" key={item.id}><div><strong>{item.title}</strong><p>{item.body.slice(0,180)}</p></div><button aria-label={`Delete ${item.title}`} onClick={()=>void remove('memory',item.id)}>Delete</button></article>)}{!memories.length&&<p className="drawer-empty">No memories yet.</p>}</section></div>}
      {drawer==='activity'&&<div className="drawer-body"><p className="drawer-intro">A content-minimized history of local actions.</p>{activity.map((item)=><article className="activity-item" key={String(item.id)}><span/><div><strong>{String(item.action).replaceAll('.',' ')}</strong><small>{String(item.createdAt)}</small></div></article>)}</div>}
      {drawer==='health'&&<div className="drawer-body"><div className="drawer-actions"><button onClick={()=>void runHealth()} disabled={checking}>{checking?'Checking…':'Run local checks'}</button></div>{diagnostics?.results.map((item)=><article className={`health-item ${item.status}`} key={item.code}><span>{item.status.replace('_',' ')}</span><strong>{item.code}</strong><p>{item.summary}</p>{item.remediation&&<small>{item.remediation}</small>}</article>)||<p className="drawer-empty">Check the database, storage, attachments, indexes, CLIs, and local sync state.</p>}</div>}
      {drawer==='settings'&&<div className="drawer-body"><section><h3>Secure device sync</h3><p className="drawer-intro">End-to-end encrypted through the pinned Waypoint relay. Keys stay in protected storage on each device.</p><dl className="settings-list"><div><dt>Relay</dt><dd>{desktopSync?.configured?'Connected identity':desktopSync?.pendingEnrollment?'Approval pending':'Not configured'}</dd></div><div><dt>Key epoch</dt><dd>{desktopSync?.keyEpoch||'—'}</dd></div><div><dt>Pending changes</dt><dd>{syncStatus?.pending??0}</dd></div><div><dt>Deletion markers</dt><dd>{syncStatus?.tombstones??0}</dd></div></dl>{!desktopSync?.configured&&!desktopSync?.pendingEnrollment&&<div className="drawer-actions"><button onClick={()=>void initializeSync()}>Set up first device</button><button className="secondary" onClick={()=>void joinSync()}>Join with invitation</button></div>}{desktopSync?.pendingEnrollment&&<button onClick={()=>void completeSync()}>Complete approved enrollment</button>}{bootstrapBundle&&<div className="bootstrap-bundle"><p>Public operator bootstrap bundle</p><textarea readOnly value={bootstrapBundle}/><button className="secondary" onClick={()=>void navigator.clipboard.writeText(bootstrapBundle)}>Copy public bundle</button></div>}{desktopSync?.configured&&<><div className="drawer-actions"><button onClick={()=>void invitePeer()}>Invite device</button>{desktopSync.rotationTargetEpoch&&<button className="secondary" onClick={()=>workspace&&void window.waypoint.resumeSyncRotation(workspace.id).then(()=>refresh()).catch(showError)}>Resume rotation</button>}</div>{pendingPeers.map((item)=><article className="provider-row" key={item.requestId}><span><strong>Pending device</strong><small>{item.deviceId.slice(0,12)}…</small></span><button onClick={()=>void approvePeer(item.requestId)}>Approve</button></article>)}{syncDevices.map((item)=><article className="provider-row" key={item.deviceId}><span><strong>{item.role==='owner'?'This workspace owner':'Peer device'}</strong><small>{item.deviceId.slice(0,12)}… · {item.status}</small></span>{item.role!=='owner'&&item.status==='active'&&<button onClick={()=>void revokePeer(item.deviceId)}>Revoke</button>}</article>)}</>}</section><section><h3>Backup & recovery</h3><p className="drawer-intro">Backups are plaintext. Keep them in a protected location.</p><div className="drawer-actions"><button onClick={()=>void exportWorkspace()}>Back up workspace</button><button className="secondary" onClick={()=>void restoreWorkspace()}>Restore backup</button></div></section><section><h3>Provider status</h3>{capabilities.map((item)=><p className="provider-row" key={item.name}><strong>{item.name}</strong><span>{item.available&&item.compatible!==false?'Ready':item.compatibilityError||item.error}</span></p>)}</section></div>}
    </aside></>}
  </div>
}

createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>)
