import { useEffect, useRef, useState } from 'react'
type ScreenCaptureLayer={id:string;tool:'select'|'crop'|'arrow'|'line'|'rectangle'|'ellipse'|'text'|'step'|'highlight'|'freehand'|'blur'|'pixelate'|'redact';x:number;y:number;width:number;height:number;color:string;stroke:number;text?:string;points?:Array<{x:number;y:number}>}
type ScreenCaptureView={id:string;title:string;mode:string;sourceName:string;capturedAt:string;width:number;height:number;sha256:string;layers:ScreenCaptureLayer[];flattened:boolean;expiresAt:string;bytes:number}

type Tool=ScreenCaptureLayer['tool']
const TOOLS:Array<{id:Tool;label:string}>=[['select','Select'],['crop','Crop'],['arrow','Arrow'],['line','Line'],['rectangle','Rectangle'],['ellipse','Ellipse'],['text','Text'],['step','Step'],['highlight','Highlight'],['freehand','Draw'],['blur','Blur'],['pixelate','Pixelate'],['redact','Redact']].map(([id,label])=>({id:id as Tool,label}))

function renderLayer(context:CanvasRenderingContext2D,layer:ScreenCaptureLayer,image:HTMLImageElement,step:number){
  context.save();context.strokeStyle=layer.color;context.fillStyle=layer.color;context.lineWidth=layer.stroke;context.lineCap='round';context.lineJoin='round';
  if(layer.tool==='rectangle')context.strokeRect(layer.x,layer.y,layer.width,layer.height)
  else if(layer.tool==='ellipse'){context.beginPath();context.ellipse(layer.x+layer.width/2,layer.y+layer.height/2,Math.abs(layer.width/2),Math.abs(layer.height/2),0,0,Math.PI*2);context.stroke()}
  else if(layer.tool==='line'||layer.tool==='arrow'){context.beginPath();context.moveTo(layer.x,layer.y);context.lineTo(layer.x+layer.width,layer.y+layer.height);context.stroke();if(layer.tool==='arrow'){const angle=Math.atan2(layer.height,layer.width),endX=layer.x+layer.width,endY=layer.y+layer.height;context.beginPath();context.moveTo(endX,endY);context.lineTo(endX-14*Math.cos(angle-.5),endY-14*Math.sin(angle-.5));context.moveTo(endX,endY);context.lineTo(endX-14*Math.cos(angle+.5),endY-14*Math.sin(angle+.5));context.stroke()}}
  else if(layer.tool==='highlight'){context.globalAlpha=.28;context.fillRect(layer.x,layer.y,layer.width,layer.height)}
  else if(layer.tool==='redact')context.fillRect(layer.x,layer.y,layer.width,layer.height)
  else if(layer.tool==='blur'){context.beginPath();context.rect(layer.x,layer.y,layer.width,layer.height);context.clip();context.filter='blur(12px)';context.drawImage(image,0,0)}
  else if(layer.tool==='pixelate'){const w=Math.max(1,Math.floor(layer.width/12)),h=Math.max(1,Math.floor(layer.height/12)),off=document.createElement('canvas');off.width=w;off.height=h;off.getContext('2d')?.drawImage(image,layer.x,layer.y,layer.width,layer.height,0,0,w,h);context.imageSmoothingEnabled=false;context.drawImage(off,0,0,w,h,layer.x,layer.y,layer.width,layer.height)}
  else if(layer.tool==='text'){context.font=`${Math.max(14,layer.stroke*5)}px Manrope, sans-serif`;context.fillText(layer.text||'Text',layer.x,layer.y+Math.max(18,layer.stroke*5))}
  else if(layer.tool==='step'){context.beginPath();context.arc(layer.x+16,layer.y+16,16,0,Math.PI*2);context.fill();context.fillStyle='#fff';context.font='700 16px Manrope';context.textAlign='center';context.fillText(String(step),layer.x+16,layer.y+22)}
  else if(layer.tool==='freehand'&&layer.points?.length){context.beginPath();context.moveTo(layer.points[0].x,layer.points[0].y);for(const point of layer.points.slice(1))context.lineTo(point.x,point.y);context.stroke()}
  else if(layer.tool==='crop'){context.setLineDash([8,6]);context.strokeRect(layer.x,layer.y,layer.width,layer.height)}
  context.restore()
}

function CaptureEditor({workspaceId,capture,dataUrl,onSaved,onClose}:{workspaceId:string;capture:ScreenCaptureView;dataUrl:string;onSaved:(next:ScreenCaptureView)=>void;onClose:()=>void}){
  const canvas=useRef<HTMLCanvasElement>(null),image=useRef<HTMLImageElement|null>(null),operation=useRef<{kind:'draw'|'move'|'resize';start:{x:number;y:number};before:ScreenCaptureLayer[]}|null>(null)
  const [tool,setTool]=useState<Tool>(capture.mode==='region'&&!capture.flattened?'crop':'select'),[layers,setLayers]=useState(capture.layers),[undo,setUndo]=useState<ScreenCaptureLayer[][]>([]),[redo,setRedo]=useState<ScreenCaptureLayer[][]>([]),[color,setColor]=useState('#ec6b4f'),[stroke,setStroke]=useState(4),[draft,setDraft]=useState<ScreenCaptureLayer>(),[selected,setSelected]=useState<string>(),[error,setError]=useState('')
  function draw(list=[...layers,...(draft?[draft]:[])],decorate=true){const target=canvas.current,img=image.current;if(!target||!img)return;target.width=img.naturalWidth;target.height=img.naturalHeight;const context=target.getContext('2d')!;context.drawImage(img,0,0);let step=1;for(const layer of [...list.filter((item)=>item.tool!=='redact'),...list.filter((item)=>item.tool==='redact')]){renderLayer(context,layer,img,step);if(layer.tool==='step')step++;if(decorate&&layer.id===selected){context.save();context.strokeStyle='#53a5b5';context.setLineDash([5,4]);context.strokeRect(layer.x-3,layer.y-3,layer.width+6,layer.height+6);context.fillStyle='#53a5b5';context.fillRect(layer.x+layer.width-6,layer.y+layer.height-6,12,12);context.restore()}}}
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{const next=new Image();next.onload=()=>{image.current=next;draw()};next.src=dataUrl},[dataUrl])
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>draw(),[layers,draft,selected])
  function point(event:React.PointerEvent<HTMLCanvasElement>){const rect=event.currentTarget.getBoundingClientRect();return{x:(event.clientX-rect.left)*event.currentTarget.width/rect.width,y:(event.clientY-rect.top)*event.currentTarget.height/rect.height}}
  function commit(before:ScreenCaptureLayer[]){setUndo((items)=>[...items,before]);setRedo([])}
  function down(event:React.PointerEvent<HTMLCanvasElement>){event.currentTarget.setPointerCapture(event.pointerId);const p=point(event);if(tool==='select'){const hit=[...layers].reverse().find((layer)=>p.x>=layer.x-8&&p.x<=layer.x+layer.width+8&&p.y>=layer.y-8&&p.y<=layer.y+layer.height+8);setSelected(hit?.id);if(hit)operation.current={kind:Math.abs(p.x-(hit.x+hit.width))<18&&Math.abs(p.y-(hit.y+hit.height))<18?'resize':'move',start:p,before:layers};return}const text=tool==='text'?window.prompt('Annotation text','')?.slice(0,500):undefined;if(tool==='text'&&!text)return;operation.current={kind:'draw',start:p,before:layers};setDraft({id:crypto.randomUUID(),tool,x:p.x,y:p.y,width:tool==='step'?32:0,height:tool==='step'?32:0,color,stroke,...(text?{text}:{}),...(tool==='freehand'?{points:[p]}:{})})}
  function move(event:React.PointerEvent<HTMLCanvasElement>){const active=operation.current;if(!active)return;const p=point(event);if(active.kind==='move'&&selected){const dx=p.x-active.start.x,dy=p.y-active.start.y;setLayers(active.before.map((item)=>item.id===selected?{...item,x:Math.max(0,Math.min(capture.width-item.width,item.x+dx)),y:Math.max(0,Math.min(capture.height-item.height,item.y+dy))}:item));return}if(active.kind==='resize'&&selected){setLayers(active.before.map((item)=>item.id===selected?{...item,width:Math.max(1,Math.min(capture.width-item.x,item.width+p.x-active.start.x)),height:Math.max(1,Math.min(capture.height-item.y,item.height+p.y-active.start.y))}:item));return}setDraft((item)=>{if(!item)return item;if(item.tool==='freehand'){const points=[...(item.points||[]),p],xs=points.map((value)=>value.x),ys=points.map((value)=>value.y);return{...item,x:Math.min(...xs),y:Math.min(...ys),width:Math.max(...xs)-Math.min(...xs),height:Math.max(...ys)-Math.min(...ys),points}}const x=Math.min(active.start.x,p.x),y=Math.min(active.start.y,p.y);return{...item,x,y,width:Math.abs(p.x-active.start.x),height:Math.abs(p.y-active.start.y)}})}
  function up(){const active=operation.current;operation.current=null;if(!active)return;if(active.kind==='draw'&&draft){commit(active.before);setLayers((items)=>[...items,draft]);setDraft(undefined)}else if(JSON.stringify(active.before)!==JSON.stringify(layers))commit(active.before)}
  async function save(flatten:boolean){setError('');try{if(!flatten){onSaved(await window.waypoint.updateScreenCapture(workspaceId,capture.id,layers));return}const crop=[...layers].reverse().find((layer)=>layer.tool==='crop');if(capture.mode==='region'&&!crop){setTool('crop');setError('Draw a crop region before flattening this region capture.');return}if(layers.some((layer)=>layer.tool==='redact')&&!window.confirm('Flatten redaction permanently for this source and future copies? Existing Chat, Knowledge, and backup copies remain independent and must be deleted separately.'))return;const target=canvas.current;if(!target)return;draw(layers.filter((layer)=>layer.tool!=='crop'),false);const output=document.createElement('canvas'),context=output.getContext('2d')!,bounds=crop??{x:0,y:0,width:target.width,height:target.height};output.width=Math.max(1,Math.round(bounds.width));output.height=Math.max(1,Math.round(bounds.height));context.drawImage(target,bounds.x,bounds.y,bounds.width,bounds.height,0,0,output.width,output.height);const blob=await new Promise<Blob>((resolve,reject)=>output.toBlob((value)=>value?resolve(value):reject(new Error('PNG export failed')),'image/png'));onSaved(await window.waypoint.updateScreenCapture(workspaceId,capture.id,layers,new Uint8Array(await blob.arrayBuffer())))}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}}
  return <section className="capture-editor" aria-label="Screenshot annotation editor"><header><div><strong>Annotate screenshot</strong><small>Layers stay editable until Flatten & save.</small></div><button autoFocus onClick={onClose}>Close</button></header><nav aria-label="Annotation tools">{TOOLS.map((item)=><button className={tool===item.id?'active':''} aria-pressed={tool===item.id} onClick={()=>setTool(item.id)} key={item.id}>{item.label}</button>)}</nav><div className="capture-editor-controls"><label>Color <input aria-label="Annotation color" type="color" value={color} onChange={(event)=>setColor(event.target.value)}/></label><label>Stroke <select value={stroke} onChange={(event)=>setStroke(Number(event.target.value))}><option value="2">Fine</option><option value="4">Medium</option><option value="8">Bold</option></select></label><button disabled={!undo.length} onClick={()=>{const prior=undo.at(-1)!;setRedo((items)=>[...items,layers]);setLayers(prior);setUndo((items)=>items.slice(0,-1))}}>Undo</button><button disabled={!redo.length} onClick={()=>{const next=redo.at(-1)!;setUndo((items)=>[...items,layers]);setLayers(next);setRedo((items)=>items.slice(0,-1))}}>Redo</button><button disabled={!selected} onClick={()=>{commit(layers);setLayers((items)=>items.filter((item)=>item.id!==selected));setSelected(undefined)}}>Delete layer</button></div>{error&&<p className="capture-error" role="alert">{error}</p>}<div className="capture-canvas-wrap"><canvas ref={canvas} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}/></div><footer><span>Redaction changes this source and future copies; existing copies remain independent.</span><button onClick={()=>void save(false)}>Save layers</button><button className="primary" onClick={()=>void save(true)}>Flatten & save</button></footer></section>
}

export function ScreenCaptureStudio({workspaceId,chatId,defaultMode,onClose,onNotice}:{workspaceId:string;chatId?:string;defaultMode:'region'|'window'|'display';onClose:()=>void;onNotice:(value:string)=>void}){
  const [mode,setMode]=useState<'region'|'window'|'display'>(defaultMode),[sources,setSources]=useState<Awaited<ReturnType<Window['waypoint']['screenCaptureSources']>>>([]),[captures,setCaptures]=useState<ScreenCaptureView[]>([]),[selected,setSelected]=useState<ScreenCaptureView>(),[justCaptured,setJustCaptured]=useState<ScreenCaptureView>(),[image,setImage]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('')
  async function reload(){setCaptures(await window.waypoint.listScreenCaptures(workspaceId))}
  useEffect(()=>{void window.waypoint.listScreenCaptures(workspaceId).then(setCaptures);return()=>{void window.waypoint.cancelScreenCaptureSources(workspaceId)}},[workspaceId])
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();void window.waypoint.cancelScreenCaptureSources(workspaceId);onClose()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[onClose,workspaceId])
  async function choose(){setLoading(true);setError('');try{setSources(await window.waypoint.screenCaptureSources(workspaceId,mode))}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setLoading(false)}}
  async function openEditor(capture:ScreenCaptureView){if(sources.length){setJustCaptured(capture);return}const data=await window.waypoint.readScreenCapture(workspaceId,capture.id);setSelected({...capture,workspaceId} as ScreenCaptureView);setImage(`data:${data.mediaType};base64,${data.dataBase64}`)}
  if(selected)return <div className="capture-overlay"><CaptureEditor workspaceId={workspaceId} capture={selected} dataUrl={image} onClose={()=>setSelected(undefined)} onSaved={(next)=>{setSelected(next);void reload();onNotice('Screenshot saved locally')}}/></div>
  if(justCaptured)return <div className="capture-overlay" role="dialog" aria-modal="true" aria-label="Screenshot captured"><section className="capture-studio capture-preview"><header><div><small>CAPTURED · LOCAL ONLY</small><h2>Screenshot ready</h2><p>{justCaptured.sourceName} · {justCaptured.width} × {justCaptured.height}</p></div><button autoFocus aria-label="Close screenshot preview" onClick={()=>setJustCaptured(undefined)}>×</button></header><div className="capture-preview-actions" aria-label="Screenshot quick actions"><button onClick={()=>void window.waypoint.copyScreenCapture(workspaceId,justCaptured.id).then(()=>onNotice('Copied screenshot'))}>Copy</button><button onClick={()=>void window.waypoint.saveScreenCapture(workspaceId,justCaptured.id)}>Save locally</button><button className="primary" onClick={()=>void openEditor(justCaptured)}>Annotate</button><button disabled={!chatId} onClick={()=>chatId&&void window.waypoint.addScreenCaptureToChat(workspaceId,justCaptured.id,chatId).then(()=>onNotice('Screenshot queued in this chat'))}>Add to Chat</button><button onClick={()=>void window.waypoint.addScreenCaptureToKnowledge(workspaceId,justCaptured.id).then(()=>onNotice('Screenshot added to Knowledge'))}>Add to Knowledge</button><button className="danger" onClick={()=>void window.waypoint.deleteScreenCapture(workspaceId,justCaptured.id).then(async()=>{setJustCaptured(undefined);await reload()})}>Discard</button></div><button onClick={()=>setJustCaptured(undefined)}>Keep and return to captures</button></section></div>
  return <div className="capture-overlay" role="dialog" aria-modal="true" aria-labelledby="capture-title"><section className="capture-studio"><header><div><small>MANUAL · LOCAL ONLY</small><h2 id="capture-title">Capture a screenshot</h2><p>Waypoint captures only after you choose a source. Nothing is uploaded or sent to a model.</p></div><button aria-label="Close screen capture" onClick={onClose}>×</button></header><div className="capture-mode" role="group" aria-label="Capture mode">{(['region','window','display'] as const).map((item)=><button aria-pressed={mode===item} className={mode===item?'active':''} onClick={()=>setMode(item)} key={item}>{item==='region'?'Region (crop)':item[0].toUpperCase()+item.slice(1)}</button>)}</div><button className="capture-start" disabled={loading} onClick={()=>void choose()}>{loading?'Checking permission…':'Choose capture source'}</button><button className="capture-browser-import" onClick={()=>void window.waypoint.importBrowserScreenCapture(workspaceId).then(async(capture)=>{await reload();await openEditor(capture)}).catch((reason)=>setError(reason instanceof Error?reason.message:String(reason)))}>Annotate current In-App Browser</button>{error&&<p className="capture-error" role="alert">{error}</p>}{sources.length>0&&<div className="capture-source-grid">{sources.map((source)=><button key={source.token} onClick={()=>void window.waypoint.createScreenCapture(workspaceId,source.token).then(async(capture)=>{setSources([]);await reload();await openEditor(capture)}).catch((reason)=>setError(String(reason)))}><img src={source.thumbnailDataUrl} alt=""/><strong>{source.name}</strong><small>{source.width} × {source.height}</small></button>)}</div>}<div className="capture-library"><h3>Recent captures</h3>{captures.length===0?<p>No screenshots in this workspace.</p>:captures.map((capture)=><article key={capture.id}><button className="capture-open" onClick={()=>void openEditor(capture)}><strong>{capture.title}</strong><small>{new Date(capture.capturedAt).toLocaleString()} · expires {new Date(capture.expiresAt).toLocaleDateString()}</small></button><div aria-label="Screenshot quick actions"><button onClick={()=>void window.waypoint.copyScreenCapture(workspaceId,capture.id).then(()=>onNotice('Copied screenshot'))}>Copy</button><button onClick={()=>void window.waypoint.saveScreenCapture(workspaceId,capture.id)}>Save</button><button onClick={()=>void openEditor(capture)}>Annotate</button><button disabled={!chatId} onClick={()=>chatId&&void window.waypoint.addScreenCaptureToChat(workspaceId,capture.id,chatId).then(()=>onNotice('Screenshot queued in this chat'))}>Add to Chat</button><button onClick={()=>void window.waypoint.addScreenCaptureToKnowledge(workspaceId,capture.id).then(()=>onNotice('Screenshot added to Knowledge'))}>Add to Knowledge</button><button className="danger" onClick={()=>void window.waypoint.deleteScreenCapture(workspaceId,capture.id).then(()=>reload())}>Discard</button></div></article>)}</div></section></div>
}
