export const MAX_CAPTURE_SECONDS=120
export class VoiceActivityBoundary{private speech=0;private silence=0;private fired=false;constructor(private readonly sampleRate:number){}push(chunk:Float32Array){const rms=Math.sqrt(chunk.reduce((sum,value)=>sum+value*value,0)/Math.max(1,chunk.length));if(rms>.018){this.speech+=chunk.length;this.silence=0}else if(this.speech>=this.sampleRate*.25)this.silence+=chunk.length;if(!this.fired&&this.silence>=this.sampleRate*1.1){this.fired=true;return true}return false}}
export function encodePcmWav(chunks:Float32Array[],sampleRate:number){const samples=chunks.reduce((sum,item)=>sum+item.length,0),buffer=new ArrayBuffer(44+samples*2),view=new DataView(buffer);const write=(offset:number,value:string)=>{for(let index=0;index<value.length;index++)view.setUint8(offset+index,value.charCodeAt(index))};write(0,'RIFF');view.setUint32(4,36+samples*2,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,samples*2,true);let offset=44;for(const chunk of chunks)for(const sample of chunk){view.setInt16(offset,Math.max(-1,Math.min(1,sample))*0x7fff,true);offset+=2}return new Uint8Array(buffer)}
export class BrowserPcmCapture{
 private stream?:MediaStream;private context?:AudioContext;private processor?:ScriptProcessorNode;private source?:MediaStreamAudioSourceNode;private chunks:Float32Array[]=[];private samples=0;private timer?:number;private ending=false
 async start(deviceId?:string,onEnded?:(reason:'device_lost'|'capture_limit')=>void,onSpeechEnd?:()=>void){if(this.stream)throw new Error('voice_capture_active');this.ending=false;this.stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:deviceId?{exact:deviceId}:undefined,echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});this.context=new AudioContext();this.source=this.context.createMediaStreamSource(this.stream);this.processor=this.context.createScriptProcessor(4096,1,1);const maxSamples=this.context.sampleRate*MAX_CAPTURE_SECONDS,boundary=new VoiceActivityBoundary(this.context.sampleRate);this.processor.onaudioprocess=(event)=>{if(this.samples>=maxSamples)return;const input=event.inputBuffer.getChannelData(0),remaining=maxSamples-this.samples,copy=input.slice(0,remaining);this.chunks.push(copy);this.samples+=copy.length;if(onSpeechEnd&&boundary.push(copy))queueMicrotask(onSpeechEnd)};for(const track of this.stream.getAudioTracks())track.addEventListener('ended',()=>{if(!this.ending)onEnded?.('device_lost')},{once:true});this.timer=window.setTimeout(()=>{if(!this.ending)onEnded?.('capture_limit')},MAX_CAPTURE_SECONDS*1000);this.source.connect(this.processor);this.processor.connect(this.context.destination)}
 async stop(){if(!this.stream||!this.context)throw new Error('voice_capture_inactive');const rate=this.context.sampleRate;this.processor?.disconnect();this.source?.disconnect();this.stream.getTracks().forEach((track)=>track.stop());await this.context.close();const result=encodePcmWav(this.chunks,rate);this.reset();return result}
 async cancel(){this.processor?.disconnect();this.source?.disconnect();this.stream?.getTracks().forEach((track)=>track.stop());await this.context?.close().catch(()=>undefined);this.reset()}
 private reset(){this.ending=true;if(this.timer!==undefined)window.clearTimeout(this.timer);this.timer=undefined;this.stream=undefined;this.context=undefined;this.processor=undefined;this.source=undefined;this.chunks=[];this.samples=0}
}
