export const MAX_CAPTURE_SECONDS=120
export class VoiceActivityBoundary{private speech=0;private silence=0;private fired=false;constructor(private readonly sampleRate:number){}push(chunk:Float32Array){const rms=Math.sqrt(chunk.reduce((sum,value)=>sum+value*value,0)/Math.max(1,chunk.length));if(rms>.018){this.speech+=chunk.length;this.silence=0}else if(this.speech>=this.sampleRate*.25)this.silence+=chunk.length;if(!this.fired&&this.silence>=this.sampleRate*1.1){this.fired=true;return true}return false}}
export class SpeechStartBoundary{private speech=0;private fired=false;constructor(private readonly sampleRate:number){}push(chunk:Float32Array){const rms=Math.sqrt(chunk.reduce((sum,value)=>sum+value*value,0)/Math.max(1,chunk.length));this.speech=rms>.035?this.speech+chunk.length:0;if(!this.fired&&this.speech>=this.sampleRate*.18){this.fired=true;return true}return false}}
export class BargeInAudioBuffer{private readonly startBoundary:SpeechStartBoundary;private readonly endBoundary:VoiceActivityBoundary;private readonly maxPreRoll:number;private readonly maxSamples:number;private chunks:Float32Array[]=[];private samples=0;private capturing=false;constructor(readonly sampleRate:number){this.startBoundary=new SpeechStartBoundary(sampleRate);this.endBoundary=new VoiceActivityBoundary(sampleRate);this.maxPreRoll=Math.ceil(sampleRate*.25);this.maxSamples=sampleRate*MAX_CAPTURE_SECONDS}push(input:Float32Array):'monitoring'|'speech'|'capturing'|'end'|'limit'{const chunk=new Float32Array(input);this.chunks.push(chunk);this.samples+=chunk.length;if(this.capturing){if(this.samples>=this.maxSamples)return'limit';return this.endBoundary.push(chunk)?'end':'capturing'}while(this.samples>this.maxPreRoll&&this.chunks.length>1)this.samples-=this.chunks.shift()!.length;if(!this.startBoundary.push(chunk))return'monitoring';this.capturing=true;for(const held of this.chunks)this.endBoundary.push(held);return'speech'}take(){const result=this.chunks;this.chunks=[];this.samples=0;return result}}
export function encodePcmWav(chunks:Float32Array[],sampleRate:number){const samples=chunks.reduce((sum,item)=>sum+item.length,0),buffer=new ArrayBuffer(44+samples*2),view=new DataView(buffer);const write=(offset:number,value:string)=>{for(let index=0;index<value.length;index++)view.setUint8(offset+index,value.charCodeAt(index))};write(0,'RIFF');view.setUint32(4,36+samples*2,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,samples*2,true);let offset=44;for(const chunk of chunks)for(const sample of chunk){view.setInt16(offset,Math.max(-1,Math.min(1,sample))*0x7fff,true);offset+=2}return new Uint8Array(buffer)}
export class BrowserPcmCapture{
 private stream?:MediaStream;private context?:AudioContext;private processor?:ScriptProcessorNode;private source?:MediaStreamAudioSourceNode;private chunks:Float32Array[]=[];private samples=0;private timer?:number;private ending=false
 async start(deviceId?:string,onEnded?:(reason:'device_lost'|'capture_limit')=>void,onSpeechEnd?:()=>void){if(this.stream)throw new Error('voice_capture_active');this.ending=false;this.stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:deviceId?{exact:deviceId}:undefined,echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});this.context=new AudioContext();this.source=this.context.createMediaStreamSource(this.stream);this.processor=this.context.createScriptProcessor(4096,1,1);const maxSamples=this.context.sampleRate*MAX_CAPTURE_SECONDS,boundary=new VoiceActivityBoundary(this.context.sampleRate);this.processor.onaudioprocess=(event)=>{if(this.samples>=maxSamples)return;const input=event.inputBuffer.getChannelData(0),remaining=maxSamples-this.samples,copy=input.slice(0,remaining);this.chunks.push(copy);this.samples+=copy.length;if(onSpeechEnd&&boundary.push(copy))queueMicrotask(onSpeechEnd)};for(const track of this.stream.getAudioTracks())track.addEventListener('ended',()=>{if(!this.ending)onEnded?.('device_lost')},{once:true});this.timer=window.setTimeout(()=>{if(!this.ending)onEnded?.('capture_limit')},MAX_CAPTURE_SECONDS*1000);this.source.connect(this.processor);this.processor.connect(this.context.destination)}
 async stop(){if(!this.stream||!this.context)throw new Error('voice_capture_inactive');const rate=this.context.sampleRate;this.processor?.disconnect();this.source?.disconnect();this.stream.getTracks().forEach((track)=>track.stop());await this.context.close();const result=encodePcmWav(this.chunks,rate);this.reset();return result}
 async cancel(){this.processor?.disconnect();this.source?.disconnect();this.stream?.getTracks().forEach((track)=>track.stop());await this.context?.close().catch(()=>undefined);this.reset()}
 private reset(){this.ending=true;if(this.timer!==undefined)window.clearTimeout(this.timer);this.timer=undefined;this.stream=undefined;this.context=undefined;this.processor=undefined;this.source=undefined;this.chunks=[];this.samples=0}
}
export class BrowserSpeechMonitor{private stream?:MediaStream;private context?:AudioContext;private processor?:ScriptProcessorNode;private source?:MediaStreamAudioSourceNode;private active=false;private capturing=false;private buffer?:BargeInAudioBuffer
 async start(deviceId:string|undefined,onSpeech:()=>void,onCaptureEnd:()=>void,onFailure:(reason:'device_lost'|'capture_limit')=>void){await this.stop();this.stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:deviceId?{exact:deviceId}:undefined,echoCancellation:true,noiseSuppression:true,autoGainControl:false},video:false});this.context=new AudioContext();this.buffer=new BargeInAudioBuffer(this.context.sampleRate);this.source=this.context.createMediaStreamSource(this.stream);this.processor=this.context.createScriptProcessor(2048,1,1);const armedAt=performance.now()+250;this.active=true;this.stream.getAudioTracks().forEach((track)=>{track.onended=()=>{if(this.active||this.capturing)onFailure('device_lost')}});this.processor.onaudioprocess=(event)=>{if(!this.buffer||(!this.capturing&&(!this.active||performance.now()<armedAt)))return;const state=this.buffer.push(event.inputBuffer.getChannelData(0));if(state==='speech'){this.active=false;this.capturing=true;queueMicrotask(onSpeech)}else if(state==='end'){this.capturing=false;queueMicrotask(onCaptureEnd)}else if(state==='limit'){this.capturing=false;queueMicrotask(()=>onFailure('capture_limit'))}};this.source.connect(this.processor);this.processor.connect(this.context.destination)}
 async finish(){const buffer=this.buffer;await this.teardown();const chunks=buffer?.take()??[];if(!chunks.length||!buffer?.sampleRate)throw new Error('voice_audio_empty');const wav=encodePcmWav(chunks,buffer.sampleRate);this.reset();return wav}
 async stop(){await this.teardown();this.reset()}
 private async teardown(){this.active=false;this.capturing=false;this.processor?.disconnect();this.source?.disconnect();this.stream?.getTracks().forEach((track)=>{track.onended=null;track.stop()});await this.context?.close().catch(()=>undefined)}
 private reset(){this.stream=undefined;this.context=undefined;this.processor=undefined;this.source=undefined;this.buffer=undefined}}

export type VoiceAudioChunk={workspaceId:string;chatId:string;turnId:number;index:number;sampleRate:number;samples:Float32Array}
type AudioSourceLike={buffer:AudioBuffer|null;onended:(()=>void)|null;connect(target:AudioNode):AudioNode;start(when?:number):void;stop():void}
type AudioContextLike={currentTime:number;destination:AudioDestinationNode;state:string;createBuffer(channels:number,length:number,sampleRate:number):AudioBuffer;createBufferSource():AudioSourceLike;resume():Promise<void>;close():Promise<void>}
export class BrowserVoicePlayer{
 private context?:AudioContextLike;private scope?:Omit<VoiceAudioChunk,'samples'|'index'|'sampleRate'>;private sources=new Set<AudioSourceLike>();private nextAt=0;private expectedIndex=0;private generated=false;private terminal=false
 constructor(private readonly createContext:()=>AudioContextLike=()=>new AudioContext() as unknown as AudioContextLike,private readonly onComplete:(scope:{workspaceId:string;chatId:string;turnId:number})=>void=()=>undefined,private readonly onStopped:(scope:{workspaceId:string;chatId:string;turnId:number})=>void=()=>undefined){}
 private same(value:{workspaceId:string;chatId:string;turnId:number}){return Boolean(this.scope&&this.scope.workspaceId===value.workspaceId&&this.scope.chatId===value.chatId&&this.scope.turnId===value.turnId)}
 async push(value:VoiceAudioChunk){if(!this.scope)this.scope={workspaceId:value.workspaceId,chatId:value.chatId,turnId:value.turnId};if(!this.same(value)||value.index!==this.expectedIndex||value.sampleRate<8_000||value.sampleRate>96_000||!value.samples.length)return false;this.expectedIndex++;this.context??=this.createContext();if(this.context.state==='suspended')await this.context.resume();const buffer=this.context.createBuffer(1,value.samples.length,value.sampleRate);buffer.getChannelData(0).set(value.samples);const source=this.context.createBufferSource();source.buffer=buffer;source.connect(this.context.destination);this.sources.add(source);source.onended=()=>{this.sources.delete(source);this.finishIfDone()};const when=Math.max(this.context.currentTime+.015,this.nextAt);this.nextAt=when+value.samples.length/value.sampleRate;source.start(when);return true}
 end(value:{workspaceId:string;chatId:string;turnId:number}){if(!this.same(value))return;this.generated=true;this.finishIfDone()}
 async stop(value?:{workspaceId:string;chatId:string;turnId:number}){if(value&&!this.same(value))return false;const scope=this.scope;this.terminal=true;for(const source of this.sources)try{source.onended=null;source.stop()}catch{/* already ended */}this.sources.clear();await this.context?.close().catch(()=>undefined);this.reset();if(scope)this.onStopped(scope);return true}
 private finishIfDone(){if(!this.generated||this.sources.size||this.terminal||!this.scope)return;this.terminal=true;const scope=this.scope;void this.context?.close().catch(()=>undefined);this.reset();this.onComplete(scope)}
 private reset(){this.context=undefined;this.scope=undefined;this.sources.clear();this.nextAt=0;this.expectedIndex=0;this.generated=false;this.terminal=false}
}
